/* capicitor.c generated by valac 0.24.0, the Vala compiler
 * generated from capicitor.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * capacitor.vala
 * Copyright (C) 2014 Steven Vanden Branden <StevenVandenBrandenstift@gmail.com>
 *
 * ElektroSim is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ElektroSim is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <cairo.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <float.h>
#include <math.h>


#define ELEKTRO_SIM_TYPE_COMPONENT (elektro_sim_component_get_type ())
#define ELEKTRO_SIM_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEKTRO_SIM_TYPE_COMPONENT, ElektroSimComponent))
#define ELEKTRO_SIM_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEKTRO_SIM_TYPE_COMPONENT, ElektroSimComponentClass))
#define ELEKTRO_SIM_IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEKTRO_SIM_TYPE_COMPONENT))
#define ELEKTRO_SIM_IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEKTRO_SIM_TYPE_COMPONENT))
#define ELEKTRO_SIM_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEKTRO_SIM_TYPE_COMPONENT, ElektroSimComponentClass))

typedef struct _ElektroSimComponent ElektroSimComponent;
typedef struct _ElektroSimComponentClass ElektroSimComponentClass;
typedef struct _ElektroSimComponentPrivate ElektroSimComponentPrivate;

#define ELEKTRO_SIM_TYPE_PARAMETER (elektro_sim_parameter_get_type ())
#define ELEKTRO_SIM_PARAMETER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEKTRO_SIM_TYPE_PARAMETER, ElektroSimParameter))
#define ELEKTRO_SIM_PARAMETER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEKTRO_SIM_TYPE_PARAMETER, ElektroSimParameterClass))
#define ELEKTRO_SIM_IS_PARAMETER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEKTRO_SIM_TYPE_PARAMETER))
#define ELEKTRO_SIM_IS_PARAMETER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEKTRO_SIM_TYPE_PARAMETER))
#define ELEKTRO_SIM_PARAMETER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEKTRO_SIM_TYPE_PARAMETER, ElektroSimParameterClass))

typedef struct _ElektroSimParameter ElektroSimParameter;
typedef struct _ElektroSimParameterClass ElektroSimParameterClass;

#define ELEKTRO_SIM_TYPE_POINT (elektro_sim_point_get_type ())
#define ELEKTRO_SIM_POINT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEKTRO_SIM_TYPE_POINT, ElektroSimPoint))
#define ELEKTRO_SIM_POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEKTRO_SIM_TYPE_POINT, ElektroSimPointClass))
#define ELEKTRO_SIM_IS_POINT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEKTRO_SIM_TYPE_POINT))
#define ELEKTRO_SIM_IS_POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEKTRO_SIM_TYPE_POINT))
#define ELEKTRO_SIM_POINT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEKTRO_SIM_TYPE_POINT, ElektroSimPointClass))

typedef struct _ElektroSimPoint ElektroSimPoint;
typedef struct _ElektroSimPointClass ElektroSimPointClass;

#define ELEKTRO_SIM_TYPE_CAPACITOR (elektro_sim_capacitor_get_type ())
#define ELEKTRO_SIM_CAPACITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEKTRO_SIM_TYPE_CAPACITOR, ElektroSimCapacitor))
#define ELEKTRO_SIM_CAPACITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEKTRO_SIM_TYPE_CAPACITOR, ElektroSimCapacitorClass))
#define ELEKTRO_SIM_IS_CAPACITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEKTRO_SIM_TYPE_CAPACITOR))
#define ELEKTRO_SIM_IS_CAPACITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEKTRO_SIM_TYPE_CAPACITOR))
#define ELEKTRO_SIM_CAPACITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEKTRO_SIM_TYPE_CAPACITOR, ElektroSimCapacitorClass))

typedef struct _ElektroSimCapacitor ElektroSimCapacitor;
typedef struct _ElektroSimCapacitorClass ElektroSimCapacitorClass;
typedef struct _ElektroSimCapacitorPrivate ElektroSimCapacitorPrivate;

#define ELEKTRO_SIM_PARAMETER_TYPE_WIDGET_STYLE (elektro_sim_parameter_widget_style_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _elektro_sim_point_unref0(var) ((var == NULL) ? NULL : (var = (elektro_sim_point_unref (var), NULL)))

#define ELEKTRO_SIM_COMPONENT_TYPE_ORIENTATION (elektro_sim_component_orientation_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

#define ELEKTRO_SIM_COMPONENT_TYPE_COMPONENT_TYPE (elektro_sim_component_component_type_get_type ())

struct _ElektroSimComponent {
	GtkListBoxRow parent_instance;
	ElektroSimComponentPrivate * priv;
	GeeArrayList* parameters;
	GeeArrayList* connections;
	cairo_surface_t* image_surface;
	cairo_t* image_context;
	cairo_surface_t* emoticon_surface;
	cairo_t* emoticon_context;
};

struct _ElektroSimComponentClass {
	GtkListBoxRowClass parent_class;
	ElektroSimComponent* (*clone) (ElektroSimComponent* self);
	void (*snap) (ElektroSimComponent* self, gint range, gint x, gint y);
	void (*draw_image) (ElektroSimComponent* self, cairo_t* cr);
	void (*clear_counter) (ElektroSimComponent* self);
	gchar* (*get_netlist_line) (ElektroSimComponent* self);
};

struct _ElektroSimCapacitor {
	ElektroSimComponent parent_instance;
	ElektroSimCapacitorPrivate * priv;
};

struct _ElektroSimCapacitorClass {
	ElektroSimComponentClass parent_class;
};

typedef enum  {
	ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_NONE,
	ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_LABEL,
	ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_ENTRY,
	ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_OPTIONS,
	ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_SLIDER
} ElektroSimParameterWidgetStyle;

typedef enum  {
	ELEKTRO_SIM_COMPONENT_ORIENTATION_NONE,
	ELEKTRO_SIM_COMPONENT_ORIENTATION_RIGHT,
	ELEKTRO_SIM_COMPONENT_ORIENTATION_LEFT,
	ELEKTRO_SIM_COMPONENT_ORIENTATION_DOWN,
	ELEKTRO_SIM_COMPONENT_ORIENTATION_UP
} ElektroSimComponentOrientation;

typedef enum  {
	ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_COMPONENT,
	ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_TEMPLATE,
	ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_SIMULATION
} ElektroSimComponentComponentType;


static gpointer elektro_sim_capacitor_parent_class = NULL;
extern gint elektro_sim_capacitor_counter;
gint elektro_sim_capacitor_counter = 0;

GType elektro_sim_component_get_type (void) G_GNUC_CONST;
GType elektro_sim_parameter_get_type (void) G_GNUC_CONST;
gpointer elektro_sim_point_ref (gpointer instance);
void elektro_sim_point_unref (gpointer instance);
GParamSpec* elektro_sim_param_spec_point (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void elektro_sim_value_set_point (GValue* value, gpointer v_object);
void elektro_sim_value_take_point (GValue* value, gpointer v_object);
gpointer elektro_sim_value_get_point (const GValue* value);
GType elektro_sim_point_get_type (void) G_GNUC_CONST;
GType elektro_sim_capacitor_get_type (void) G_GNUC_CONST;
enum  {
	ELEKTRO_SIM_CAPACITOR_DUMMY_PROPERTY
};
ElektroSimCapacitor* elektro_sim_capacitor_new (gdouble capacitance, gdouble ratedVoltage);
ElektroSimCapacitor* elektro_sim_capacitor_construct (GType object_type, gdouble capacitance, gdouble ratedVoltage);
ElektroSimComponent* elektro_sim_component_construct (GType object_type, const gchar* name);
void elektro_sim_component_set_width (ElektroSimComponent* self, gint value);
void elektro_sim_component_set_height (ElektroSimComponent* self, gint value);
GType elektro_sim_parameter_widget_style_get_type (void) G_GNUC_CONST;
ElektroSimParameter* elektro_sim_component_add_parameter (ElektroSimComponent* self, const gchar* name, gdouble val, const gchar* unit, ElektroSimParameterWidgetStyle simulation, ElektroSimParameterWidgetStyle edit, GeeArrayList* options);
static void elektro_sim_capacitor_real_draw_image (ElektroSimComponent* base, cairo_t* cr);
gint elektro_sim_point_get_x (ElektroSimPoint* self);
gint elektro_sim_point_get_y (ElektroSimPoint* self);
GType elektro_sim_component_orientation_get_type (void) G_GNUC_CONST;
ElektroSimComponentOrientation elektro_sim_component_get_orientation (ElektroSimComponent* self);
gint elektro_sim_component_get_width (ElektroSimComponent* self);
gint elektro_sim_component_get_height (ElektroSimComponent* self);
void elektro_sim_component_draw_emoticon (ElektroSimComponent* self, cairo_t* cr, gint x, gint y);
static void elektro_sim_capacitor_real_clear_counter (ElektroSimComponent* base);
static ElektroSimComponent* elektro_sim_capacitor_real_clone (ElektroSimComponent* base);
ElektroSimParameter* elektro_sim_component_get_parameter (ElektroSimComponent* self, const gchar* name);
gdouble elektro_sim_parameter_get_val (ElektroSimParameter* self);
void elektro_sim_component_set_name (ElektroSimComponent* self, const gchar* new_name);
GType elektro_sim_component_component_type_get_type (void) G_GNUC_CONST;
void elektro_sim_component_set_componentType (ElektroSimComponent* self, ElektroSimComponentComponentType value);
static void elektro_sim_capacitor_real_snap (ElektroSimComponent* base, gint range, gint x, gint y);
ElektroSimPoint* elektro_sim_point_new (gint x, gint y);
ElektroSimPoint* elektro_sim_point_construct (GType object_type, gint x, gint y);
ElektroSimPoint* elektro_sim_point_point_nearby (ElektroSimPoint* self, gint range);
ElektroSimComponentOrientation elektro_sim_point_connect_component (ElektroSimPoint* self, ElektroSimComponent* component);
void elektro_sim_component_set_orientation (ElektroSimComponent* self, ElektroSimComponentOrientation value);
static gchar* elektro_sim_capacitor_real_get_netlist_line (ElektroSimComponent* base);
gint elektro_sim_point_get_net (ElektroSimPoint* self);
static void elektro_sim_capacitor_finalize (GObject* obj);


ElektroSimCapacitor* elektro_sim_capacitor_construct (GType object_type, gdouble capacitance, gdouble ratedVoltage) {
	ElektroSimCapacitor * self = NULL;
	gdouble _tmp0_ = 0.0;
	GeeArrayList* _tmp1_ = NULL;
	GeeArrayList* _tmp2_ = NULL;
	ElektroSimParameter* _tmp3_ = NULL;
	ElektroSimParameter* _tmp4_ = NULL;
	gdouble _tmp5_ = 0.0;
	GeeArrayList* _tmp6_ = NULL;
	GeeArrayList* _tmp7_ = NULL;
	ElektroSimParameter* _tmp8_ = NULL;
	ElektroSimParameter* _tmp9_ = NULL;
	self = (ElektroSimCapacitor*) elektro_sim_component_construct (object_type, "Capacitor");
	elektro_sim_component_set_width ((ElektroSimComponent*) self, 200);
	elektro_sim_component_set_height ((ElektroSimComponent*) self, 50);
	_tmp0_ = capacitance;
	_tmp1_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = elektro_sim_component_add_parameter ((ElektroSimComponent*) self, "C", _tmp0_, "F", ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_SLIDER, ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_SLIDER, _tmp2_);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_g_object_unref0 (_tmp2_);
	_tmp5_ = ratedVoltage;
	_tmp6_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	_tmp7_ = _tmp6_;
	_tmp8_ = elektro_sim_component_add_parameter ((ElektroSimComponent*) self, "rated voltage", _tmp5_, "V", ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_SLIDER, ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_SLIDER, _tmp7_);
	_tmp9_ = _tmp8_;
	_g_object_unref0 (_tmp9_);
	_g_object_unref0 (_tmp7_);
	return self;
}


ElektroSimCapacitor* elektro_sim_capacitor_new (gdouble capacitance, gdouble ratedVoltage) {
	return elektro_sim_capacitor_construct (ELEKTRO_SIM_TYPE_CAPACITOR, capacitance, ratedVoltage);
}


static void elektro_sim_capacitor_real_draw_image (ElektroSimComponent* base, cairo_t* cr) {
	ElektroSimCapacitor * self;
	gint p1_x = 0;
	GeeArrayList* _tmp0_ = NULL;
	gpointer _tmp1_ = NULL;
	ElektroSimPoint* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	gint p1_y = 0;
	GeeArrayList* _tmp6_ = NULL;
	gpointer _tmp7_ = NULL;
	ElektroSimPoint* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	gint p2_x = 0;
	GeeArrayList* _tmp12_ = NULL;
	gpointer _tmp13_ = NULL;
	ElektroSimPoint* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
	gint p2_y = 0;
	GeeArrayList* _tmp18_ = NULL;
	gpointer _tmp19_ = NULL;
	ElektroSimPoint* _tmp20_ = NULL;
	gint _tmp21_ = 0;
	gint _tmp22_ = 0;
	gint _tmp23_ = 0;
	gint x = 0;
	gint y = 0;
	gboolean _tmp24_ = FALSE;
	ElektroSimComponentOrientation _tmp25_ = 0;
	ElektroSimComponentOrientation _tmp26_ = 0;
	cairo_t* _tmp163_ = NULL;
	gint _tmp164_ = 0;
	gint _tmp165_ = 0;
	self = (ElektroSimCapacitor*) base;
	g_return_if_fail (cr != NULL);
	_tmp0_ = ((ElektroSimComponent*) self)->connections;
	_tmp1_ = gee_abstract_list_get ((GeeAbstractList*) _tmp0_, 0);
	_tmp2_ = (ElektroSimPoint*) _tmp1_;
	_tmp3_ = elektro_sim_point_get_x (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = _tmp4_;
	_elektro_sim_point_unref0 (_tmp2_);
	p1_x = _tmp5_;
	_tmp6_ = ((ElektroSimComponent*) self)->connections;
	_tmp7_ = gee_abstract_list_get ((GeeAbstractList*) _tmp6_, 0);
	_tmp8_ = (ElektroSimPoint*) _tmp7_;
	_tmp9_ = elektro_sim_point_get_y (_tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = _tmp10_;
	_elektro_sim_point_unref0 (_tmp8_);
	p1_y = _tmp11_;
	_tmp12_ = ((ElektroSimComponent*) self)->connections;
	_tmp13_ = gee_abstract_list_get ((GeeAbstractList*) _tmp12_, 1);
	_tmp14_ = (ElektroSimPoint*) _tmp13_;
	_tmp15_ = elektro_sim_point_get_x (_tmp14_);
	_tmp16_ = _tmp15_;
	_tmp17_ = _tmp16_;
	_elektro_sim_point_unref0 (_tmp14_);
	p2_x = _tmp17_;
	_tmp18_ = ((ElektroSimComponent*) self)->connections;
	_tmp19_ = gee_abstract_list_get ((GeeAbstractList*) _tmp18_, 1);
	_tmp20_ = (ElektroSimPoint*) _tmp19_;
	_tmp21_ = elektro_sim_point_get_y (_tmp20_);
	_tmp22_ = _tmp21_;
	_tmp23_ = _tmp22_;
	_elektro_sim_point_unref0 (_tmp20_);
	p2_y = _tmp23_;
	_tmp25_ = elektro_sim_component_get_orientation ((ElektroSimComponent*) self);
	_tmp26_ = _tmp25_;
	if (_tmp26_ == ELEKTRO_SIM_COMPONENT_ORIENTATION_RIGHT) {
		_tmp24_ = TRUE;
	} else {
		ElektroSimComponentOrientation _tmp27_ = 0;
		ElektroSimComponentOrientation _tmp28_ = 0;
		_tmp27_ = elektro_sim_component_get_orientation ((ElektroSimComponent*) self);
		_tmp28_ = _tmp27_;
		_tmp24_ = _tmp28_ == ELEKTRO_SIM_COMPONENT_ORIENTATION_LEFT;
	}
	if (_tmp24_) {
		gint _tmp29_ = 0;
		gint _tmp30_ = 0;
		cairo_t* _tmp34_ = NULL;
		cairo_t* _tmp35_ = NULL;
		gint _tmp36_ = 0;
		gint _tmp37_ = 0;
		cairo_t* _tmp38_ = NULL;
		gint _tmp39_ = 0;
		gint _tmp40_ = 0;
		gint _tmp41_ = 0;
		gint _tmp42_ = 0;
		cairo_t* _tmp43_ = NULL;
		gint _tmp44_ = 0;
		gint _tmp45_ = 0;
		gint _tmp46_ = 0;
		gint _tmp47_ = 0;
		gint _tmp48_ = 0;
		gint _tmp49_ = 0;
		gint _tmp50_ = 0;
		gint _tmp51_ = 0;
		cairo_t* _tmp52_ = NULL;
		gint _tmp53_ = 0;
		gint _tmp54_ = 0;
		cairo_t* _tmp55_ = NULL;
		gint _tmp56_ = 0;
		gint _tmp57_ = 0;
		gint _tmp58_ = 0;
		gint _tmp59_ = 0;
		gint _tmp60_ = 0;
		gint _tmp61_ = 0;
		gint _tmp62_ = 0;
		gint _tmp63_ = 0;
		cairo_t* _tmp64_ = NULL;
		gint _tmp65_ = 0;
		gint _tmp66_ = 0;
		cairo_t* _tmp67_ = NULL;
		gint _tmp68_ = 0;
		gint _tmp69_ = 0;
		cairo_t* _tmp70_ = NULL;
		gint _tmp71_ = 0;
		gint _tmp72_ = 0;
		gint _tmp73_ = 0;
		gint _tmp74_ = 0;
		cairo_t* _tmp75_ = NULL;
		cairo_t* _tmp76_ = NULL;
		cairo_t* _tmp77_ = NULL;
		cairo_t* _tmp78_ = NULL;
		gint _tmp79_ = 0;
		gint _tmp80_ = 0;
		cairo_t* _tmp81_ = NULL;
		gint _tmp82_ = 0;
		gint _tmp83_ = 0;
		gint _tmp84_ = 0;
		gint _tmp85_ = 0;
		gint _tmp86_ = 0;
		gint _tmp87_ = 0;
		gint _tmp88_ = 0;
		gint _tmp89_ = 0;
		cairo_t* _tmp90_ = NULL;
		const gchar* _tmp91_ = NULL;
		const gchar* _tmp92_ = NULL;
		cairo_t* _tmp93_ = NULL;
		cairo_t* _tmp94_ = NULL;
		gint _tmp95_ = 0;
		gint _tmp96_ = 0;
		_tmp29_ = p1_x;
		_tmp30_ = p2_x;
		if (_tmp29_ > _tmp30_) {
			gint temp = 0;
			gint _tmp31_ = 0;
			gint _tmp32_ = 0;
			gint _tmp33_ = 0;
			_tmp31_ = p2_x;
			temp = _tmp31_;
			_tmp32_ = p1_x;
			p2_x = _tmp32_;
			_tmp33_ = temp;
			p1_x = _tmp33_;
		}
		_tmp34_ = cr;
		cairo_new_path (_tmp34_);
		_tmp35_ = cr;
		_tmp36_ = p1_x;
		_tmp37_ = p1_y;
		cairo_move_to (_tmp35_, (gdouble) _tmp36_, (gdouble) _tmp37_);
		_tmp38_ = cr;
		_tmp39_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp40_ = _tmp39_;
		_tmp41_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp42_ = _tmp41_;
		cairo_rel_line_to (_tmp38_, (gdouble) ((_tmp40_ / 2) - (_tmp42_ / 20)), (gdouble) 0);
		_tmp43_ = cr;
		_tmp44_ = p1_x;
		_tmp45_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp46_ = _tmp45_;
		_tmp47_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp48_ = _tmp47_;
		_tmp49_ = p1_y;
		_tmp50_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp51_ = _tmp50_;
		cairo_move_to (_tmp43_, (gdouble) ((_tmp44_ + (_tmp46_ / 2)) - (_tmp48_ / 20)), (gdouble) (_tmp49_ - (_tmp51_ / 2)));
		_tmp52_ = cr;
		_tmp53_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp54_ = _tmp53_;
		cairo_rel_line_to (_tmp52_, (gdouble) 0, (gdouble) _tmp54_);
		_tmp55_ = cr;
		_tmp56_ = p1_x;
		_tmp57_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp58_ = _tmp57_;
		_tmp59_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp60_ = _tmp59_;
		_tmp61_ = p1_y;
		_tmp62_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp63_ = _tmp62_;
		cairo_move_to (_tmp55_, (gdouble) ((_tmp56_ + (_tmp58_ / 2)) + (_tmp60_ / 20)), (gdouble) (_tmp61_ - (_tmp63_ / 2)));
		_tmp64_ = cr;
		_tmp65_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp66_ = _tmp65_;
		cairo_rel_line_to (_tmp64_, (gdouble) 0, (gdouble) _tmp66_);
		_tmp67_ = cr;
		_tmp68_ = p2_x;
		_tmp69_ = p2_y;
		cairo_move_to (_tmp67_, (gdouble) _tmp68_, (gdouble) _tmp69_);
		_tmp70_ = cr;
		_tmp71_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp72_ = _tmp71_;
		_tmp73_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp74_ = _tmp73_;
		cairo_rel_line_to (_tmp70_, (gdouble) (((+_tmp72_) / 20) - (_tmp74_ / 2)), (gdouble) 0);
		_tmp75_ = cr;
		cairo_close_path (_tmp75_);
		_tmp76_ = cr;
		cairo_stroke (_tmp76_);
		_tmp77_ = cr;
		cairo_new_path (_tmp77_);
		_tmp78_ = cr;
		_tmp79_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp80_ = _tmp79_;
		cairo_set_font_size (_tmp78_, _tmp80_ * 0.5);
		_tmp81_ = cr;
		_tmp82_ = p1_x;
		_tmp83_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp84_ = _tmp83_;
		_tmp85_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp86_ = _tmp85_;
		_tmp87_ = p1_y;
		_tmp88_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp89_ = _tmp88_;
		cairo_move_to (_tmp81_, (gdouble) ((_tmp82_ + (_tmp84_ / 2)) + (_tmp86_ / 10)), (gdouble) (_tmp87_ - (_tmp89_ / 3)));
		_tmp90_ = cr;
		_tmp91_ = gtk_widget_get_name ((GtkWidget*) self);
		_tmp92_ = _tmp91_;
		cairo_text_path (_tmp90_, _tmp92_);
		_tmp93_ = cr;
		cairo_close_path (_tmp93_);
		_tmp94_ = cr;
		cairo_fill (_tmp94_);
		_tmp95_ = p1_x;
		x = _tmp95_ + 100;
		_tmp96_ = p1_y;
		y = _tmp96_ - 120;
	} else {
		gint _tmp97_ = 0;
		gint _tmp98_ = 0;
		cairo_t* _tmp102_ = NULL;
		cairo_t* _tmp103_ = NULL;
		gint _tmp104_ = 0;
		gint _tmp105_ = 0;
		cairo_t* _tmp106_ = NULL;
		gint _tmp107_ = 0;
		gint _tmp108_ = 0;
		gint _tmp109_ = 0;
		gint _tmp110_ = 0;
		cairo_t* _tmp111_ = NULL;
		gint _tmp112_ = 0;
		gint _tmp113_ = 0;
		gint _tmp114_ = 0;
		gint _tmp115_ = 0;
		gint _tmp116_ = 0;
		gint _tmp117_ = 0;
		gint _tmp118_ = 0;
		gint _tmp119_ = 0;
		cairo_t* _tmp120_ = NULL;
		gint _tmp121_ = 0;
		gint _tmp122_ = 0;
		cairo_t* _tmp123_ = NULL;
		gint _tmp124_ = 0;
		gint _tmp125_ = 0;
		gint _tmp126_ = 0;
		gint _tmp127_ = 0;
		gint _tmp128_ = 0;
		gint _tmp129_ = 0;
		gint _tmp130_ = 0;
		gint _tmp131_ = 0;
		cairo_t* _tmp132_ = NULL;
		gint _tmp133_ = 0;
		gint _tmp134_ = 0;
		cairo_t* _tmp135_ = NULL;
		gint _tmp136_ = 0;
		gint _tmp137_ = 0;
		cairo_t* _tmp138_ = NULL;
		gint _tmp139_ = 0;
		gint _tmp140_ = 0;
		gint _tmp141_ = 0;
		gint _tmp142_ = 0;
		cairo_t* _tmp143_ = NULL;
		cairo_t* _tmp144_ = NULL;
		cairo_t* _tmp145_ = NULL;
		cairo_t* _tmp146_ = NULL;
		gint _tmp147_ = 0;
		gint _tmp148_ = 0;
		cairo_t* _tmp149_ = NULL;
		gint _tmp150_ = 0;
		gint _tmp151_ = 0;
		gint _tmp152_ = 0;
		gint _tmp153_ = 0;
		gint _tmp154_ = 0;
		gint _tmp155_ = 0;
		cairo_t* _tmp156_ = NULL;
		const gchar* _tmp157_ = NULL;
		const gchar* _tmp158_ = NULL;
		cairo_t* _tmp159_ = NULL;
		cairo_t* _tmp160_ = NULL;
		gint _tmp161_ = 0;
		gint _tmp162_ = 0;
		_tmp97_ = p1_y;
		_tmp98_ = p2_y;
		if (_tmp97_ > _tmp98_) {
			gint temp = 0;
			gint _tmp99_ = 0;
			gint _tmp100_ = 0;
			gint _tmp101_ = 0;
			_tmp99_ = p2_y;
			temp = _tmp99_;
			_tmp100_ = p1_y;
			p2_y = _tmp100_;
			_tmp101_ = temp;
			p1_y = _tmp101_;
		}
		_tmp102_ = cr;
		cairo_new_path (_tmp102_);
		_tmp103_ = cr;
		_tmp104_ = p1_x;
		_tmp105_ = p1_y;
		cairo_move_to (_tmp103_, (gdouble) _tmp104_, (gdouble) _tmp105_);
		_tmp106_ = cr;
		_tmp107_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp108_ = _tmp107_;
		_tmp109_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp110_ = _tmp109_;
		cairo_rel_line_to (_tmp106_, (gdouble) 0, (gdouble) ((_tmp108_ / 2) - (_tmp110_ / 20)));
		_tmp111_ = cr;
		_tmp112_ = p1_x;
		_tmp113_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp114_ = _tmp113_;
		_tmp115_ = p1_y;
		_tmp116_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp117_ = _tmp116_;
		_tmp118_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp119_ = _tmp118_;
		cairo_move_to (_tmp111_, (gdouble) (_tmp112_ - (_tmp114_ / 2)), (gdouble) ((_tmp115_ + (_tmp117_ / 2)) - (_tmp119_ / 20)));
		_tmp120_ = cr;
		_tmp121_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp122_ = _tmp121_;
		cairo_rel_line_to (_tmp120_, (gdouble) _tmp122_, (gdouble) 0);
		_tmp123_ = cr;
		_tmp124_ = p1_x;
		_tmp125_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp126_ = _tmp125_;
		_tmp127_ = p1_y;
		_tmp128_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp129_ = _tmp128_;
		_tmp130_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp131_ = _tmp130_;
		cairo_move_to (_tmp123_, (gdouble) (_tmp124_ - (_tmp126_ / 2)), (gdouble) ((_tmp127_ + (_tmp129_ / 2)) + (_tmp131_ / 20)));
		_tmp132_ = cr;
		_tmp133_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp134_ = _tmp133_;
		cairo_rel_line_to (_tmp132_, (gdouble) _tmp134_, (gdouble) 0);
		_tmp135_ = cr;
		_tmp136_ = p2_x;
		_tmp137_ = p2_y;
		cairo_move_to (_tmp135_, (gdouble) _tmp136_, (gdouble) _tmp137_);
		_tmp138_ = cr;
		_tmp139_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp140_ = _tmp139_;
		_tmp141_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp142_ = _tmp141_;
		cairo_rel_line_to (_tmp138_, (gdouble) 0, (gdouble) (((+_tmp140_) / 20) - (_tmp142_ / 2)));
		_tmp143_ = cr;
		cairo_close_path (_tmp143_);
		_tmp144_ = cr;
		cairo_stroke (_tmp144_);
		_tmp145_ = cr;
		cairo_new_path (_tmp145_);
		_tmp146_ = cr;
		_tmp147_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp148_ = _tmp147_;
		cairo_set_font_size (_tmp146_, _tmp148_ * 0.5);
		_tmp149_ = cr;
		_tmp150_ = p1_x;
		_tmp151_ = elektro_sim_component_get_height ((ElektroSimComponent*) self);
		_tmp152_ = _tmp151_;
		_tmp153_ = p1_y;
		_tmp154_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp155_ = _tmp154_;
		cairo_move_to (_tmp149_, (gdouble) (_tmp150_ + (_tmp152_ / 3)), (gdouble) (_tmp153_ + (_tmp155_ / 3)));
		_tmp156_ = cr;
		_tmp157_ = gtk_widget_get_name ((GtkWidget*) self);
		_tmp158_ = _tmp157_;
		cairo_text_path (_tmp156_, _tmp158_);
		_tmp159_ = cr;
		cairo_close_path (_tmp159_);
		_tmp160_ = cr;
		cairo_fill (_tmp160_);
		_tmp161_ = p1_y;
		y = _tmp161_ + 80;
		_tmp162_ = p1_x;
		x = _tmp162_ + 40;
	}
	_tmp163_ = cr;
	_tmp164_ = x;
	_tmp165_ = y;
	elektro_sim_component_draw_emoticon ((ElektroSimComponent*) self, _tmp163_, _tmp164_, _tmp165_);
}


static void elektro_sim_capacitor_real_clear_counter (ElektroSimComponent* base) {
	ElektroSimCapacitor * self;
	self = (ElektroSimCapacitor*) base;
	elektro_sim_capacitor_counter = 0;
}


static ElektroSimComponent* elektro_sim_capacitor_real_clone (ElektroSimComponent* base) {
	ElektroSimCapacitor * self;
	ElektroSimComponent* result = NULL;
	ElektroSimCapacitor* newc = NULL;
	ElektroSimParameter* _tmp0_ = NULL;
	ElektroSimParameter* _tmp1_ = NULL;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	ElektroSimParameter* _tmp4_ = NULL;
	ElektroSimParameter* _tmp5_ = NULL;
	gdouble _tmp6_ = 0.0;
	gdouble _tmp7_ = 0.0;
	ElektroSimCapacitor* _tmp8_ = NULL;
	ElektroSimCapacitor* _tmp9_ = NULL;
	ElektroSimParameter* _tmp10_ = NULL;
	ElektroSimParameter* _tmp11_ = NULL;
	gboolean _tmp12_ = FALSE;
	gint _tmp13_ = 0;
	ElektroSimCapacitor* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	ElektroSimCapacitor* _tmp20_ = NULL;
	self = (ElektroSimCapacitor*) base;
	_tmp0_ = elektro_sim_component_get_parameter ((ElektroSimComponent*) self, "C");
	_tmp1_ = _tmp0_;
	_tmp2_ = elektro_sim_parameter_get_val (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = elektro_sim_component_get_parameter ((ElektroSimComponent*) self, "rated voltage");
	_tmp5_ = _tmp4_;
	_tmp6_ = elektro_sim_parameter_get_val (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = elektro_sim_capacitor_new (_tmp3_, _tmp7_);
	g_object_ref_sink (_tmp8_);
	_tmp9_ = _tmp8_;
	_g_object_unref0 (_tmp5_);
	_g_object_unref0 (_tmp1_);
	newc = _tmp9_;
	_tmp10_ = elektro_sim_component_get_parameter ((ElektroSimComponent*) self, "C");
	_tmp11_ = _tmp10_;
	_tmp12_ = _tmp11_ == NULL;
	_g_object_unref0 (_tmp11_);
	if (_tmp12_) {
		g_print ("error no parameter to copy from!");
	}
	_tmp13_ = elektro_sim_capacitor_counter;
	elektro_sim_capacitor_counter = _tmp13_ + 1;
	_tmp14_ = newc;
	_tmp15_ = elektro_sim_capacitor_counter;
	_tmp16_ = g_strdup_printf ("%i", _tmp15_);
	_tmp17_ = _tmp16_;
	_tmp18_ = g_strconcat ("c", _tmp17_, NULL);
	_tmp19_ = _tmp18_;
	elektro_sim_component_set_name ((ElektroSimComponent*) _tmp14_, _tmp19_);
	_g_free0 (_tmp19_);
	_g_free0 (_tmp17_);
	_tmp20_ = newc;
	elektro_sim_component_set_componentType ((ElektroSimComponent*) _tmp20_, ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_COMPONENT);
	result = (ElektroSimComponent*) newc;
	return result;
}


static void elektro_sim_capacitor_real_snap (ElektroSimComponent* base, gint range, gint x, gint y) {
	ElektroSimCapacitor * self;
	ElektroSimPoint* point = NULL;
	ElektroSimPoint* point2 = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	ElektroSimPoint* _tmp2_ = NULL;
	ElektroSimPoint* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	ElektroSimPoint* _tmp5_ = NULL;
	GeeArrayList* _tmp6_ = NULL;
	ElektroSimPoint* _tmp7_ = NULL;
	ElektroSimPoint* _tmp8_ = NULL;
	ElektroSimComponentOrientation _tmp9_ = 0;
	ElektroSimComponentOrientation _tmp10_ = 0;
	ElektroSimComponentOrientation _tmp11_ = 0;
	ElektroSimPoint* _tmp63_ = NULL;
	gint _tmp64_ = 0;
	ElektroSimPoint* _tmp65_ = NULL;
	GeeArrayList* _tmp66_ = NULL;
	ElektroSimPoint* _tmp67_ = NULL;
	ElektroSimPoint* _tmp68_ = NULL;
	self = (ElektroSimCapacitor*) base;
	_tmp0_ = x;
	_tmp1_ = y;
	_tmp2_ = elektro_sim_point_new (_tmp0_, _tmp1_);
	_elektro_sim_point_unref0 (point);
	point = _tmp2_;
	_tmp3_ = point;
	_tmp4_ = range;
	_tmp5_ = elektro_sim_point_point_nearby (_tmp3_, _tmp4_);
	_elektro_sim_point_unref0 (point);
	point = _tmp5_;
	_tmp6_ = ((ElektroSimComponent*) self)->connections;
	_tmp7_ = point;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp6_, _tmp7_);
	_tmp8_ = point;
	_tmp9_ = elektro_sim_point_connect_component (_tmp8_, (ElektroSimComponent*) self);
	elektro_sim_component_set_orientation ((ElektroSimComponent*) self, _tmp9_);
	_tmp10_ = elektro_sim_component_get_orientation ((ElektroSimComponent*) self);
	_tmp11_ = _tmp10_;
	if (_tmp11_ == ELEKTRO_SIM_COMPONENT_ORIENTATION_RIGHT) {
		ElektroSimPoint* _tmp12_ = NULL;
		gint _tmp13_ = 0;
		gint _tmp14_ = 0;
		gint _tmp15_ = 0;
		gint _tmp16_ = 0;
		ElektroSimPoint* _tmp17_ = NULL;
		gint _tmp18_ = 0;
		gint _tmp19_ = 0;
		ElektroSimPoint* _tmp20_ = NULL;
		_tmp12_ = point;
		_tmp13_ = elektro_sim_point_get_x (_tmp12_);
		_tmp14_ = _tmp13_;
		_tmp15_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
		_tmp16_ = _tmp15_;
		_tmp17_ = point;
		_tmp18_ = elektro_sim_point_get_y (_tmp17_);
		_tmp19_ = _tmp18_;
		_tmp20_ = elektro_sim_point_new (_tmp14_ + _tmp16_, _tmp19_);
		_elektro_sim_point_unref0 (point2);
		point2 = _tmp20_;
	} else {
		ElektroSimComponentOrientation _tmp21_ = 0;
		ElektroSimComponentOrientation _tmp22_ = 0;
		_tmp21_ = elektro_sim_component_get_orientation ((ElektroSimComponent*) self);
		_tmp22_ = _tmp21_;
		if (_tmp22_ == ELEKTRO_SIM_COMPONENT_ORIENTATION_LEFT) {
			ElektroSimPoint* _tmp23_ = NULL;
			gint _tmp24_ = 0;
			gint _tmp25_ = 0;
			gint _tmp26_ = 0;
			gint _tmp27_ = 0;
			ElektroSimPoint* _tmp28_ = NULL;
			gint _tmp29_ = 0;
			gint _tmp30_ = 0;
			ElektroSimPoint* _tmp31_ = NULL;
			_tmp23_ = point;
			_tmp24_ = elektro_sim_point_get_x (_tmp23_);
			_tmp25_ = _tmp24_;
			_tmp26_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
			_tmp27_ = _tmp26_;
			_tmp28_ = point;
			_tmp29_ = elektro_sim_point_get_y (_tmp28_);
			_tmp30_ = _tmp29_;
			_tmp31_ = elektro_sim_point_new (_tmp25_ - _tmp27_, _tmp30_);
			_elektro_sim_point_unref0 (point2);
			point2 = _tmp31_;
		} else {
			ElektroSimComponentOrientation _tmp32_ = 0;
			ElektroSimComponentOrientation _tmp33_ = 0;
			_tmp32_ = elektro_sim_component_get_orientation ((ElektroSimComponent*) self);
			_tmp33_ = _tmp32_;
			if (_tmp33_ == ELEKTRO_SIM_COMPONENT_ORIENTATION_UP) {
				ElektroSimPoint* _tmp34_ = NULL;
				gint _tmp35_ = 0;
				gint _tmp36_ = 0;
				ElektroSimPoint* _tmp37_ = NULL;
				gint _tmp38_ = 0;
				gint _tmp39_ = 0;
				gint _tmp40_ = 0;
				gint _tmp41_ = 0;
				ElektroSimPoint* _tmp42_ = NULL;
				_tmp34_ = point;
				_tmp35_ = elektro_sim_point_get_x (_tmp34_);
				_tmp36_ = _tmp35_;
				_tmp37_ = point;
				_tmp38_ = elektro_sim_point_get_y (_tmp37_);
				_tmp39_ = _tmp38_;
				_tmp40_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
				_tmp41_ = _tmp40_;
				_tmp42_ = elektro_sim_point_new (_tmp36_, _tmp39_ - _tmp41_);
				_elektro_sim_point_unref0 (point2);
				point2 = _tmp42_;
			} else {
				ElektroSimComponentOrientation _tmp43_ = 0;
				ElektroSimComponentOrientation _tmp44_ = 0;
				_tmp43_ = elektro_sim_component_get_orientation ((ElektroSimComponent*) self);
				_tmp44_ = _tmp43_;
				if (_tmp44_ == ELEKTRO_SIM_COMPONENT_ORIENTATION_DOWN) {
					ElektroSimPoint* _tmp45_ = NULL;
					gint _tmp46_ = 0;
					gint _tmp47_ = 0;
					ElektroSimPoint* _tmp48_ = NULL;
					gint _tmp49_ = 0;
					gint _tmp50_ = 0;
					gint _tmp51_ = 0;
					gint _tmp52_ = 0;
					ElektroSimPoint* _tmp53_ = NULL;
					_tmp45_ = point;
					_tmp46_ = elektro_sim_point_get_x (_tmp45_);
					_tmp47_ = _tmp46_;
					_tmp48_ = point;
					_tmp49_ = elektro_sim_point_get_y (_tmp48_);
					_tmp50_ = _tmp49_;
					_tmp51_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
					_tmp52_ = _tmp51_;
					_tmp53_ = elektro_sim_point_new (_tmp47_, _tmp50_ + _tmp52_);
					_elektro_sim_point_unref0 (point2);
					point2 = _tmp53_;
				} else {
					ElektroSimPoint* _tmp54_ = NULL;
					gint _tmp55_ = 0;
					gint _tmp56_ = 0;
					gint _tmp57_ = 0;
					gint _tmp58_ = 0;
					ElektroSimPoint* _tmp59_ = NULL;
					gint _tmp60_ = 0;
					gint _tmp61_ = 0;
					ElektroSimPoint* _tmp62_ = NULL;
					_tmp54_ = point;
					_tmp55_ = elektro_sim_point_get_x (_tmp54_);
					_tmp56_ = _tmp55_;
					_tmp57_ = elektro_sim_component_get_width ((ElektroSimComponent*) self);
					_tmp58_ = _tmp57_;
					_tmp59_ = point;
					_tmp60_ = elektro_sim_point_get_y (_tmp59_);
					_tmp61_ = _tmp60_;
					_tmp62_ = elektro_sim_point_new (_tmp56_ + _tmp58_, _tmp61_);
					_elektro_sim_point_unref0 (point2);
					point2 = _tmp62_;
				}
			}
		}
	}
	_tmp63_ = point2;
	_tmp64_ = range;
	_tmp65_ = elektro_sim_point_point_nearby (_tmp63_, _tmp64_);
	_elektro_sim_point_unref0 (point2);
	point2 = _tmp65_;
	_tmp66_ = ((ElektroSimComponent*) self)->connections;
	_tmp67_ = point2;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp66_, _tmp67_);
	_tmp68_ = point2;
	elektro_sim_point_connect_component (_tmp68_, (ElektroSimComponent*) self);
	_elektro_sim_point_unref0 (point2);
	_elektro_sim_point_unref0 (point);
}


static gchar* double_to_string (gdouble self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp1_ = (g_free (_tmp1_), NULL);
	result = _tmp4_;
	return result;
}


static gchar* elektro_sim_capacitor_real_get_netlist_line (ElektroSimComponent* base) {
	ElektroSimCapacitor * self;
	gchar* result = NULL;
	gchar* line = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GeeArrayList* _tmp4_ = NULL;
	gpointer _tmp5_ = NULL;
	ElektroSimPoint* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	GeeArrayList* _tmp15_ = NULL;
	gpointer _tmp16_ = NULL;
	ElektroSimPoint* _tmp17_ = NULL;
	gint _tmp18_ = 0;
	gint _tmp19_ = 0;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	ElektroSimParameter* _tmp26_ = NULL;
	ElektroSimParameter* _tmp27_ = NULL;
	gdouble _tmp28_ = 0.0;
	gdouble _tmp29_ = 0.0;
	gchar* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	gchar* _tmp33_ = NULL;
	gchar* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	ElektroSimParameter* _tmp36_ = NULL;
	ElektroSimParameter* _tmp37_ = NULL;
	gdouble _tmp38_ = 0.0;
	gdouble _tmp39_ = 0.0;
	gchar* _tmp40_ = NULL;
	gchar* _tmp41_ = NULL;
	gchar* _tmp42_ = NULL;
	gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	self = (ElektroSimCapacitor*) base;
	_tmp0_ = gtk_widget_get_name ((GtkWidget*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strconcat (_tmp1_, " ", NULL);
	_tmp3_ = _tmp2_;
	_tmp4_ = ((ElektroSimComponent*) self)->connections;
	_tmp5_ = gee_abstract_list_get ((GeeAbstractList*) _tmp4_, 0);
	_tmp6_ = (ElektroSimPoint*) _tmp5_;
	_tmp7_ = elektro_sim_point_get_net (_tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = g_strdup_printf ("%i", _tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = g_strconcat (_tmp3_, _tmp10_, NULL);
	_tmp12_ = _tmp11_;
	_tmp13_ = g_strconcat (_tmp12_, " ", NULL);
	_tmp14_ = _tmp13_;
	_tmp15_ = ((ElektroSimComponent*) self)->connections;
	_tmp16_ = gee_abstract_list_get ((GeeAbstractList*) _tmp15_, 1);
	_tmp17_ = (ElektroSimPoint*) _tmp16_;
	_tmp18_ = elektro_sim_point_get_net (_tmp17_);
	_tmp19_ = _tmp18_;
	_tmp20_ = g_strdup_printf ("%i", _tmp19_);
	_tmp21_ = _tmp20_;
	_tmp22_ = g_strconcat (_tmp14_, _tmp21_, NULL);
	_tmp23_ = _tmp22_;
	_tmp24_ = g_strconcat (_tmp23_, " ", NULL);
	_tmp25_ = _tmp24_;
	_tmp26_ = elektro_sim_component_get_parameter ((ElektroSimComponent*) self, "C");
	_tmp27_ = _tmp26_;
	_tmp28_ = elektro_sim_parameter_get_val (_tmp27_);
	_tmp29_ = _tmp28_;
	_tmp30_ = double_to_string (_tmp29_);
	_tmp31_ = _tmp30_;
	_tmp32_ = g_strconcat (_tmp25_, _tmp31_, NULL);
	_tmp33_ = _tmp32_;
	_tmp34_ = g_strconcat (_tmp33_, " rated_voltage=", NULL);
	_tmp35_ = _tmp34_;
	_tmp36_ = elektro_sim_component_get_parameter ((ElektroSimComponent*) self, "rated voltage");
	_tmp37_ = _tmp36_;
	_tmp38_ = elektro_sim_parameter_get_val (_tmp37_);
	_tmp39_ = _tmp38_;
	_tmp40_ = double_to_string (_tmp39_);
	_tmp41_ = _tmp40_;
	_tmp42_ = g_strconcat (_tmp35_, _tmp41_, NULL);
	_tmp43_ = _tmp42_;
	_tmp44_ = g_strconcat (_tmp43_, "\n", NULL);
	_g_free0 (line);
	line = _tmp44_;
	_g_free0 (_tmp43_);
	_g_free0 (_tmp41_);
	_g_object_unref0 (_tmp37_);
	_g_free0 (_tmp35_);
	_g_free0 (_tmp33_);
	_g_free0 (_tmp31_);
	_g_object_unref0 (_tmp27_);
	_g_free0 (_tmp25_);
	_g_free0 (_tmp23_);
	_g_free0 (_tmp21_);
	_elektro_sim_point_unref0 (_tmp17_);
	_g_free0 (_tmp14_);
	_g_free0 (_tmp12_);
	_g_free0 (_tmp10_);
	_elektro_sim_point_unref0 (_tmp6_);
	_g_free0 (_tmp3_);
	result = line;
	return result;
}


static void elektro_sim_capacitor_class_init (ElektroSimCapacitorClass * klass) {
	elektro_sim_capacitor_parent_class = g_type_class_peek_parent (klass);
	ELEKTRO_SIM_COMPONENT_CLASS (klass)->draw_image = elektro_sim_capacitor_real_draw_image;
	ELEKTRO_SIM_COMPONENT_CLASS (klass)->clear_counter = elektro_sim_capacitor_real_clear_counter;
	ELEKTRO_SIM_COMPONENT_CLASS (klass)->clone = elektro_sim_capacitor_real_clone;
	ELEKTRO_SIM_COMPONENT_CLASS (klass)->snap = elektro_sim_capacitor_real_snap;
	ELEKTRO_SIM_COMPONENT_CLASS (klass)->get_netlist_line = elektro_sim_capacitor_real_get_netlist_line;
	G_OBJECT_CLASS (klass)->finalize = elektro_sim_capacitor_finalize;
}


static void elektro_sim_capacitor_instance_init (ElektroSimCapacitor * self) {
}


static void elektro_sim_capacitor_finalize (GObject* obj) {
	ElektroSimCapacitor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEKTRO_SIM_TYPE_CAPACITOR, ElektroSimCapacitor);
	G_OBJECT_CLASS (elektro_sim_capacitor_parent_class)->finalize (obj);
}


GType elektro_sim_capacitor_get_type (void) {
	static volatile gsize elektro_sim_capacitor_type_id__volatile = 0;
	if (g_once_init_enter (&elektro_sim_capacitor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ElektroSimCapacitorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) elektro_sim_capacitor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ElektroSimCapacitor), 0, (GInstanceInitFunc) elektro_sim_capacitor_instance_init, NULL };
		GType elektro_sim_capacitor_type_id;
		elektro_sim_capacitor_type_id = g_type_register_static (ELEKTRO_SIM_TYPE_COMPONENT, "ElektroSimCapacitor", &g_define_type_info, 0);
		g_once_init_leave (&elektro_sim_capacitor_type_id__volatile, elektro_sim_capacitor_type_id);
	}
	return elektro_sim_capacitor_type_id__volatile;
}



