/* component.c generated by valac 0.22.1, the Vala compiler
 * generated from component.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * component.vala
 * Copyright (C) 2014 Steven Vanden Branden <StevenVandenBrandenStift@gmail.com>
 *
 * ElektroSim is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ElektroSim is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <cairo.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <gobject/gvaluecollector.h>


#define TYPE_TARGET (target_get_type ())

#define TYPE_POINT (point_get_type ())
#define POINT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POINT, Point))
#define POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POINT, PointClass))
#define IS_POINT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POINT))
#define IS_POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POINT))
#define POINT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POINT, PointClass))

typedef struct _Point Point;
typedef struct _PointClass PointClass;
typedef struct _PointPrivate PointPrivate;

#define TYPE_COMPONENT (component_get_type ())
#define COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMPONENT, Component))
#define COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMPONENT, ComponentClass))
#define IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMPONENT))
#define IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMPONENT))
#define COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMPONENT, ComponentClass))

typedef struct _Component Component;
typedef struct _ComponentClass ComponentClass;
typedef struct _ComponentPrivate ComponentPrivate;
#define _point_unref0(var) ((var == NULL) ? NULL : (var = (point_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ParamSpecPoint ParamSpecPoint;

#define TYPE_ACTIVITY (activity_get_type ())

#define TYPE_ZONE (zone_get_type ())

#define TYPE_ORIENTATION (orientation_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_list_free__point_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__point_unref0_ (var), NULL)))

typedef enum  {
	TARGET_INT32
} Target;

struct _Point {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PointPrivate * priv;
};

struct _PointClass {
	GTypeClass parent_class;
	void (*finalize) (Point *self);
};

struct _PointPrivate {
	gint _x;
	gint _y;
	gint _net;
};

struct _Component {
	GtkListBoxRow parent_instance;
	ComponentPrivate * priv;
	GList* connections;
};

struct _ComponentClass {
	GtkListBoxRowClass parent_class;
	Component* (*clone) (Component* self, Component* component, gint x, gint y);
	gint (*snap) (Component* self, GList* list, gint range, gint netAmount);
	void (*draw_symbol) (Component* self, cairo_t* context);
	gchar* (*getNetlistLine) (Component* self);
	void (*insertSimulationData) (Component* self, const gchar* data);
};

struct _ParamSpecPoint {
	GParamSpec parent_instance;
};

typedef enum  {
	ACTIVITY_NONE,
	ACTIVITY_INACTIVE,
	ACTIVITY_SUBACTIVE,
	ACTIVITY_ACTIVE,
	ACTIVITY_OVERACTIVE
} Activity;

typedef enum  {
	ZONE_NONE,
	ZONE_SUBOPTIMAL,
	ZONE_OPTIMAL,
	ZONE_OUTOFRANGE,
	ZONE_DESTRUCTIVE
} Zone;

typedef enum  {
	ORIENTATION_UNKNOWN,
	ORIENTATION_LEFT,
	ORIENTATION_RIGHT,
	ORIENTATION_UP,
	ORIENTATION_DOWN
} Orientation;

struct _ComponentPrivate {
	gint _height;
	gint _width;
	Activity _activity;
	Zone _zone;
	Orientation _orientation;
	GtkButton* label;
	gchar* _name;
};


static gpointer point_parent_class = NULL;
static gpointer component_parent_class = NULL;

GType target_get_type (void) G_GNUC_CONST;
#define BYTE_BITS 8
#define WORD_BITS 16
#define DWORD_BITS 32
gpointer point_ref (gpointer instance);
void point_unref (gpointer instance);
GParamSpec* param_spec_point (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_point (GValue* value, gpointer v_object);
void value_take_point (GValue* value, gpointer v_object);
gpointer value_get_point (const GValue* value);
GType point_get_type (void) G_GNUC_CONST;
#define POINT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_POINT, PointPrivate))
enum  {
	POINT_DUMMY_PROPERTY
};
Point* point_new (gint x, gint y);
Point* point_construct (GType object_type, gint x, gint y);
void point_set_x (Point* self, gint value);
void point_set_y (Point* self, gint value);
Point* point_new_with_net (gint x, gint y, gint net);
Point* point_construct_with_net (GType object_type, gint x, gint y, gint net);
void point_set_net (Point* self, gint value);
GType component_get_type (void) G_GNUC_CONST;
gboolean point_pointNearby (Point* self, gint range, GList* items);
gint point_get_x (Point* self);
gint point_get_y (Point* self);
gint point_get_net (Point* self);
gint point_checkNetName (Point* self, gint netCount);
static void point_finalize (Point* obj);
GType activity_get_type (void) G_GNUC_CONST;
GType zone_get_type (void) G_GNUC_CONST;
GType orientation_get_type (void) G_GNUC_CONST;
#define COMPONENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_COMPONENT, ComponentPrivate))
enum  {
	COMPONENT_DUMMY_PROPERTY,
	COMPONENT_HEIGHT,
	COMPONENT_WIDTH,
	COMPONENT_ACTIVITY,
	COMPONENT_ZONE,
	COMPONENT_ORIENTATION,
	COMPONENT_NAME
};
static void _point_unref0_ (gpointer var);
static void _g_list_free__point_unref0_ (GList* self);
Component* component_construct (GType object_type, const gchar* name);
void component_set_name (Component* self, const gchar* value);
static void component_on_drag_data_get (Component* self, GtkWidget* widget, GdkDragContext* context, GtkSelectionData* selection_data, guint target_type, guint time);
static void _component_on_drag_data_get_gtk_widget_drag_data_get (GtkWidget* _sender, GdkDragContext* context, GtkSelectionData* selection_data, guint info, guint time_, gpointer self);
Component* component_clone (Component* self, Component* component, gint x, gint y);
static Component* component_real_clone (Component* self, Component* component, gint x, gint y);
gint component_snap (Component* self, GList* list, gint range, gint netAmount);
static gint component_real_snap (Component* self, GList* list, gint range, gint netAmount);
void component_draw_symbol (Component* self, cairo_t* context);
static void component_real_draw_symbol (Component* self, cairo_t* context);
gchar* component_getNetlistLine (Component* self);
static gchar* component_real_getNetlistLine (Component* self);
void component_insertSimulationData (Component* self, const gchar* data);
static void component_real_insertSimulationData (Component* self, const gchar* data);
static void component_convert_long_to_bytes (Component* self, glong number, guchar** buffer, int* buffer_length1);
gint component_get_height (Component* self);
void component_set_height (Component* self, gint value);
gint component_get_width (Component* self);
void component_set_width (Component* self, gint value);
Activity component_get_activity (Component* self);
void component_set_activity (Component* self, Activity value);
Zone component_get_zone (Component* self);
void component_set_zone (Component* self, Zone value);
Orientation component_get_orientation (Component* self);
void component_set_orientation (Component* self, Orientation value);
const gchar* component_get_name (Component* self);
static void component_finalize (GObject* obj);
static void _vala_component_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_component_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);

const GtkTargetEntry target_list[1] = {{"INTEGER", (guint) 0, (guint) TARGET_INT32}};

GType target_get_type (void) {
	static volatile gsize target_type_id__volatile = 0;
	if (g_once_init_enter (&target_type_id__volatile)) {
		static const GEnumValue values[] = {{TARGET_INT32, "TARGET_INT32", "int32"}, {0, NULL, NULL}};
		GType target_type_id;
		target_type_id = g_enum_register_static ("Target", values);
		g_once_init_leave (&target_type_id__volatile, target_type_id);
	}
	return target_type_id__volatile;
}


Point* point_construct (GType object_type, gint x, gint y) {
	Point* self = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	self = (Point*) g_type_create_instance (object_type);
	_tmp0_ = x;
	point_set_x (self, _tmp0_);
	_tmp1_ = y;
	point_set_y (self, _tmp1_);
	return self;
}


Point* point_new (gint x, gint y) {
	return point_construct (TYPE_POINT, x, y);
}


Point* point_construct_with_net (GType object_type, gint x, gint y, gint net) {
	Point* self = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	self = (Point*) g_type_create_instance (object_type);
	_tmp0_ = x;
	point_set_x (self, _tmp0_);
	_tmp1_ = y;
	point_set_y (self, _tmp1_);
	_tmp2_ = net;
	point_set_net (self, _tmp2_);
	return self;
}


Point* point_new_with_net (gint x, gint y, gint net) {
	return point_construct_with_net (TYPE_POINT, x, y, net);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gpointer _point_ref0 (gpointer self) {
	return self ? point_ref (self) : NULL;
}


gboolean point_pointNearby (Point* self, gint range, GList* items) {
	gboolean result = FALSE;
	GList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = items;
	{
		GList* component_collection = NULL;
		GList* component_it = NULL;
		component_collection = _tmp0_;
		for (component_it = component_collection; component_it != NULL; component_it = component_it->next) {
			Component* _tmp1_ = NULL;
			Component* component = NULL;
			_tmp1_ = _g_object_ref0 ((Component*) component_it->data);
			component = _tmp1_;
			{
				Component* _tmp2_ = NULL;
				GList* _tmp3_ = NULL;
				_tmp2_ = component;
				_tmp3_ = _tmp2_->connections;
				{
					GList* snapPoint_collection = NULL;
					GList* snapPoint_it = NULL;
					snapPoint_collection = _tmp3_;
					for (snapPoint_it = snapPoint_collection; snapPoint_it != NULL; snapPoint_it = snapPoint_it->next) {
						Point* _tmp4_ = NULL;
						Point* snapPoint = NULL;
						_tmp4_ = _point_ref0 ((Point*) snapPoint_it->data);
						snapPoint = _tmp4_;
						{
							gboolean _tmp5_ = FALSE;
							gboolean _tmp6_ = FALSE;
							gboolean _tmp7_ = FALSE;
							gint _tmp8_ = 0;
							Point* _tmp9_ = NULL;
							gint _tmp10_ = 0;
							gint _tmp11_ = 0;
							gboolean _tmp16_ = FALSE;
							gboolean _tmp21_ = FALSE;
							gboolean _tmp26_ = FALSE;
							_tmp8_ = self->priv->_x;
							_tmp9_ = snapPoint;
							_tmp10_ = _tmp9_->priv->_x;
							_tmp11_ = range;
							if (_tmp8_ > (_tmp10_ - _tmp11_)) {
								gint _tmp12_ = 0;
								Point* _tmp13_ = NULL;
								gint _tmp14_ = 0;
								gint _tmp15_ = 0;
								_tmp12_ = self->priv->_x;
								_tmp13_ = snapPoint;
								_tmp14_ = _tmp13_->priv->_x;
								_tmp15_ = range;
								_tmp7_ = _tmp12_ < (_tmp14_ + _tmp15_);
							} else {
								_tmp7_ = FALSE;
							}
							_tmp16_ = _tmp7_;
							if (_tmp16_) {
								gint _tmp17_ = 0;
								Point* _tmp18_ = NULL;
								gint _tmp19_ = 0;
								gint _tmp20_ = 0;
								_tmp17_ = self->priv->_y;
								_tmp18_ = snapPoint;
								_tmp19_ = _tmp18_->priv->_y;
								_tmp20_ = range;
								_tmp6_ = _tmp17_ > (_tmp19_ - _tmp20_);
							} else {
								_tmp6_ = FALSE;
							}
							_tmp21_ = _tmp6_;
							if (_tmp21_) {
								gint _tmp22_ = 0;
								Point* _tmp23_ = NULL;
								gint _tmp24_ = 0;
								gint _tmp25_ = 0;
								_tmp22_ = self->priv->_y;
								_tmp23_ = snapPoint;
								_tmp24_ = _tmp23_->priv->_y;
								_tmp25_ = range;
								_tmp5_ = _tmp22_ < (_tmp24_ + _tmp25_);
							} else {
								_tmp5_ = FALSE;
							}
							_tmp26_ = _tmp5_;
							if (_tmp26_) {
								Point* _tmp27_ = NULL;
								gint _tmp28_ = 0;
								Point* _tmp29_ = NULL;
								gint _tmp30_ = 0;
								gint _tmp31_ = 0;
								_tmp27_ = snapPoint;
								_tmp28_ = _tmp27_->priv->_x;
								point_set_x (self, _tmp28_);
								_tmp29_ = snapPoint;
								_tmp30_ = _tmp29_->priv->_y;
								point_set_y (self, _tmp30_);
								_tmp31_ = self->priv->_net;
								if (_tmp31_ == 0) {
									Point* _tmp32_ = NULL;
									_tmp32_ = snapPoint;
									point_set_net (_tmp32_, 0);
								} else {
									Point* _tmp33_ = NULL;
									gint _tmp34_ = 0;
									_tmp33_ = snapPoint;
									_tmp34_ = _tmp33_->priv->_net;
									point_set_net (self, _tmp34_);
								}
								result = TRUE;
								_point_unref0 (snapPoint);
								_g_object_unref0 (component);
								return result;
							}
							_point_unref0 (snapPoint);
						}
					}
				}
				_g_object_unref0 (component);
			}
		}
	}
	result = FALSE;
	return result;
}


gint point_checkNetName (Point* self, gint netCount) {
	gint result = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp7_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_x;
	_tmp1_ = self->priv->_y;
	_tmp2_ = self->priv->_net;
	_tmp3_ = netCount;
	g_print ("net from point %i,%i : %i %i\n", _tmp0_, _tmp1_, _tmp2_, _tmp3_);
	_tmp4_ = self->priv->_net;
	if (_tmp4_ == 1000) {
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		_tmp5_ = netCount;
		point_set_net (self, _tmp5_);
		_tmp6_ = netCount;
		result = _tmp6_ + 1;
		return result;
	}
	_tmp7_ = netCount;
	result = _tmp7_;
	return result;
}


gint point_get_x (Point* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_x;
	result = _tmp0_;
	return result;
}


void point_set_x (Point* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_x = _tmp0_;
}


gint point_get_y (Point* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_y;
	result = _tmp0_;
	return result;
}


void point_set_y (Point* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_y = _tmp0_;
}


gint point_get_net (Point* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_net;
	result = _tmp0_;
	return result;
}


void point_set_net (Point* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_net = _tmp0_;
}


static void value_point_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_point_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		point_unref (value->data[0].v_pointer);
	}
}


static void value_point_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = point_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_point_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_point_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		Point* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = point_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_point_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Point** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = point_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_point (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecPoint* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_POINT), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_point (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_POINT), NULL);
	return value->data[0].v_pointer;
}


void value_set_point (GValue* value, gpointer v_object) {
	Point* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_POINT));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_POINT));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		point_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		point_unref (old);
	}
}


void value_take_point (GValue* value, gpointer v_object) {
	Point* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_POINT));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_POINT));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		point_unref (old);
	}
}


static void point_class_init (PointClass * klass) {
	point_parent_class = g_type_class_peek_parent (klass);
	POINT_CLASS (klass)->finalize = point_finalize;
	g_type_class_add_private (klass, sizeof (PointPrivate));
}


static void point_instance_init (Point * self) {
	self->priv = POINT_GET_PRIVATE (self);
	self->priv->_x = 0;
	self->priv->_y = 0;
	self->priv->_net = 1000;
	self->ref_count = 1;
}


static void point_finalize (Point* obj) {
	Point * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_POINT, Point);
}


GType point_get_type (void) {
	static volatile gsize point_type_id__volatile = 0;
	if (g_once_init_enter (&point_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_point_init, value_point_free_value, value_point_copy_value, value_point_peek_pointer, "p", value_point_collect_value, "p", value_point_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PointClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) point_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Point), 0, (GInstanceInitFunc) point_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType point_type_id;
		point_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Point", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&point_type_id__volatile, point_type_id);
	}
	return point_type_id__volatile;
}


gpointer point_ref (gpointer instance) {
	Point* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void point_unref (gpointer instance) {
	Point* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		POINT_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


GType activity_get_type (void) {
	static volatile gsize activity_type_id__volatile = 0;
	if (g_once_init_enter (&activity_type_id__volatile)) {
		static const GEnumValue values[] = {{ACTIVITY_NONE, "ACTIVITY_NONE", "none"}, {ACTIVITY_INACTIVE, "ACTIVITY_INACTIVE", "inactive"}, {ACTIVITY_SUBACTIVE, "ACTIVITY_SUBACTIVE", "subactive"}, {ACTIVITY_ACTIVE, "ACTIVITY_ACTIVE", "active"}, {ACTIVITY_OVERACTIVE, "ACTIVITY_OVERACTIVE", "overactive"}, {0, NULL, NULL}};
		GType activity_type_id;
		activity_type_id = g_enum_register_static ("Activity", values);
		g_once_init_leave (&activity_type_id__volatile, activity_type_id);
	}
	return activity_type_id__volatile;
}


GType zone_get_type (void) {
	static volatile gsize zone_type_id__volatile = 0;
	if (g_once_init_enter (&zone_type_id__volatile)) {
		static const GEnumValue values[] = {{ZONE_NONE, "ZONE_NONE", "none"}, {ZONE_SUBOPTIMAL, "ZONE_SUBOPTIMAL", "suboptimal"}, {ZONE_OPTIMAL, "ZONE_OPTIMAL", "optimal"}, {ZONE_OUTOFRANGE, "ZONE_OUTOFRANGE", "outofrange"}, {ZONE_DESTRUCTIVE, "ZONE_DESTRUCTIVE", "destructive"}, {0, NULL, NULL}};
		GType zone_type_id;
		zone_type_id = g_enum_register_static ("Zone", values);
		g_once_init_leave (&zone_type_id__volatile, zone_type_id);
	}
	return zone_type_id__volatile;
}


GType orientation_get_type (void) {
	static volatile gsize orientation_type_id__volatile = 0;
	if (g_once_init_enter (&orientation_type_id__volatile)) {
		static const GEnumValue values[] = {{ORIENTATION_UNKNOWN, "ORIENTATION_UNKNOWN", "unknown"}, {ORIENTATION_LEFT, "ORIENTATION_LEFT", "left"}, {ORIENTATION_RIGHT, "ORIENTATION_RIGHT", "right"}, {ORIENTATION_UP, "ORIENTATION_UP", "up"}, {ORIENTATION_DOWN, "ORIENTATION_DOWN", "down"}, {0, NULL, NULL}};
		GType orientation_type_id;
		orientation_type_id = g_enum_register_static ("Orientation", values);
		g_once_init_leave (&orientation_type_id__volatile, orientation_type_id);
	}
	return orientation_type_id__volatile;
}


static void _point_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (point_unref (var), NULL));
}


static void _g_list_free__point_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _point_unref0_, NULL);
	g_list_free (self);
}


static void _component_on_drag_data_get_gtk_widget_drag_data_get (GtkWidget* _sender, GdkDragContext* context, GtkSelectionData* selection_data, guint info, guint time_, gpointer self) {
	component_on_drag_data_get (self, _sender, context, selection_data, info, time_);
}


Component* component_construct (GType object_type, const gchar* name) {
	Component * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkButton* _tmp2_ = NULL;
	GtkButton* _tmp3_ = NULL;
	GtkButton* _tmp4_ = NULL;
	GtkButton* _tmp5_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	self = (Component*) g_object_new (object_type, NULL);
	_tmp0_ = name;
	component_set_name (self, _tmp0_);
	_tmp1_ = name;
	_tmp2_ = (GtkButton*) gtk_button_new_with_label (_tmp1_);
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->label);
	self->priv->label = _tmp2_;
	_tmp3_ = self->priv->label;
	gtk_container_add ((GtkContainer*) (G_TYPE_CHECK_INSTANCE_TYPE (self, GTK_TYPE_LIST_BOX_ROW) ? ((GtkListBoxRow*) self) : NULL), (GtkWidget*) _tmp3_);
	_tmp4_ = self->priv->label;
	gtk_drag_source_set ((GtkWidget*) _tmp4_, GDK_BUTTON1_MASK, target_list, G_N_ELEMENTS (target_list), GDK_ACTION_COPY);
	_tmp5_ = self->priv->label;
	g_signal_connect_object ((GtkWidget*) _tmp5_, "drag-data-get", (GCallback) _component_on_drag_data_get_gtk_widget_drag_data_get, self, 0);
	__g_list_free__point_unref0_0 (self->connections);
	self->connections = NULL;
	return self;
}


static Component* component_real_clone (Component* self, Component* component, gint x, gint y) {
	g_critical ("Type `%s' does not implement abstract method `component_clone'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return NULL;
}


Component* component_clone (Component* self, Component* component, gint x, gint y) {
	g_return_val_if_fail (self != NULL, NULL);
	return COMPONENT_GET_CLASS (self)->clone (self, component, x, y);
}


static gint component_real_snap (Component* self, GList* list, gint range, gint netAmount) {
	g_critical ("Type `%s' does not implement abstract method `component_snap'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return 0;
}


gint component_snap (Component* self, GList* list, gint range, gint netAmount) {
	g_return_val_if_fail (self != NULL, 0);
	return COMPONENT_GET_CLASS (self)->snap (self, list, range, netAmount);
}


static void component_real_draw_symbol (Component* self, cairo_t* context) {
	g_critical ("Type `%s' does not implement abstract method `component_draw_symbol'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void component_draw_symbol (Component* self, cairo_t* context) {
	g_return_if_fail (self != NULL);
	COMPONENT_GET_CLASS (self)->draw_symbol (self, context);
}


static gchar* component_real_getNetlistLine (Component* self) {
	g_critical ("Type `%s' does not implement abstract method `component_getNetlistLine'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return NULL;
}


gchar* component_getNetlistLine (Component* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return COMPONENT_GET_CLASS (self)->getNetlistLine (self);
}


static void component_real_insertSimulationData (Component* self, const gchar* data) {
	g_critical ("Type `%s' does not implement abstract method `component_insertSimulationData'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void component_insertSimulationData (Component* self, const gchar* data) {
	g_return_if_fail (self != NULL);
	COMPONENT_GET_CLASS (self)->insertSimulationData (self, data);
}


static void component_on_drag_data_get (Component* self, GtkWidget* widget, GdkDragContext* context, GtkSelectionData* selection_data, guint target_type, guint time) {
	guint _tmp0_ = 0U;
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (selection_data != NULL);
	_tmp0_ = target_type;
	switch (_tmp0_) {
		case TARGET_INT32:
		{
			guchar* buf = NULL;
			gint buf_length1 = 0;
			gint _buf_size_ = 0;
			gint _tmp1_ = 0;
			guchar* _tmp2_ = NULL;
			gint _tmp3_ = 0;
			GtkSelectionData* _tmp4_ = NULL;
			GtkSelectionData* _tmp5_ = NULL;
			GdkAtom _tmp6_ = 0U;
			_tmp1_ = gtk_list_box_row_get_index ((GtkListBoxRow*) self);
			component_convert_long_to_bytes (self, (glong) _tmp1_, &_tmp2_, &_tmp3_);
			buf = (g_free (buf), NULL);
			buf = _tmp2_;
			buf_length1 = _tmp3_;
			_buf_size_ = buf_length1;
			_tmp4_ = selection_data;
			_tmp5_ = selection_data;
			_tmp6_ = gtk_selection_data_get_target (_tmp5_);
			gtk_selection_data_set (_tmp4_, _tmp6_, BYTE_BITS, buf, buf_length1);
			buf = (g_free (buf), NULL);
			break;
		}
		default:
		{
			g_print ("failed to send");
			g_assert_not_reached ();
		}
	}
}


static void component_convert_long_to_bytes (Component* self, glong number, guchar** buffer, int* buffer_length1) {
	guchar* _vala_buffer = NULL;
	int _vala_buffer_length1 = 0;
	guchar* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_new0 (guchar, sizeof (glong));
	_vala_buffer = (g_free (_vala_buffer), NULL);
	_vala_buffer = _tmp0_;
	_vala_buffer_length1 = sizeof (glong);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gboolean _tmp2_ = FALSE;
				gint _tmp4_ = 0;
				guchar* _tmp5_ = NULL;
				gint _tmp5__length1 = 0;
				gint _tmp6_ = 0;
				glong _tmp7_ = 0L;
				guchar _tmp8_ = '\0';
				glong _tmp9_ = 0L;
				_tmp2_ = _tmp1_;
				if (!_tmp2_) {
					gint _tmp3_ = 0;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp4_ = i;
				if (!(((gulong) _tmp4_) < sizeof (glong))) {
					break;
				}
				_tmp5_ = _vala_buffer;
				_tmp5__length1 = _vala_buffer_length1;
				_tmp6_ = i;
				_tmp7_ = number;
				_tmp5_[_tmp6_] = (guchar) (_tmp7_ & 0xFF);
				_tmp8_ = _tmp5_[_tmp6_];
				_tmp9_ = number;
				number = _tmp9_ >> 8;
			}
		}
	}
	if (buffer) {
		*buffer = _vala_buffer;
	} else {
		_vala_buffer = (g_free (_vala_buffer), NULL);
	}
	if (buffer_length1) {
		*buffer_length1 = _vala_buffer_length1;
	}
}


gint component_get_height (Component* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_height;
	result = _tmp0_;
	return result;
}


void component_set_height (Component* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_height = _tmp0_;
	g_object_notify ((GObject *) self, "height");
}


gint component_get_width (Component* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_width;
	result = _tmp0_;
	return result;
}


void component_set_width (Component* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_width = _tmp0_;
	g_object_notify ((GObject *) self, "width");
}


Activity component_get_activity (Component* self) {
	Activity result;
	Activity _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_activity;
	result = _tmp0_;
	return result;
}


void component_set_activity (Component* self, Activity value) {
	Activity _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_activity = _tmp0_;
	g_object_notify ((GObject *) self, "activity");
}


Zone component_get_zone (Component* self) {
	Zone result;
	Zone _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_zone;
	result = _tmp0_;
	return result;
}


void component_set_zone (Component* self, Zone value) {
	Zone _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_zone = _tmp0_;
	g_object_notify ((GObject *) self, "zone");
}


Orientation component_get_orientation (Component* self) {
	Orientation result;
	Orientation _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_orientation;
	result = _tmp0_;
	return result;
}


void component_set_orientation (Component* self, Orientation value) {
	Orientation _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_orientation = _tmp0_;
	g_object_notify ((GObject *) self, "orientation");
}


const gchar* component_get_name (Component* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


void component_set_name (Component* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
	g_object_notify ((GObject *) self, "name");
}


static void component_class_init (ComponentClass * klass) {
	component_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ComponentPrivate));
	COMPONENT_CLASS (klass)->clone = component_real_clone;
	COMPONENT_CLASS (klass)->snap = component_real_snap;
	COMPONENT_CLASS (klass)->draw_symbol = component_real_draw_symbol;
	COMPONENT_CLASS (klass)->getNetlistLine = component_real_getNetlistLine;
	COMPONENT_CLASS (klass)->insertSimulationData = component_real_insertSimulationData;
	G_OBJECT_CLASS (klass)->get_property = _vala_component_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_component_set_property;
	G_OBJECT_CLASS (klass)->finalize = component_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), COMPONENT_HEIGHT, g_param_spec_int ("height", "height", "height", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), COMPONENT_WIDTH, g_param_spec_int ("width", "width", "width", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), COMPONENT_ACTIVITY, g_param_spec_enum ("activity", "activity", "activity", TYPE_ACTIVITY, ACTIVITY_NONE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), COMPONENT_ZONE, g_param_spec_enum ("zone", "zone", "zone", TYPE_ZONE, ZONE_NONE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), COMPONENT_ORIENTATION, g_param_spec_enum ("orientation", "orientation", "orientation", TYPE_ORIENTATION, ORIENTATION_UNKNOWN, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), COMPONENT_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void component_instance_init (Component * self) {
	self->priv = COMPONENT_GET_PRIVATE (self);
	self->priv->_height = 0;
	self->priv->_width = 0;
	self->priv->_activity = ACTIVITY_NONE;
	self->priv->_zone = ZONE_NONE;
	self->priv->_orientation = ORIENTATION_UNKNOWN;
}


static void component_finalize (GObject* obj) {
	Component * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_COMPONENT, Component);
	_g_object_unref0 (self->priv->label);
	_g_free0 (self->priv->_name);
	__g_list_free__point_unref0_0 (self->connections);
	G_OBJECT_CLASS (component_parent_class)->finalize (obj);
}


GType component_get_type (void) {
	static volatile gsize component_type_id__volatile = 0;
	if (g_once_init_enter (&component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Component), 0, (GInstanceInitFunc) component_instance_init, NULL };
		GType component_type_id;
		component_type_id = g_type_register_static (GTK_TYPE_LIST_BOX_ROW, "Component", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&component_type_id__volatile, component_type_id);
	}
	return component_type_id__volatile;
}


static void _vala_component_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	Component * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_COMPONENT, Component);
	switch (property_id) {
		case COMPONENT_HEIGHT:
		g_value_set_int (value, component_get_height (self));
		break;
		case COMPONENT_WIDTH:
		g_value_set_int (value, component_get_width (self));
		break;
		case COMPONENT_ACTIVITY:
		g_value_set_enum (value, component_get_activity (self));
		break;
		case COMPONENT_ZONE:
		g_value_set_enum (value, component_get_zone (self));
		break;
		case COMPONENT_ORIENTATION:
		g_value_set_enum (value, component_get_orientation (self));
		break;
		case COMPONENT_NAME:
		g_value_set_string (value, component_get_name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_component_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	Component * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_COMPONENT, Component);
	switch (property_id) {
		case COMPONENT_HEIGHT:
		component_set_height (self, g_value_get_int (value));
		break;
		case COMPONENT_WIDTH:
		component_set_width (self, g_value_get_int (value));
		break;
		case COMPONENT_ACTIVITY:
		component_set_activity (self, g_value_get_enum (value));
		break;
		case COMPONENT_ZONE:
		component_set_zone (self, g_value_get_enum (value));
		break;
		case COMPONENT_ORIENTATION:
		component_set_orientation (self, g_value_get_enum (value));
		break;
		case COMPONENT_NAME:
		component_set_name (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



