/* component.c generated by valac 0.24.0, the Vala compiler
 * generated from component.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * component.vala
 * Copyright (C) 2014 Steven Vanden Branden <StevenVandenBrandenStift@gmail.com>
 *
 * ElektroSim is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ElektroSim is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <cairo.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <float.h>
#include <math.h>
#include <librsvg/rsvg.h>
#include <stdio.h>


#define ELEKTRO_SIM_TYPE_COMPONENT (elektro_sim_component_get_type ())
#define ELEKTRO_SIM_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEKTRO_SIM_TYPE_COMPONENT, ElektroSimComponent))
#define ELEKTRO_SIM_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEKTRO_SIM_TYPE_COMPONENT, ElektroSimComponentClass))
#define ELEKTRO_SIM_IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEKTRO_SIM_TYPE_COMPONENT))
#define ELEKTRO_SIM_IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEKTRO_SIM_TYPE_COMPONENT))
#define ELEKTRO_SIM_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEKTRO_SIM_TYPE_COMPONENT, ElektroSimComponentClass))

typedef struct _ElektroSimComponent ElektroSimComponent;
typedef struct _ElektroSimComponentClass ElektroSimComponentClass;
typedef struct _ElektroSimComponentPrivate ElektroSimComponentPrivate;

#define ELEKTRO_SIM_TYPE_PARAMETER (elektro_sim_parameter_get_type ())
#define ELEKTRO_SIM_PARAMETER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEKTRO_SIM_TYPE_PARAMETER, ElektroSimParameter))
#define ELEKTRO_SIM_PARAMETER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEKTRO_SIM_TYPE_PARAMETER, ElektroSimParameterClass))
#define ELEKTRO_SIM_IS_PARAMETER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEKTRO_SIM_TYPE_PARAMETER))
#define ELEKTRO_SIM_IS_PARAMETER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEKTRO_SIM_TYPE_PARAMETER))
#define ELEKTRO_SIM_PARAMETER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEKTRO_SIM_TYPE_PARAMETER, ElektroSimParameterClass))

typedef struct _ElektroSimParameter ElektroSimParameter;
typedef struct _ElektroSimParameterClass ElektroSimParameterClass;

#define ELEKTRO_SIM_TYPE_POINT (elektro_sim_point_get_type ())
#define ELEKTRO_SIM_POINT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEKTRO_SIM_TYPE_POINT, ElektroSimPoint))
#define ELEKTRO_SIM_POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEKTRO_SIM_TYPE_POINT, ElektroSimPointClass))
#define ELEKTRO_SIM_IS_POINT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEKTRO_SIM_TYPE_POINT))
#define ELEKTRO_SIM_IS_POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEKTRO_SIM_TYPE_POINT))
#define ELEKTRO_SIM_POINT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEKTRO_SIM_TYPE_POINT, ElektroSimPointClass))

typedef struct _ElektroSimPoint ElektroSimPoint;
typedef struct _ElektroSimPointClass ElektroSimPointClass;

#define ELEKTRO_SIM_COMPONENT_TYPE_COMPONENT_TYPE (elektro_sim_component_component_type_get_type ())

#define ELEKTRO_SIM_COMPONENT_TYPE_ORIENTATION (elektro_sim_component_orientation_get_type ())

#define ELEKTRO_SIM_COMPONENT_TYPE_ACTIVITY (elektro_sim_component_activity_get_type ())

#define ELEKTRO_SIM_COMPONENT_TYPE_ZONE (elektro_sim_component_zone_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _cairo_surface_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_surface_destroy (var), NULL)))
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))

#define ELEKTRO_SIM_PARAMETER_TYPE_WIDGET_STYLE (elektro_sim_parameter_widget_style_get_type ())
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

#define ELEKTRO_SIM_COMPONENT_LIST_TYPE_MODE (elektro_sim_component_list_mode_get_type ())
typedef struct _ElektroSimParameterPrivate ElektroSimParameterPrivate;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))

struct _ElektroSimComponent {
	GtkListBoxRow parent_instance;
	ElektroSimComponentPrivate * priv;
	GeeArrayList* parameters;
	GeeArrayList* connections;
	cairo_surface_t* image_surface;
	cairo_t* image_context;
	cairo_surface_t* emoticon_surface;
	cairo_t* emoticon_context;
};

struct _ElektroSimComponentClass {
	GtkListBoxRowClass parent_class;
	ElektroSimComponent* (*clone) (ElektroSimComponent* self);
	void (*snap) (ElektroSimComponent* self, gint range, gint x, gint y);
	void (*draw_image) (ElektroSimComponent* self, cairo_t* cr);
	void (*clear_counter) (ElektroSimComponent* self);
	gchar* (*get_netlist_line) (ElektroSimComponent* self);
};

typedef enum  {
	ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_COMPONENT,
	ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_TEMPLATE,
	ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_SIMULATION
} ElektroSimComponentComponentType;

typedef enum  {
	ELEKTRO_SIM_COMPONENT_ORIENTATION_NONE,
	ELEKTRO_SIM_COMPONENT_ORIENTATION_RIGHT,
	ELEKTRO_SIM_COMPONENT_ORIENTATION_LEFT,
	ELEKTRO_SIM_COMPONENT_ORIENTATION_DOWN,
	ELEKTRO_SIM_COMPONENT_ORIENTATION_UP
} ElektroSimComponentOrientation;

struct _ElektroSimComponentPrivate {
	gint _height;
	gint _width;
	ElektroSimComponentComponentType _componentType;
	ElektroSimComponentOrientation _orientation;
	GtkBox* _grid;
	gchar* emoticons;
	GtkLabel* label;
	gint selected_parameter;
};

typedef enum  {
	ELEKTRO_SIM_COMPONENT_ACTIVITY_UNKNOWN,
	ELEKTRO_SIM_COMPONENT_ACTIVITY_INACTIVE,
	ELEKTRO_SIM_COMPONENT_ACTIVITY_SUBACTIVE,
	ELEKTRO_SIM_COMPONENT_ACTIVITY_ACTIVE,
	ELEKTRO_SIM_COMPONENT_ACTIVITY_OVERACTIVE
} ElektroSimComponentActivity;

typedef enum  {
	ELEKTRO_SIM_COMPONENT_ZONE_UNKNOWN,
	ELEKTRO_SIM_COMPONENT_ZONE_SUBOPTIMAL,
	ELEKTRO_SIM_COMPONENT_ZONE_OPTIMAL,
	ELEKTRO_SIM_COMPONENT_ZONE_OUTOFRANGE,
	ELEKTRO_SIM_COMPONENT_ZONE_DESTRUCTIVE
} ElektroSimComponentZone;

typedef enum  {
	ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_NONE,
	ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_LABEL,
	ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_ENTRY,
	ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_OPTIONS,
	ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_SLIDER
} ElektroSimParameterWidgetStyle;

typedef enum  {
	ELEKTRO_SIM_COMPONENT_LIST_MODE_UNKNOWN,
	ELEKTRO_SIM_COMPONENT_LIST_MODE_EDIT,
	ELEKTRO_SIM_COMPONENT_LIST_MODE_SIMULATION
} ElektroSimComponentListMode;

struct _ElektroSimParameter {
	GtkBox parent_instance;
	ElektroSimParameterPrivate * priv;
	gchar* unit;
};

struct _ElektroSimParameterClass {
	GtkBoxClass parent_class;
};


static gpointer elektro_sim_component_parent_class = NULL;

GType elektro_sim_component_get_type (void) G_GNUC_CONST;
GType elektro_sim_parameter_get_type (void) G_GNUC_CONST;
gpointer elektro_sim_point_ref (gpointer instance);
void elektro_sim_point_unref (gpointer instance);
GParamSpec* elektro_sim_param_spec_point (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void elektro_sim_value_set_point (GValue* value, gpointer v_object);
void elektro_sim_value_take_point (GValue* value, gpointer v_object);
gpointer elektro_sim_value_get_point (const GValue* value);
GType elektro_sim_point_get_type (void) G_GNUC_CONST;
GType elektro_sim_component_component_type_get_type (void) G_GNUC_CONST;
GType elektro_sim_component_orientation_get_type (void) G_GNUC_CONST;
#define ELEKTRO_SIM_COMPONENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ELEKTRO_SIM_TYPE_COMPONENT, ElektroSimComponentPrivate))
enum  {
	ELEKTRO_SIM_COMPONENT_DUMMY_PROPERTY,
	ELEKTRO_SIM_COMPONENT_HEIGHT,
	ELEKTRO_SIM_COMPONENT_WIDTH,
	ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE,
	ELEKTRO_SIM_COMPONENT_ORIENTATION,
	ELEKTRO_SIM_COMPONENT_GRID
};
GType elektro_sim_component_activity_get_type (void) G_GNUC_CONST;
GType elektro_sim_component_zone_get_type (void) G_GNUC_CONST;
ElektroSimComponent* elektro_sim_component_construct (GType object_type, const gchar* name);
void elektro_sim_component_init (ElektroSimComponent* self, const gchar* name);
GType elektro_sim_parameter_widget_style_get_type (void) G_GNUC_CONST;
ElektroSimParameter* elektro_sim_component_add_parameter (ElektroSimComponent* self, const gchar* name, gdouble val, const gchar* unit, ElektroSimParameterWidgetStyle simulation, ElektroSimParameterWidgetStyle edit, GeeArrayList* options);
gchar* elektro_sim_component_to_string (ElektroSimComponent* self);
gchar* elektro_sim_parameter_to_string (ElektroSimParameter* self);
GtkBox* elektro_sim_component_get_grid (ElektroSimComponent* self);
void elektro_sim_component_set_grid (ElektroSimComponent* self, GtkBox* value);
void elektro_sim_component_set_name (ElektroSimComponent* self, const gchar* new_name);
void elektro_sim_component_clear_parameters (ElektroSimComponent* self);
GType elektro_sim_component_list_mode_get_type (void) G_GNUC_CONST;
void elektro_sim_component_set_mode (ElektroSimComponent* self, ElektroSimComponentListMode mode);
void elektro_sim_parameter_set_mode (ElektroSimParameter* self, ElektroSimComponentListMode mode);
void elektro_sim_component_invalidate_values (ElektroSimComponent* self);
void elektro_sim_parameter_set_invalidate_values (ElektroSimParameter* self, gboolean value);
ElektroSimParameter* elektro_sim_component_get_parameter (ElektroSimComponent* self, const gchar* name);
void elektro_sim_parameter_set_val (ElektroSimParameter* self, gdouble value);
void elektro_sim_parameter_set_edit_array (ElektroSimParameter* self, ElektroSimParameterWidgetStyle style);
void elektro_sim_parameter_set_simulation_array (ElektroSimParameter* self, ElektroSimParameterWidgetStyle style);
ElektroSimParameter* elektro_sim_parameter_new (const gchar* name, gdouble val, const gchar* unit);
ElektroSimParameter* elektro_sim_parameter_construct (GType object_type, const gchar* name, gdouble val, const gchar* unit);
static void ___lambda10_ (ElektroSimComponent* self);
static void ____lambda10__elektro_sim_parameter_edited (ElektroSimParameter* _sender, gpointer self);
GeeArrayList* elektro_sim_parameter_get_options (ElektroSimParameter* self);
ElektroSimParameter* elektro_sim_component_get_next_parameter (ElektroSimComponent* self);
GeeArrayList* elektro_sim_parameter_get_values (ElektroSimParameter* self);
ElektroSimParameter* elektro_sim_component_get_selected_parameter (ElektroSimComponent* self);
const gchar* elektro_sim_parameter_get_name (ElektroSimParameter* self);
ElektroSimComponent* elektro_sim_component_clone (ElektroSimComponent* self);
static ElektroSimComponent* elektro_sim_component_real_clone (ElektroSimComponent* self);
void elektro_sim_component_snap (ElektroSimComponent* self, gint range, gint x, gint y);
static void elektro_sim_component_real_snap (ElektroSimComponent* self, gint range, gint x, gint y);
void elektro_sim_component_draw_emoticon (ElektroSimComponent* self, cairo_t* cr, gint x, gint y);
gdouble elektro_sim_parameter_get_val (ElektroSimParameter* self);
void elektro_sim_component_draw_image (ElektroSimComponent* self, cairo_t* cr);
static void elektro_sim_component_real_draw_image (ElektroSimComponent* self, cairo_t* cr);
void elektro_sim_component_clear_counter (ElektroSimComponent* self);
static void elektro_sim_component_real_clear_counter (ElektroSimComponent* self);
gchar* elektro_sim_component_get_netlist_line (ElektroSimComponent* self);
static gchar* elektro_sim_component_real_get_netlist_line (ElektroSimComponent* self);
void elektro_sim_component_insert_simulation_data (ElektroSimComponent* self, const gchar* name, const gchar* val, gboolean add);
void elektro_sim_parameter_set_value (ElektroSimParameter* self, gdouble temp);
void elektro_sim_parameter_add_value (ElektroSimParameter* self, gdouble temp);
gint elektro_sim_component_get_height (ElektroSimComponent* self);
void elektro_sim_component_set_height (ElektroSimComponent* self, gint value);
gint elektro_sim_component_get_width (ElektroSimComponent* self);
void elektro_sim_component_set_width (ElektroSimComponent* self, gint value);
ElektroSimComponentComponentType elektro_sim_component_get_componentType (ElektroSimComponent* self);
void elektro_sim_component_set_componentType (ElektroSimComponent* self, ElektroSimComponentComponentType value);
ElektroSimComponentOrientation elektro_sim_component_get_orientation (ElektroSimComponent* self);
void elektro_sim_component_set_orientation (ElektroSimComponent* self, ElektroSimComponentOrientation value);
static void elektro_sim_component_finalize (GObject* obj);
static void _vala_elektro_sim_component_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_elektro_sim_component_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GType elektro_sim_component_activity_get_type (void) {
	static volatile gsize elektro_sim_component_activity_type_id__volatile = 0;
	if (g_once_init_enter (&elektro_sim_component_activity_type_id__volatile)) {
		static const GEnumValue values[] = {{ELEKTRO_SIM_COMPONENT_ACTIVITY_UNKNOWN, "ELEKTRO_SIM_COMPONENT_ACTIVITY_UNKNOWN", "unknown"}, {ELEKTRO_SIM_COMPONENT_ACTIVITY_INACTIVE, "ELEKTRO_SIM_COMPONENT_ACTIVITY_INACTIVE", "inactive"}, {ELEKTRO_SIM_COMPONENT_ACTIVITY_SUBACTIVE, "ELEKTRO_SIM_COMPONENT_ACTIVITY_SUBACTIVE", "subactive"}, {ELEKTRO_SIM_COMPONENT_ACTIVITY_ACTIVE, "ELEKTRO_SIM_COMPONENT_ACTIVITY_ACTIVE", "active"}, {ELEKTRO_SIM_COMPONENT_ACTIVITY_OVERACTIVE, "ELEKTRO_SIM_COMPONENT_ACTIVITY_OVERACTIVE", "overactive"}, {0, NULL, NULL}};
		GType elektro_sim_component_activity_type_id;
		elektro_sim_component_activity_type_id = g_enum_register_static ("ElektroSimComponentActivity", values);
		g_once_init_leave (&elektro_sim_component_activity_type_id__volatile, elektro_sim_component_activity_type_id);
	}
	return elektro_sim_component_activity_type_id__volatile;
}


GType elektro_sim_component_zone_get_type (void) {
	static volatile gsize elektro_sim_component_zone_type_id__volatile = 0;
	if (g_once_init_enter (&elektro_sim_component_zone_type_id__volatile)) {
		static const GEnumValue values[] = {{ELEKTRO_SIM_COMPONENT_ZONE_UNKNOWN, "ELEKTRO_SIM_COMPONENT_ZONE_UNKNOWN", "unknown"}, {ELEKTRO_SIM_COMPONENT_ZONE_SUBOPTIMAL, "ELEKTRO_SIM_COMPONENT_ZONE_SUBOPTIMAL", "suboptimal"}, {ELEKTRO_SIM_COMPONENT_ZONE_OPTIMAL, "ELEKTRO_SIM_COMPONENT_ZONE_OPTIMAL", "optimal"}, {ELEKTRO_SIM_COMPONENT_ZONE_OUTOFRANGE, "ELEKTRO_SIM_COMPONENT_ZONE_OUTOFRANGE", "outofrange"}, {ELEKTRO_SIM_COMPONENT_ZONE_DESTRUCTIVE, "ELEKTRO_SIM_COMPONENT_ZONE_DESTRUCTIVE", "destructive"}, {0, NULL, NULL}};
		GType elektro_sim_component_zone_type_id;
		elektro_sim_component_zone_type_id = g_enum_register_static ("ElektroSimComponentZone", values);
		g_once_init_leave (&elektro_sim_component_zone_type_id__volatile, elektro_sim_component_zone_type_id);
	}
	return elektro_sim_component_zone_type_id__volatile;
}


GType elektro_sim_component_orientation_get_type (void) {
	static volatile gsize elektro_sim_component_orientation_type_id__volatile = 0;
	if (g_once_init_enter (&elektro_sim_component_orientation_type_id__volatile)) {
		static const GEnumValue values[] = {{ELEKTRO_SIM_COMPONENT_ORIENTATION_NONE, "ELEKTRO_SIM_COMPONENT_ORIENTATION_NONE", "none"}, {ELEKTRO_SIM_COMPONENT_ORIENTATION_RIGHT, "ELEKTRO_SIM_COMPONENT_ORIENTATION_RIGHT", "right"}, {ELEKTRO_SIM_COMPONENT_ORIENTATION_LEFT, "ELEKTRO_SIM_COMPONENT_ORIENTATION_LEFT", "left"}, {ELEKTRO_SIM_COMPONENT_ORIENTATION_DOWN, "ELEKTRO_SIM_COMPONENT_ORIENTATION_DOWN", "down"}, {ELEKTRO_SIM_COMPONENT_ORIENTATION_UP, "ELEKTRO_SIM_COMPONENT_ORIENTATION_UP", "up"}, {0, NULL, NULL}};
		GType elektro_sim_component_orientation_type_id;
		elektro_sim_component_orientation_type_id = g_enum_register_static ("ElektroSimComponentOrientation", values);
		g_once_init_leave (&elektro_sim_component_orientation_type_id__volatile, elektro_sim_component_orientation_type_id);
	}
	return elektro_sim_component_orientation_type_id__volatile;
}


GType elektro_sim_component_component_type_get_type (void) {
	static volatile gsize elektro_sim_component_component_type_type_id__volatile = 0;
	if (g_once_init_enter (&elektro_sim_component_component_type_type_id__volatile)) {
		static const GEnumValue values[] = {{ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_COMPONENT, "ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_COMPONENT", "component"}, {ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_TEMPLATE, "ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_TEMPLATE", "template"}, {ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_SIMULATION, "ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_SIMULATION", "simulation"}, {0, NULL, NULL}};
		GType elektro_sim_component_component_type_type_id;
		elektro_sim_component_component_type_type_id = g_enum_register_static ("ElektroSimComponentComponentType", values);
		g_once_init_leave (&elektro_sim_component_component_type_type_id__volatile, elektro_sim_component_component_type_type_id);
	}
	return elektro_sim_component_component_type_type_id__volatile;
}


ElektroSimComponent* elektro_sim_component_construct (GType object_type, const gchar* name) {
	ElektroSimComponent * self = NULL;
	const gchar* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	GeeArrayList* _tmp2_ = NULL;
	ElektroSimParameter* _tmp3_ = NULL;
	ElektroSimParameter* _tmp4_ = NULL;
	GeeArrayList* _tmp5_ = NULL;
	GeeArrayList* _tmp6_ = NULL;
	ElektroSimParameter* _tmp7_ = NULL;
	ElektroSimParameter* _tmp8_ = NULL;
	ElektroSimParameter* activity = NULL;
	GeeArrayList* _tmp9_ = NULL;
	GeeArrayList* _tmp10_ = NULL;
	ElektroSimParameter* _tmp11_ = NULL;
	ElektroSimParameter* _tmp12_ = NULL;
	ElektroSimParameter* work_zone = NULL;
	GeeArrayList* _tmp13_ = NULL;
	GeeArrayList* _tmp14_ = NULL;
	ElektroSimParameter* _tmp15_ = NULL;
	ElektroSimParameter* _tmp16_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	self = (ElektroSimComponent*) g_object_new (object_type, NULL);
	_tmp0_ = name;
	elektro_sim_component_init (self, _tmp0_);
	_tmp1_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = elektro_sim_component_add_parameter (self, "i", (gdouble) 0, "A", ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_LABEL, ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_NONE, _tmp2_);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp4_);
	_g_object_unref0 (_tmp2_);
	_tmp5_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = elektro_sim_component_add_parameter (self, "p", (gdouble) 0, "V", ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_LABEL, ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_NONE, _tmp6_);
	_tmp8_ = _tmp7_;
	_g_object_unref0 (_tmp8_);
	_g_object_unref0 (_tmp6_);
	_tmp9_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	_tmp10_ = _tmp9_;
	_tmp11_ = elektro_sim_component_add_parameter (self, "activity", (gdouble) ELEKTRO_SIM_COMPONENT_ACTIVITY_UNKNOWN, "", ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_LABEL, ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_NONE, _tmp10_);
	_tmp12_ = _tmp11_;
	_g_object_unref0 (_tmp10_);
	activity = _tmp12_;
	_tmp13_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	_tmp14_ = _tmp13_;
	_tmp15_ = elektro_sim_component_add_parameter (self, "work_zone", (gdouble) ELEKTRO_SIM_COMPONENT_ZONE_UNKNOWN, "", ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_LABEL, ELEKTRO_SIM_PARAMETER_WIDGET_STYLE_NONE, _tmp14_);
	_tmp16_ = _tmp15_;
	_g_object_unref0 (_tmp14_);
	work_zone = _tmp16_;
	self->priv->selected_parameter = -1;
	_g_object_unref0 (work_zone);
	_g_object_unref0 (activity);
	return self;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


gchar* elektro_sim_component_to_string (ElektroSimComponent* self) {
	gchar* result = NULL;
	gchar* line = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	GList* tl = NULL;
	GtkBox* _tmp21_ = NULL;
	GList* _tmp22_ = NULL;
	GList* _tmp23_ = NULL;
	const gchar* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gtk_widget_get_name ((GtkWidget*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strconcat (_tmp1_, ":\n parameters in parameters:\n", NULL);
	_g_free0 (line);
	line = _tmp2_;
	{
		GeeArrayList* _par_list = NULL;
		GeeArrayList* _tmp3_ = NULL;
		GeeArrayList* _tmp4_ = NULL;
		gint _par_size = 0;
		GeeArrayList* _tmp5_ = NULL;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		gint _par_index = 0;
		_tmp3_ = self->parameters;
		_tmp4_ = _g_object_ref0 (_tmp3_);
		_par_list = _tmp4_;
		_tmp5_ = _par_list;
		_tmp6_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp5_);
		_tmp7_ = _tmp6_;
		_par_size = _tmp7_;
		_par_index = -1;
		while (TRUE) {
			gint _tmp8_ = 0;
			gint _tmp9_ = 0;
			gint _tmp10_ = 0;
			ElektroSimParameter* par = NULL;
			GeeArrayList* _tmp11_ = NULL;
			gint _tmp12_ = 0;
			gpointer _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
			ElektroSimParameter* _tmp15_ = NULL;
			gchar* _tmp16_ = NULL;
			gchar* _tmp17_ = NULL;
			gchar* _tmp18_ = NULL;
			_tmp8_ = _par_index;
			_par_index = _tmp8_ + 1;
			_tmp9_ = _par_index;
			_tmp10_ = _par_size;
			if (!(_tmp9_ < _tmp10_)) {
				break;
			}
			_tmp11_ = _par_list;
			_tmp12_ = _par_index;
			_tmp13_ = gee_abstract_list_get ((GeeAbstractList*) _tmp11_, _tmp12_);
			par = (ElektroSimParameter*) _tmp13_;
			_tmp14_ = line;
			_tmp15_ = par;
			_tmp16_ = elektro_sim_parameter_to_string (_tmp15_);
			_tmp17_ = _tmp16_;
			_tmp18_ = g_strconcat (_tmp14_, _tmp17_, NULL);
			_g_free0 (line);
			line = _tmp18_;
			_g_free0 (_tmp17_);
			_g_object_unref0 (par);
		}
		_g_object_unref0 (_par_list);
	}
	_tmp19_ = line;
	_tmp20_ = g_strconcat (_tmp19_, "\n parameters in grid:\n", NULL);
	_g_free0 (line);
	line = _tmp20_;
	_tmp21_ = self->priv->_grid;
	_tmp22_ = gtk_container_get_children ((GtkContainer*) _tmp21_);
	tl = _tmp22_;
	_tmp23_ = tl;
	{
		GList* parameter_collection = NULL;
		GList* parameter_it = NULL;
		parameter_collection = _tmp23_;
		for (parameter_it = parameter_collection; parameter_it != NULL; parameter_it = parameter_it->next) {
			GtkWidget* _tmp24_ = NULL;
			GtkWidget* parameter = NULL;
			_tmp24_ = _g_object_ref0 ((GtkWidget*) parameter_it->data);
			parameter = _tmp24_;
			{
				const gchar* _tmp25_ = NULL;
				GtkWidget* _tmp26_ = NULL;
				gchar* _tmp27_ = NULL;
				gchar* _tmp28_ = NULL;
				gchar* _tmp29_ = NULL;
				_tmp25_ = line;
				_tmp26_ = parameter;
				_tmp27_ = elektro_sim_parameter_to_string (G_TYPE_CHECK_INSTANCE_TYPE (_tmp26_, ELEKTRO_SIM_TYPE_PARAMETER) ? ((ElektroSimParameter*) _tmp26_) : NULL);
				_tmp28_ = _tmp27_;
				_tmp29_ = g_strconcat (_tmp25_, _tmp28_, NULL);
				_g_free0 (line);
				line = _tmp29_;
				_g_free0 (_tmp28_);
				_g_object_unref0 (parameter);
			}
		}
	}
	_tmp30_ = line;
	_tmp31_ = g_strconcat (_tmp30_, "\n\n", NULL);
	_g_free0 (line);
	line = _tmp31_;
	result = line;
	_g_list_free0 (tl);
	return result;
}


void elektro_sim_component_init (ElektroSimComponent* self, const gchar* name) {
	gchar* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkBox* _tmp5_ = NULL;
	GtkLabel* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	GtkBox* _tmp8_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = g_strdup ("/usr/share/elektrosim/");
	_g_free0 (self->priv->emoticons);
	self->priv->emoticons = _tmp0_;
	_tmp1_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp1_);
	_tmp2_ = _tmp1_;
	elektro_sim_component_set_grid (self, _tmp2_);
	_g_object_unref0 (_tmp2_);
	_tmp3_ = name;
	_tmp4_ = (GtkLabel*) gtk_label_new (_tmp3_);
	g_object_ref_sink (_tmp4_);
	_g_object_unref0 (self->priv->label);
	self->priv->label = _tmp4_;
	_tmp5_ = self->priv->_grid;
	_tmp6_ = self->priv->label;
	gtk_container_add ((GtkContainer*) _tmp5_, (GtkWidget*) _tmp6_);
	_tmp7_ = name;
	elektro_sim_component_set_name (self, _tmp7_);
	_tmp8_ = self->priv->_grid;
	gtk_container_add ((GtkContainer*) (G_TYPE_CHECK_INSTANCE_TYPE (self, GTK_TYPE_LIST_BOX_ROW) ? ((GtkListBoxRow*) self) : NULL), (GtkWidget*) _tmp8_);
}


void elektro_sim_component_clear_parameters (ElektroSimComponent* self) {
	GList* tl = NULL;
	GtkBox* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
	GList* _tmp2_ = NULL;
	GeeArrayList* _tmp8_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_grid;
	_tmp1_ = gtk_container_get_children ((GtkContainer*) _tmp0_);
	tl = _tmp1_;
	_tmp2_ = tl;
	{
		GList* parameter_collection = NULL;
		GList* parameter_it = NULL;
		parameter_collection = _tmp2_;
		for (parameter_it = parameter_collection; parameter_it != NULL; parameter_it = parameter_it->next) {
			GtkWidget* _tmp3_ = NULL;
			GtkWidget* parameter = NULL;
			_tmp3_ = _g_object_ref0 ((GtkWidget*) parameter_it->data);
			parameter = _tmp3_;
			{
				GtkWidget* _tmp4_ = NULL;
				GType _tmp5_ = 0UL;
				_tmp4_ = parameter;
				_tmp5_ = G_TYPE_FROM_INSTANCE ((GObject*) _tmp4_);
				if (_tmp5_ != GTK_TYPE_LABEL) {
					GtkBox* _tmp6_ = NULL;
					GtkWidget* _tmp7_ = NULL;
					_tmp6_ = self->priv->_grid;
					_tmp7_ = parameter;
					gtk_container_remove ((GtkContainer*) _tmp6_, _tmp7_);
				}
				_g_object_unref0 (parameter);
			}
		}
	}
	_tmp8_ = gee_array_list_new (ELEKTRO_SIM_TYPE_PARAMETER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->parameters);
	self->parameters = _tmp8_;
	_g_list_free0 (tl);
}


void elektro_sim_component_set_mode (ElektroSimComponent* self, ElektroSimComponentListMode mode) {
	g_return_if_fail (self != NULL);
	{
		GeeArrayList* _par_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _par_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _par_index = 0;
		_tmp0_ = self->parameters;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_par_list = _tmp1_;
		_tmp2_ = _par_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_par_size = _tmp4_;
		_par_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			ElektroSimParameter* par = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			ElektroSimParameter* _tmp11_ = NULL;
			ElektroSimComponentListMode _tmp12_ = 0;
			_tmp5_ = _par_index;
			_par_index = _tmp5_ + 1;
			_tmp6_ = _par_index;
			_tmp7_ = _par_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _par_list;
			_tmp9_ = _par_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			par = (ElektroSimParameter*) _tmp10_;
			_tmp11_ = par;
			_tmp12_ = mode;
			elektro_sim_parameter_set_mode (_tmp11_, _tmp12_);
			_g_object_unref0 (par);
		}
		_g_object_unref0 (_par_list);
	}
}


void elektro_sim_component_set_name (ElektroSimComponent* self, const gchar* new_name) {
	GList* tl = NULL;
	GtkBox* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
	GList* _tmp2_ = NULL;
	const gchar* _tmp8_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (new_name != NULL);
	_tmp0_ = self->priv->_grid;
	_tmp1_ = gtk_container_get_children ((GtkContainer*) _tmp0_);
	tl = _tmp1_;
	_tmp2_ = tl;
	{
		GList* parameter_collection = NULL;
		GList* parameter_it = NULL;
		parameter_collection = _tmp2_;
		for (parameter_it = parameter_collection; parameter_it != NULL; parameter_it = parameter_it->next) {
			GtkWidget* _tmp3_ = NULL;
			GtkWidget* parameter = NULL;
			_tmp3_ = _g_object_ref0 ((GtkWidget*) parameter_it->data);
			parameter = _tmp3_;
			{
				GtkWidget* _tmp4_ = NULL;
				GType _tmp5_ = 0UL;
				_tmp4_ = parameter;
				_tmp5_ = G_TYPE_FROM_INSTANCE ((GObject*) _tmp4_);
				if (_tmp5_ == GTK_TYPE_LABEL) {
					GtkWidget* _tmp6_ = NULL;
					const gchar* _tmp7_ = NULL;
					_tmp6_ = parameter;
					_tmp7_ = new_name;
					gtk_label_set_label (G_TYPE_CHECK_INSTANCE_TYPE (_tmp6_, GTK_TYPE_LABEL) ? ((GtkLabel*) _tmp6_) : NULL, _tmp7_);
				}
				_g_object_unref0 (parameter);
			}
		}
	}
	_tmp8_ = new_name;
	gtk_widget_set_name ((GtkWidget*) self, _tmp8_);
	_g_list_free0 (tl);
}


void elektro_sim_component_invalidate_values (ElektroSimComponent* self) {
	g_return_if_fail (self != NULL);
	{
		GeeArrayList* _par_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _par_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _par_index = 0;
		_tmp0_ = self->parameters;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_par_list = _tmp1_;
		_tmp2_ = _par_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_par_size = _tmp4_;
		_par_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			ElektroSimParameter* par = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			ElektroSimParameter* _tmp11_ = NULL;
			_tmp5_ = _par_index;
			_par_index = _tmp5_ + 1;
			_tmp6_ = _par_index;
			_tmp7_ = _par_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _par_list;
			_tmp9_ = _par_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			par = (ElektroSimParameter*) _tmp10_;
			_tmp11_ = par;
			elektro_sim_parameter_set_invalidate_values (_tmp11_, TRUE);
			_g_object_unref0 (par);
		}
		_g_object_unref0 (_par_list);
	}
}


static void ___lambda10_ (ElektroSimComponent* self) {
	g_signal_emit_by_name (self, "request-simulate");
}


static void ____lambda10__elektro_sim_parameter_edited (ElektroSimParameter* _sender, gpointer self) {
	___lambda10_ ((ElektroSimComponent*) self);
}


ElektroSimParameter* elektro_sim_component_add_parameter (ElektroSimComponent* self, const gchar* name, gdouble val, const gchar* unit, ElektroSimParameterWidgetStyle simulation, ElektroSimParameterWidgetStyle edit, GeeArrayList* options) {
	ElektroSimParameter* result = NULL;
	ElektroSimParameter* par = NULL;
	const gchar* _tmp0_ = NULL;
	ElektroSimParameter* _tmp1_ = NULL;
	ElektroSimParameter* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (unit != NULL, NULL);
	g_return_val_if_fail (options != NULL, NULL);
	_tmp0_ = name;
	_tmp1_ = elektro_sim_component_get_parameter (self, _tmp0_);
	par = _tmp1_;
	_tmp2_ = par;
	if (_tmp2_ != NULL) {
		ElektroSimParameter* _tmp3_ = NULL;
		gdouble _tmp4_ = 0.0;
		ElektroSimParameter* _tmp5_ = NULL;
		ElektroSimParameterWidgetStyle _tmp6_ = 0;
		ElektroSimParameter* _tmp7_ = NULL;
		ElektroSimParameterWidgetStyle _tmp8_ = 0;
		ElektroSimParameter* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		_tmp3_ = par;
		_tmp4_ = val;
		elektro_sim_parameter_set_val (_tmp3_, _tmp4_);
		_tmp5_ = par;
		_tmp6_ = edit;
		elektro_sim_parameter_set_edit_array (_tmp5_, _tmp6_);
		_tmp7_ = par;
		_tmp8_ = simulation;
		elektro_sim_parameter_set_simulation_array (_tmp7_, _tmp8_);
		_tmp9_ = par;
		_tmp10_ = unit;
		_tmp11_ = g_strdup (_tmp10_);
		_g_free0 (_tmp9_->unit);
		_tmp9_->unit = _tmp11_;
	} else {
		const gchar* _tmp12_ = NULL;
		gdouble _tmp13_ = 0.0;
		const gchar* _tmp14_ = NULL;
		ElektroSimParameter* _tmp15_ = NULL;
		GeeArrayList* _tmp16_ = NULL;
		ElektroSimParameter* _tmp17_ = NULL;
		ElektroSimParameter* _tmp18_ = NULL;
		ElektroSimParameter* _tmp34_ = NULL;
		ElektroSimParameterWidgetStyle _tmp35_ = 0;
		ElektroSimParameter* _tmp36_ = NULL;
		ElektroSimParameterWidgetStyle _tmp37_ = 0;
		GtkBox* _tmp38_ = NULL;
		ElektroSimParameter* _tmp39_ = NULL;
		_tmp12_ = name;
		_tmp13_ = val;
		_tmp14_ = unit;
		_tmp15_ = elektro_sim_parameter_new (_tmp12_, _tmp13_, _tmp14_);
		g_object_ref_sink (_tmp15_);
		_g_object_unref0 (par);
		par = _tmp15_;
		_tmp16_ = self->parameters;
		_tmp17_ = par;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp16_, _tmp17_);
		_tmp18_ = par;
		g_signal_connect_object (_tmp18_, "edited", (GCallback) ____lambda10__elektro_sim_parameter_edited, self, 0);
		{
			GeeArrayList* _str_list = NULL;
			GeeArrayList* _tmp19_ = NULL;
			GeeArrayList* _tmp20_ = NULL;
			gint _str_size = 0;
			GeeArrayList* _tmp21_ = NULL;
			gint _tmp22_ = 0;
			gint _tmp23_ = 0;
			gint _str_index = 0;
			_tmp19_ = options;
			_tmp20_ = _g_object_ref0 (_tmp19_);
			_str_list = _tmp20_;
			_tmp21_ = _str_list;
			_tmp22_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp21_);
			_tmp23_ = _tmp22_;
			_str_size = _tmp23_;
			_str_index = -1;
			while (TRUE) {
				gint _tmp24_ = 0;
				gint _tmp25_ = 0;
				gint _tmp26_ = 0;
				gchar* str = NULL;
				GeeArrayList* _tmp27_ = NULL;
				gint _tmp28_ = 0;
				gpointer _tmp29_ = NULL;
				ElektroSimParameter* _tmp30_ = NULL;
				GeeArrayList* _tmp31_ = NULL;
				GeeArrayList* _tmp32_ = NULL;
				const gchar* _tmp33_ = NULL;
				_tmp24_ = _str_index;
				_str_index = _tmp24_ + 1;
				_tmp25_ = _str_index;
				_tmp26_ = _str_size;
				if (!(_tmp25_ < _tmp26_)) {
					break;
				}
				_tmp27_ = _str_list;
				_tmp28_ = _str_index;
				_tmp29_ = gee_abstract_list_get ((GeeAbstractList*) _tmp27_, _tmp28_);
				str = (gchar*) _tmp29_;
				_tmp30_ = par;
				_tmp31_ = elektro_sim_parameter_get_options (_tmp30_);
				_tmp32_ = _tmp31_;
				_tmp33_ = str;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp32_, _tmp33_);
				_g_free0 (str);
			}
			_g_object_unref0 (_str_list);
		}
		_tmp34_ = par;
		_tmp35_ = edit;
		elektro_sim_parameter_set_edit_array (_tmp34_, _tmp35_);
		_tmp36_ = par;
		_tmp37_ = simulation;
		elektro_sim_parameter_set_simulation_array (_tmp36_, _tmp37_);
		_tmp38_ = self->priv->_grid;
		_tmp39_ = par;
		gtk_container_add ((GtkContainer*) _tmp38_, (GtkWidget*) _tmp39_);
	}
	result = par;
	return result;
}


ElektroSimParameter* elektro_sim_component_get_next_parameter (ElektroSimComponent* self) {
	ElektroSimParameter* result = NULL;
	gboolean goRound = FALSE;
	GeeArrayList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	goRound = TRUE;
	_tmp0_ = self->parameters;
	if (_tmp0_ != NULL) {
		gint _tmp1_ = 0;
		gint _tmp2_ = 0;
		GeeArrayList* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		GeeArrayList* _tmp28_ = NULL;
		gint _tmp29_ = 0;
		gpointer _tmp30_ = NULL;
		_tmp1_ = self->priv->selected_parameter;
		self->priv->selected_parameter = _tmp1_ + 1;
		_tmp2_ = self->priv->selected_parameter;
		_tmp3_ = self->parameters;
		_tmp4_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp3_);
		_tmp5_ = _tmp4_;
		if (_tmp2_ >= _tmp5_) {
			self->priv->selected_parameter = 0;
			goRound = FALSE;
		}
		while (TRUE) {
			gboolean _tmp6_ = FALSE;
			GeeArrayList* _tmp7_ = NULL;
			gint _tmp8_ = 0;
			gpointer _tmp9_ = NULL;
			ElektroSimParameter* _tmp10_ = NULL;
			GeeArrayList* _tmp11_ = NULL;
			GeeArrayList* _tmp12_ = NULL;
			gboolean _tmp13_ = FALSE;
			gint _tmp22_ = 0;
			gint _tmp23_ = 0;
			GeeArrayList* _tmp24_ = NULL;
			gint _tmp25_ = 0;
			gint _tmp26_ = 0;
			_tmp7_ = self->parameters;
			_tmp8_ = self->priv->selected_parameter;
			_tmp9_ = gee_abstract_list_get ((GeeAbstractList*) _tmp7_, _tmp8_);
			_tmp10_ = (ElektroSimParameter*) _tmp9_;
			_tmp11_ = elektro_sim_parameter_get_values (_tmp10_);
			_tmp12_ = _tmp11_;
			_tmp13_ = _tmp12_ == NULL;
			_g_object_unref0 (_tmp10_);
			if (_tmp13_) {
				_tmp6_ = TRUE;
			} else {
				GeeArrayList* _tmp14_ = NULL;
				gint _tmp15_ = 0;
				gpointer _tmp16_ = NULL;
				ElektroSimParameter* _tmp17_ = NULL;
				GeeArrayList* _tmp18_ = NULL;
				GeeArrayList* _tmp19_ = NULL;
				gint _tmp20_ = 0;
				gint _tmp21_ = 0;
				_tmp14_ = self->parameters;
				_tmp15_ = self->priv->selected_parameter;
				_tmp16_ = gee_abstract_list_get ((GeeAbstractList*) _tmp14_, _tmp15_);
				_tmp17_ = (ElektroSimParameter*) _tmp16_;
				_tmp18_ = elektro_sim_parameter_get_values (_tmp17_);
				_tmp19_ = _tmp18_;
				_tmp20_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp19_);
				_tmp21_ = _tmp20_;
				_tmp6_ = _tmp21_ == 0;
				_g_object_unref0 (_tmp17_);
			}
			if (!_tmp6_) {
				break;
			}
			_tmp22_ = self->priv->selected_parameter;
			self->priv->selected_parameter = _tmp22_ + 1;
			_tmp23_ = self->priv->selected_parameter;
			_tmp24_ = self->parameters;
			_tmp25_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp24_);
			_tmp26_ = _tmp25_;
			if (_tmp23_ >= _tmp26_) {
				gboolean _tmp27_ = FALSE;
				_tmp27_ = goRound;
				if (_tmp27_) {
					self->priv->selected_parameter = 0;
					goRound = FALSE;
				} else {
					result = NULL;
					return result;
				}
			}
		}
		_tmp28_ = self->parameters;
		_tmp29_ = self->priv->selected_parameter;
		_tmp30_ = gee_abstract_list_get ((GeeAbstractList*) _tmp28_, _tmp29_);
		result = (ElektroSimParameter*) _tmp30_;
		return result;
	}
	result = NULL;
	return result;
}


ElektroSimParameter* elektro_sim_component_get_selected_parameter (ElektroSimComponent* self) {
	ElektroSimParameter* result = NULL;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GeeArrayList* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp2_ = self->parameters;
	if (_tmp2_ != NULL) {
		gint _tmp3_ = 0;
		_tmp3_ = self->priv->selected_parameter;
		_tmp1_ = _tmp3_ != (-1);
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		gint _tmp4_ = 0;
		GeeArrayList* _tmp5_ = NULL;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp4_ = self->priv->selected_parameter;
		_tmp5_ = self->parameters;
		_tmp6_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp5_);
		_tmp7_ = _tmp6_;
		_tmp0_ = _tmp4_ < _tmp7_;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		GeeArrayList* _tmp8_ = NULL;
		gint _tmp9_ = 0;
		gpointer _tmp10_ = NULL;
		_tmp8_ = self->parameters;
		_tmp9_ = self->priv->selected_parameter;
		_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
		result = (ElektroSimParameter*) _tmp10_;
		return result;
	} else {
		ElektroSimParameter* _tmp11_ = NULL;
		_tmp11_ = elektro_sim_component_get_next_parameter (self);
		result = _tmp11_;
		return result;
	}
}


ElektroSimParameter* elektro_sim_component_get_parameter (ElektroSimComponent* self, const gchar* name) {
	ElektroSimParameter* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	{
		GeeArrayList* _par_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _par_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _par_index = 0;
		_tmp0_ = self->parameters;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_par_list = _tmp1_;
		_tmp2_ = _par_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_par_size = _tmp4_;
		_par_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			ElektroSimParameter* par = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			ElektroSimParameter* _tmp11_ = NULL;
			const gchar* _tmp12_ = NULL;
			const gchar* _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
			_tmp5_ = _par_index;
			_par_index = _tmp5_ + 1;
			_tmp6_ = _par_index;
			_tmp7_ = _par_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _par_list;
			_tmp9_ = _par_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			par = (ElektroSimParameter*) _tmp10_;
			_tmp11_ = par;
			_tmp12_ = elektro_sim_parameter_get_name (_tmp11_);
			_tmp13_ = _tmp12_;
			_tmp14_ = name;
			if (g_strcmp0 (_tmp13_, _tmp14_) == 0) {
				result = par;
				_g_object_unref0 (_par_list);
				return result;
			}
			_g_object_unref0 (par);
		}
		_g_object_unref0 (_par_list);
	}
	result = NULL;
	return result;
}


static ElektroSimComponent* elektro_sim_component_real_clone (ElektroSimComponent* self) {
	g_critical ("Type `%s' does not implement abstract method `elektro_sim_component_clone'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return NULL;
}


ElektroSimComponent* elektro_sim_component_clone (ElektroSimComponent* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return ELEKTRO_SIM_COMPONENT_GET_CLASS (self)->clone (self);
}


static void elektro_sim_component_real_snap (ElektroSimComponent* self, gint range, gint x, gint y) {
	g_critical ("Type `%s' does not implement abstract method `elektro_sim_component_snap'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void elektro_sim_component_snap (ElektroSimComponent* self, gint range, gint x, gint y) {
	g_return_if_fail (self != NULL);
	ELEKTRO_SIM_COMPONENT_GET_CLASS (self)->snap (self, range, x, y);
}


void elektro_sim_component_draw_emoticon (ElektroSimComponent* self, cairo_t* cr, gint x, gint y) {
	ElektroSimParameter* act = NULL;
	ElektroSimParameter* _tmp0_ = NULL;
	ElektroSimParameter* zon = NULL;
	ElektroSimParameter* _tmp1_ = NULL;
	gint activity = 0;
	gint zone = 0;
	gboolean _tmp2_ = FALSE;
	ElektroSimParameter* _tmp3_ = NULL;
	GeeArrayList* _tmp4_ = NULL;
	GeeArrayList* _tmp5_ = NULL;
	gboolean _tmp32_ = FALSE;
	ElektroSimParameter* _tmp33_ = NULL;
	GeeArrayList* _tmp34_ = NULL;
	GeeArrayList* _tmp35_ = NULL;
	cairo_surface_t* temp_surface = NULL;
	cairo_surface_t* _tmp62_ = NULL;
	cairo_t* emoticon_context = NULL;
	cairo_surface_t* _tmp63_ = NULL;
	cairo_t* _tmp64_ = NULL;
	gchar* emoticon = NULL;
	gint _tmp65_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (cr != NULL);
	_tmp0_ = elektro_sim_component_get_parameter (self, "activity");
	act = _tmp0_;
	_tmp1_ = elektro_sim_component_get_parameter (self, "work_zone");
	zon = _tmp1_;
	activity = 0;
	zone = 0;
	_tmp3_ = act;
	_tmp4_ = elektro_sim_parameter_get_values (_tmp3_);
	_tmp5_ = _tmp4_;
	if (_tmp5_ == NULL) {
		_tmp2_ = TRUE;
	} else {
		ElektroSimParameter* _tmp6_ = NULL;
		GeeArrayList* _tmp7_ = NULL;
		GeeArrayList* _tmp8_ = NULL;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		_tmp6_ = act;
		_tmp7_ = elektro_sim_parameter_get_values (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp8_);
		_tmp10_ = _tmp9_;
		_tmp2_ = _tmp10_ < 1;
	}
	if (_tmp2_) {
		ElektroSimParameter* _tmp11_ = NULL;
		gdouble _tmp12_ = 0.0;
		gdouble _tmp13_ = 0.0;
		_tmp11_ = act;
		_tmp12_ = elektro_sim_parameter_get_val (_tmp11_);
		_tmp13_ = _tmp12_;
		activity = (gint) _tmp13_;
	} else {
		{
			GeeArrayList* _val_list = NULL;
			ElektroSimParameter* _tmp14_ = NULL;
			GeeArrayList* _tmp15_ = NULL;
			GeeArrayList* _tmp16_ = NULL;
			GeeArrayList* _tmp17_ = NULL;
			gint _val_size = 0;
			GeeArrayList* _tmp18_ = NULL;
			gint _tmp19_ = 0;
			gint _tmp20_ = 0;
			gint _val_index = 0;
			_tmp14_ = act;
			_tmp15_ = elektro_sim_parameter_get_values (_tmp14_);
			_tmp16_ = _tmp15_;
			_tmp17_ = _g_object_ref0 (_tmp16_);
			_val_list = _tmp17_;
			_tmp18_ = _val_list;
			_tmp19_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp18_);
			_tmp20_ = _tmp19_;
			_val_size = _tmp20_;
			_val_index = -1;
			while (TRUE) {
				gint _tmp21_ = 0;
				gint _tmp22_ = 0;
				gint _tmp23_ = 0;
				gdouble val = 0.0;
				GeeArrayList* _tmp24_ = NULL;
				gint _tmp25_ = 0;
				gpointer _tmp26_ = NULL;
				gdouble* _tmp27_ = NULL;
				gdouble _tmp28_ = 0.0;
				gint _tmp29_ = 0;
				gdouble _tmp30_ = 0.0;
				_tmp21_ = _val_index;
				_val_index = _tmp21_ + 1;
				_tmp22_ = _val_index;
				_tmp23_ = _val_size;
				if (!(_tmp22_ < _tmp23_)) {
					break;
				}
				_tmp24_ = _val_list;
				_tmp25_ = _val_index;
				_tmp26_ = gee_abstract_list_get ((GeeAbstractList*) _tmp24_, _tmp25_);
				_tmp27_ = (gdouble*) _tmp26_;
				_tmp28_ = *_tmp27_;
				_g_free0 (_tmp27_);
				val = _tmp28_;
				_tmp29_ = activity;
				_tmp30_ = val;
				if (((gdouble) _tmp29_) < _tmp30_) {
					gdouble _tmp31_ = 0.0;
					_tmp31_ = val;
					activity = (gint) _tmp31_;
				}
			}
			_g_object_unref0 (_val_list);
		}
	}
	_tmp33_ = zon;
	_tmp34_ = elektro_sim_parameter_get_values (_tmp33_);
	_tmp35_ = _tmp34_;
	if (_tmp35_ == NULL) {
		_tmp32_ = TRUE;
	} else {
		ElektroSimParameter* _tmp36_ = NULL;
		GeeArrayList* _tmp37_ = NULL;
		GeeArrayList* _tmp38_ = NULL;
		gint _tmp39_ = 0;
		gint _tmp40_ = 0;
		_tmp36_ = zon;
		_tmp37_ = elektro_sim_parameter_get_values (_tmp36_);
		_tmp38_ = _tmp37_;
		_tmp39_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp38_);
		_tmp40_ = _tmp39_;
		_tmp32_ = _tmp40_ < 1;
	}
	if (_tmp32_) {
		ElektroSimParameter* _tmp41_ = NULL;
		gdouble _tmp42_ = 0.0;
		gdouble _tmp43_ = 0.0;
		_tmp41_ = zon;
		_tmp42_ = elektro_sim_parameter_get_val (_tmp41_);
		_tmp43_ = _tmp42_;
		zone = (gint) _tmp43_;
	} else {
		{
			GeeArrayList* _val_list = NULL;
			ElektroSimParameter* _tmp44_ = NULL;
			GeeArrayList* _tmp45_ = NULL;
			GeeArrayList* _tmp46_ = NULL;
			GeeArrayList* _tmp47_ = NULL;
			gint _val_size = 0;
			GeeArrayList* _tmp48_ = NULL;
			gint _tmp49_ = 0;
			gint _tmp50_ = 0;
			gint _val_index = 0;
			_tmp44_ = zon;
			_tmp45_ = elektro_sim_parameter_get_values (_tmp44_);
			_tmp46_ = _tmp45_;
			_tmp47_ = _g_object_ref0 (_tmp46_);
			_val_list = _tmp47_;
			_tmp48_ = _val_list;
			_tmp49_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp48_);
			_tmp50_ = _tmp49_;
			_val_size = _tmp50_;
			_val_index = -1;
			while (TRUE) {
				gint _tmp51_ = 0;
				gint _tmp52_ = 0;
				gint _tmp53_ = 0;
				gdouble val = 0.0;
				GeeArrayList* _tmp54_ = NULL;
				gint _tmp55_ = 0;
				gpointer _tmp56_ = NULL;
				gdouble* _tmp57_ = NULL;
				gdouble _tmp58_ = 0.0;
				gint _tmp59_ = 0;
				gdouble _tmp60_ = 0.0;
				_tmp51_ = _val_index;
				_val_index = _tmp51_ + 1;
				_tmp52_ = _val_index;
				_tmp53_ = _val_size;
				if (!(_tmp52_ < _tmp53_)) {
					break;
				}
				_tmp54_ = _val_list;
				_tmp55_ = _val_index;
				_tmp56_ = gee_abstract_list_get ((GeeAbstractList*) _tmp54_, _tmp55_);
				_tmp57_ = (gdouble*) _tmp56_;
				_tmp58_ = *_tmp57_;
				_g_free0 (_tmp57_);
				val = _tmp58_;
				_tmp59_ = zone;
				_tmp60_ = val;
				if (((gdouble) _tmp59_) < _tmp60_) {
					gdouble _tmp61_ = 0.0;
					_tmp61_ = val;
					zone = (gint) _tmp61_;
				}
			}
			_g_object_unref0 (_val_list);
		}
	}
	_tmp62_ = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, 100, 100);
	temp_surface = _tmp62_;
	_tmp63_ = temp_surface;
	_tmp64_ = cairo_create (_tmp63_);
	emoticon_context = _tmp64_;
	_tmp65_ = activity;
	if (_tmp65_ != ((gint) ELEKTRO_SIM_COMPONENT_ACTIVITY_UNKNOWN)) {
		gchar* _tmp66_ = NULL;
		gint _tmp67_ = 0;
		const gchar* _tmp106_ = NULL;
		_tmp66_ = g_strdup ("");
		_g_free0 (emoticon);
		emoticon = _tmp66_;
		_tmp67_ = activity;
		if (_tmp67_ == ((gint) ELEKTRO_SIM_COMPONENT_ACTIVITY_INACTIVE)) {
			const gchar* _tmp68_ = NULL;
			gchar* _tmp69_ = NULL;
			_tmp68_ = self->priv->emoticons;
			_tmp69_ = g_strconcat (_tmp68_, "deepSleepAlien.svg", NULL);
			_g_free0 (emoticon);
			emoticon = _tmp69_;
		} else {
			gint _tmp70_ = 0;
			_tmp70_ = activity;
			if (_tmp70_ == ((gint) ELEKTRO_SIM_COMPONENT_ACTIVITY_SUBACTIVE)) {
				gint _tmp71_ = 0;
				_tmp71_ = zone;
				switch (_tmp71_) {
					case ELEKTRO_SIM_COMPONENT_ZONE_DESTRUCTIVE:
					{
						const gchar* _tmp72_ = NULL;
						gchar* _tmp73_ = NULL;
						_tmp72_ = self->priv->emoticons;
						_tmp73_ = g_strconcat (_tmp72_, "angstigSleepyAlien.svg", NULL);
						_g_free0 (emoticon);
						emoticon = _tmp73_;
						break;
					}
					case ELEKTRO_SIM_COMPONENT_ZONE_OUTOFRANGE:
					{
						const gchar* _tmp74_ = NULL;
						gchar* _tmp75_ = NULL;
						_tmp74_ = self->priv->emoticons;
						_tmp75_ = g_strconcat (_tmp74_, "stressesSleepyAlien.svg", NULL);
						_g_free0 (emoticon);
						emoticon = _tmp75_;
						break;
					}
					case ELEKTRO_SIM_COMPONENT_ZONE_OPTIMAL:
					{
						const gchar* _tmp76_ = NULL;
						gchar* _tmp77_ = NULL;
						_tmp76_ = self->priv->emoticons;
						_tmp77_ = g_strconcat (_tmp76_, "sleepyAlien.svg", NULL);
						_g_free0 (emoticon);
						emoticon = _tmp77_;
						break;
					}
					case ELEKTRO_SIM_COMPONENT_ZONE_SUBOPTIMAL:
					{
						const gchar* _tmp78_ = NULL;
						gchar* _tmp79_ = NULL;
						_tmp78_ = self->priv->emoticons;
						_tmp79_ = g_strconcat (_tmp78_, "sleepyAlien.svg", NULL);
						_g_free0 (emoticon);
						emoticon = _tmp79_;
						break;
					}
					default:
					{
						const gchar* _tmp80_ = NULL;
						const gchar* _tmp81_ = NULL;
						gchar* _tmp82_ = NULL;
						_tmp80_ = gtk_widget_get_name ((GtkWidget*) self);
						_tmp81_ = _tmp80_;
						g_print ("found no zone subactive on %s", _tmp81_);
						_tmp82_ = g_strdup ("");
						_g_free0 (emoticon);
						emoticon = _tmp82_;
						break;
					}
				}
			} else {
				gint _tmp83_ = 0;
				_tmp83_ = activity;
				if (_tmp83_ == ((gint) ELEKTRO_SIM_COMPONENT_ACTIVITY_ACTIVE)) {
					gint _tmp84_ = 0;
					_tmp84_ = zone;
					switch (_tmp84_) {
						case ELEKTRO_SIM_COMPONENT_ZONE_DESTRUCTIVE:
						{
							const gchar* _tmp85_ = NULL;
							gchar* _tmp86_ = NULL;
							_tmp85_ = self->priv->emoticons;
							_tmp86_ = g_strconcat (_tmp85_, "stressedAlien.svg", NULL);
							_g_free0 (emoticon);
							emoticon = _tmp86_;
							break;
						}
						case ELEKTRO_SIM_COMPONENT_ZONE_OUTOFRANGE:
						{
							const gchar* _tmp87_ = NULL;
							gchar* _tmp88_ = NULL;
							_tmp87_ = self->priv->emoticons;
							_tmp88_ = g_strconcat (_tmp87_, "stressedSadAlien.svg", NULL);
							_g_free0 (emoticon);
							emoticon = _tmp88_;
							break;
						}
						case ELEKTRO_SIM_COMPONENT_ZONE_OPTIMAL:
						{
							const gchar* _tmp89_ = NULL;
							gchar* _tmp90_ = NULL;
							_tmp89_ = self->priv->emoticons;
							_tmp90_ = g_strconcat (_tmp89_, "HappyAlien.svg", NULL);
							_g_free0 (emoticon);
							emoticon = _tmp90_;
							break;
						}
						case ELEKTRO_SIM_COMPONENT_ZONE_SUBOPTIMAL:
						{
							const gchar* _tmp91_ = NULL;
							gchar* _tmp92_ = NULL;
							_tmp91_ = self->priv->emoticons;
							_tmp92_ = g_strconcat (_tmp91_, "NerveusAlien.svg", NULL);
							_g_free0 (emoticon);
							emoticon = _tmp92_;
							break;
						}
						default:
						{
							gchar* _tmp93_ = NULL;
							g_print ("found no zone active");
							_tmp93_ = g_strdup ("");
							_g_free0 (emoticon);
							emoticon = _tmp93_;
							break;
						}
					}
				} else {
					gint _tmp94_ = 0;
					_tmp94_ = activity;
					if (_tmp94_ == ((gint) ELEKTRO_SIM_COMPONENT_ACTIVITY_OVERACTIVE)) {
						gint _tmp95_ = 0;
						_tmp95_ = zone;
						switch (_tmp95_) {
							case ELEKTRO_SIM_COMPONENT_ZONE_DESTRUCTIVE:
							{
								const gchar* _tmp96_ = NULL;
								gchar* _tmp97_ = NULL;
								_tmp96_ = self->priv->emoticons;
								_tmp97_ = g_strconcat (_tmp96_, "ScaredAlien.svg", NULL);
								_g_free0 (emoticon);
								emoticon = _tmp97_;
								break;
							}
							case ELEKTRO_SIM_COMPONENT_ZONE_OUTOFRANGE:
							{
								const gchar* _tmp98_ = NULL;
								gchar* _tmp99_ = NULL;
								_tmp98_ = self->priv->emoticons;
								_tmp99_ = g_strconcat (_tmp98_, "depresiveAlien.svg", NULL);
								_g_free0 (emoticon);
								emoticon = _tmp99_;
								break;
							}
							case ELEKTRO_SIM_COMPONENT_ZONE_OPTIMAL:
							{
								const gchar* _tmp100_ = NULL;
								gchar* _tmp101_ = NULL;
								_tmp100_ = self->priv->emoticons;
								_tmp101_ = g_strconcat (_tmp100_, "ExcitedAlien.svg", NULL);
								_g_free0 (emoticon);
								emoticon = _tmp101_;
								break;
							}
							case ELEKTRO_SIM_COMPONENT_ZONE_SUBOPTIMAL:
							{
								const gchar* _tmp102_ = NULL;
								gchar* _tmp103_ = NULL;
								_tmp102_ = self->priv->emoticons;
								_tmp103_ = g_strconcat (_tmp102_, "FrustratedAlien.svg", NULL);
								_g_free0 (emoticon);
								emoticon = _tmp103_;
								break;
							}
							default:
							{
								gchar* _tmp104_ = NULL;
								g_print ("found no zone overactive");
								_tmp104_ = g_strdup ("");
								_g_free0 (emoticon);
								emoticon = _tmp104_;
								break;
							}
						}
					} else {
						gchar* _tmp105_ = NULL;
						_tmp105_ = g_strdup ("");
						_g_free0 (emoticon);
						emoticon = _tmp105_;
					}
				}
			}
		}
		_tmp106_ = emoticon;
		if (g_strcmp0 (_tmp106_, "") != 0) {
			RsvgHandle* handle = NULL;
			{
				RsvgHandle* _tmp107_ = NULL;
				const gchar* _tmp108_ = NULL;
				RsvgHandle* _tmp109_ = NULL;
				RsvgHandle* _tmp110_ = NULL;
				cairo_t* _tmp111_ = NULL;
				cairo_t* _tmp112_ = NULL;
				cairo_t* _tmp113_ = NULL;
				cairo_t* _tmp114_ = NULL;
				RsvgHandle* _tmp115_ = NULL;
				cairo_t* _tmp116_ = NULL;
				cairo_t* _tmp117_ = NULL;
				cairo_t* _tmp118_ = NULL;
				cairo_surface_t* _tmp119_ = NULL;
				gint _tmp120_ = 0;
				gint _tmp121_ = 0;
				cairo_t* _tmp122_ = NULL;
				cairo_t* _tmp123_ = NULL;
				cairo_t* _tmp124_ = NULL;
				_tmp108_ = emoticon;
				_tmp109_ = rsvg_handle_new_from_file (_tmp108_, &_inner_error_);
				_tmp107_ = _tmp109_;
				if (_inner_error_ != NULL) {
					if (_inner_error_->domain == RSVG_ERROR) {
						goto __catch0_rsvg_error;
					}
					goto __finally0;
				}
				_tmp110_ = _tmp107_;
				_tmp107_ = NULL;
				_g_object_unref0 (handle);
				handle = _tmp110_;
				_tmp111_ = cr;
				cairo_save (_tmp111_);
				_tmp112_ = cr;
				cairo_new_path (_tmp112_);
				_tmp113_ = emoticon_context;
				cairo_set_operator (_tmp113_, CAIRO_OPERATOR_OVER);
				_tmp114_ = emoticon_context;
				cairo_scale (_tmp114_, 1.5, 1.5);
				_tmp115_ = handle;
				_tmp116_ = emoticon_context;
				rsvg_handle_render_cairo (_tmp115_, _tmp116_);
				_tmp117_ = cr;
				_tmp118_ = emoticon_context;
				_tmp119_ = cairo_get_target (_tmp118_);
				_tmp120_ = x;
				_tmp121_ = y;
				cairo_set_source_surface (_tmp117_, _tmp119_, (gdouble) _tmp120_, (gdouble) _tmp121_);
				_tmp122_ = cr;
				cairo_paint (_tmp122_);
				_tmp123_ = cr;
				cairo_close_path (_tmp123_);
				_tmp124_ = cr;
				cairo_restore (_tmp124_);
				_g_object_unref0 (_tmp107_);
			}
			goto __finally0;
			__catch0_rsvg_error:
			{
				GError* e = NULL;
				FILE* _tmp125_ = NULL;
				const gchar* _tmp126_ = NULL;
				e = _inner_error_;
				_inner_error_ = NULL;
				_tmp125_ = stderr;
				_tmp126_ = emoticon;
				fprintf (_tmp125_, "can not open svg file with link %s \n", _tmp126_);
				_g_error_free0 (e);
			}
			__finally0:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (handle);
				_g_free0 (emoticon);
				_cairo_destroy0 (emoticon_context);
				_cairo_surface_destroy0 (temp_surface);
				_g_object_unref0 (zon);
				_g_object_unref0 (act);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			_g_object_unref0 (handle);
		}
	}
	_g_free0 (emoticon);
	_cairo_destroy0 (emoticon_context);
	_cairo_surface_destroy0 (temp_surface);
	_g_object_unref0 (zon);
	_g_object_unref0 (act);
}


static void elektro_sim_component_real_draw_image (ElektroSimComponent* self, cairo_t* cr) {
	g_return_if_fail (cr != NULL);
}


void elektro_sim_component_draw_image (ElektroSimComponent* self, cairo_t* cr) {
	g_return_if_fail (self != NULL);
	ELEKTRO_SIM_COMPONENT_GET_CLASS (self)->draw_image (self, cr);
}


static void elektro_sim_component_real_clear_counter (ElektroSimComponent* self) {
}


void elektro_sim_component_clear_counter (ElektroSimComponent* self) {
	g_return_if_fail (self != NULL);
	ELEKTRO_SIM_COMPONENT_GET_CLASS (self)->clear_counter (self);
}


static gchar* elektro_sim_component_real_get_netlist_line (ElektroSimComponent* self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	_tmp0_ = g_strdup ("");
	result = _tmp0_;
	return result;
}


gchar* elektro_sim_component_get_netlist_line (ElektroSimComponent* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return ELEKTRO_SIM_COMPONENT_GET_CLASS (self)->get_netlist_line (self);
}


static gdouble double_parse (const gchar* str) {
	gdouble result = 0.0;
	const gchar* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	g_return_val_if_fail (str != NULL, 0.0);
	_tmp0_ = str;
	_tmp1_ = g_ascii_strtod (_tmp0_, NULL);
	result = _tmp1_;
	return result;
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		GRegex* regex = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GRegex* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch1_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp6_ = regex;
		_tmp7_ = replacement;
		_tmp8_ = g_regex_replace_literal (_tmp6_, self, (gssize) (-1), 0, _tmp7_, 0, &_inner_error_);
		_tmp5_ = _tmp8_;
		if (_inner_error_ != NULL) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch1_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp9_ = _tmp5_;
		_tmp5_ = NULL;
		result = _tmp9_;
		_g_free0 (_tmp5_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally1;
	__catch1_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally1:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = needle;
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
	result = _tmp1_ != NULL;
	return result;
}


void elektro_sim_component_insert_simulation_data (ElektroSimComponent* self, const gchar* name, const gchar* val, gboolean add) {
	ElektroSimParameter* par = NULL;
	const gchar* _tmp0_ = NULL;
	ElektroSimParameter* _tmp1_ = NULL;
	ElektroSimParameter* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	g_return_if_fail (val != NULL);
	_tmp0_ = name;
	_tmp1_ = elektro_sim_component_get_parameter (self, _tmp0_);
	par = _tmp1_;
	_tmp2_ = par;
	if (_tmp2_ != NULL) {
		gboolean _tmp3_ = FALSE;
		const gchar* _tmp4_ = NULL;
		gboolean _tmp41_ = FALSE;
		_tmp4_ = name;
		if (g_strcmp0 (_tmp4_, "activity") != 0) {
			const gchar* _tmp5_ = NULL;
			_tmp5_ = name;
			_tmp3_ = g_strcmp0 (_tmp5_, "work_zone") != 0;
		} else {
			_tmp3_ = FALSE;
		}
		if (_tmp3_) {
			gdouble temp = 0.0;
			const gchar* _tmp6_ = NULL;
			gchar* _tmp7_ = NULL;
			gchar* _tmp8_ = NULL;
			gdouble _tmp9_ = 0.0;
			gdouble _tmp10_ = 0.0;
			ElektroSimParameter* _tmp11_ = NULL;
			gdouble _tmp12_ = 0.0;
			_tmp6_ = val;
			_tmp7_ = string_replace (_tmp6_, ",", ".");
			_tmp8_ = _tmp7_;
			_tmp9_ = double_parse (_tmp8_);
			_tmp10_ = _tmp9_;
			_g_free0 (_tmp8_);
			temp = _tmp10_;
			_tmp11_ = par;
			_tmp12_ = temp;
			elektro_sim_parameter_set_value (_tmp11_, _tmp12_);
		} else {
			const gchar* _tmp13_ = NULL;
			_tmp13_ = name;
			if (g_strcmp0 (_tmp13_, "activity") == 0) {
				const gchar* _tmp14_ = NULL;
				gboolean _tmp15_ = FALSE;
				_tmp14_ = val;
				_tmp15_ = string_contains (_tmp14_, "inactive");
				if (_tmp15_) {
					ElektroSimParameter* _tmp16_ = NULL;
					_tmp16_ = par;
					elektro_sim_parameter_set_value (_tmp16_, (gdouble) ELEKTRO_SIM_COMPONENT_ACTIVITY_INACTIVE);
				} else {
					const gchar* _tmp17_ = NULL;
					gboolean _tmp18_ = FALSE;
					_tmp17_ = val;
					_tmp18_ = string_contains (_tmp17_, "subactive");
					if (_tmp18_) {
						ElektroSimParameter* _tmp19_ = NULL;
						_tmp19_ = par;
						elektro_sim_parameter_set_value (_tmp19_, (gdouble) ELEKTRO_SIM_COMPONENT_ACTIVITY_SUBACTIVE);
					} else {
						const gchar* _tmp20_ = NULL;
						gboolean _tmp21_ = FALSE;
						_tmp20_ = val;
						_tmp21_ = string_contains (_tmp20_, "overactive");
						if (_tmp21_) {
							ElektroSimParameter* _tmp22_ = NULL;
							_tmp22_ = par;
							elektro_sim_parameter_set_value (_tmp22_, (gdouble) ELEKTRO_SIM_COMPONENT_ACTIVITY_OVERACTIVE);
						} else {
							const gchar* _tmp23_ = NULL;
							gboolean _tmp24_ = FALSE;
							_tmp23_ = val;
							_tmp24_ = string_contains (_tmp23_, "active");
							if (_tmp24_) {
								ElektroSimParameter* _tmp25_ = NULL;
								_tmp25_ = par;
								elektro_sim_parameter_set_value (_tmp25_, (gdouble) ELEKTRO_SIM_COMPONENT_ACTIVITY_ACTIVE);
							} else {
								ElektroSimParameter* _tmp26_ = NULL;
								_tmp26_ = par;
								elektro_sim_parameter_set_value (_tmp26_, (gdouble) ELEKTRO_SIM_COMPONENT_ACTIVITY_UNKNOWN);
							}
						}
					}
				}
			} else {
				const gchar* _tmp27_ = NULL;
				_tmp27_ = name;
				if (g_strcmp0 (_tmp27_, "work_zone") == 0) {
					const gchar* _tmp28_ = NULL;
					gboolean _tmp29_ = FALSE;
					_tmp28_ = val;
					_tmp29_ = string_contains (_tmp28_, "suboptimal");
					if (_tmp29_) {
						ElektroSimParameter* _tmp30_ = NULL;
						_tmp30_ = par;
						elektro_sim_parameter_set_value (_tmp30_, (gdouble) ELEKTRO_SIM_COMPONENT_ZONE_SUBOPTIMAL);
					} else {
						const gchar* _tmp31_ = NULL;
						gboolean _tmp32_ = FALSE;
						_tmp31_ = val;
						_tmp32_ = string_contains (_tmp31_, "optimal");
						if (_tmp32_) {
							ElektroSimParameter* _tmp33_ = NULL;
							_tmp33_ = par;
							elektro_sim_parameter_set_value (_tmp33_, (gdouble) ELEKTRO_SIM_COMPONENT_ZONE_OPTIMAL);
						} else {
							const gchar* _tmp34_ = NULL;
							gboolean _tmp35_ = FALSE;
							_tmp34_ = val;
							_tmp35_ = string_contains (_tmp34_, "outofrange");
							if (_tmp35_) {
								ElektroSimParameter* _tmp36_ = NULL;
								_tmp36_ = par;
								elektro_sim_parameter_set_value (_tmp36_, (gdouble) ELEKTRO_SIM_COMPONENT_ZONE_OUTOFRANGE);
							} else {
								const gchar* _tmp37_ = NULL;
								gboolean _tmp38_ = FALSE;
								_tmp37_ = val;
								_tmp38_ = string_contains (_tmp37_, "destructive");
								if (_tmp38_) {
									ElektroSimParameter* _tmp39_ = NULL;
									_tmp39_ = par;
									elektro_sim_parameter_set_value (_tmp39_, (gdouble) ELEKTRO_SIM_COMPONENT_ZONE_DESTRUCTIVE);
								} else {
									ElektroSimParameter* _tmp40_ = NULL;
									_tmp40_ = par;
									elektro_sim_parameter_set_value (_tmp40_, (gdouble) ELEKTRO_SIM_COMPONENT_ZONE_UNKNOWN);
								}
							}
						}
					}
				}
			}
		}
		_tmp41_ = add;
		if (_tmp41_) {
			ElektroSimParameter* _tmp42_ = NULL;
			ElektroSimParameter* _tmp43_ = NULL;
			gdouble _tmp44_ = 0.0;
			gdouble _tmp45_ = 0.0;
			_tmp42_ = par;
			_tmp43_ = par;
			_tmp44_ = elektro_sim_parameter_get_val (_tmp43_);
			_tmp45_ = _tmp44_;
			elektro_sim_parameter_add_value (_tmp42_, _tmp45_);
		}
	}
	_g_object_unref0 (par);
}


gint elektro_sim_component_get_height (ElektroSimComponent* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_height;
	result = _tmp0_;
	return result;
}


void elektro_sim_component_set_height (ElektroSimComponent* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_height = _tmp0_;
	g_object_notify ((GObject *) self, "height");
}


gint elektro_sim_component_get_width (ElektroSimComponent* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_width;
	result = _tmp0_;
	return result;
}


void elektro_sim_component_set_width (ElektroSimComponent* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_width = _tmp0_;
	g_object_notify ((GObject *) self, "width");
}


ElektroSimComponentComponentType elektro_sim_component_get_componentType (ElektroSimComponent* self) {
	ElektroSimComponentComponentType result;
	ElektroSimComponentComponentType _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_componentType;
	result = _tmp0_;
	return result;
}


void elektro_sim_component_set_componentType (ElektroSimComponent* self, ElektroSimComponentComponentType value) {
	ElektroSimComponentComponentType _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_componentType = _tmp0_;
	g_object_notify ((GObject *) self, "componentType");
}


ElektroSimComponentOrientation elektro_sim_component_get_orientation (ElektroSimComponent* self) {
	ElektroSimComponentOrientation result;
	ElektroSimComponentOrientation _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_orientation;
	result = _tmp0_;
	return result;
}


void elektro_sim_component_set_orientation (ElektroSimComponent* self, ElektroSimComponentOrientation value) {
	ElektroSimComponentOrientation _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_orientation = _tmp0_;
	g_object_notify ((GObject *) self, "orientation");
}


GtkBox* elektro_sim_component_get_grid (ElektroSimComponent* self) {
	GtkBox* result;
	GtkBox* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_grid;
	result = _tmp0_;
	return result;
}


void elektro_sim_component_set_grid (ElektroSimComponent* self, GtkBox* value) {
	GtkBox* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_grid);
	self->priv->_grid = _tmp1_;
	g_object_notify ((GObject *) self, "grid");
}


static void elektro_sim_component_class_init (ElektroSimComponentClass * klass) {
	elektro_sim_component_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ElektroSimComponentPrivate));
	ELEKTRO_SIM_COMPONENT_CLASS (klass)->clone = elektro_sim_component_real_clone;
	ELEKTRO_SIM_COMPONENT_CLASS (klass)->snap = elektro_sim_component_real_snap;
	ELEKTRO_SIM_COMPONENT_CLASS (klass)->draw_image = elektro_sim_component_real_draw_image;
	ELEKTRO_SIM_COMPONENT_CLASS (klass)->clear_counter = elektro_sim_component_real_clear_counter;
	ELEKTRO_SIM_COMPONENT_CLASS (klass)->get_netlist_line = elektro_sim_component_real_get_netlist_line;
	G_OBJECT_CLASS (klass)->get_property = _vala_elektro_sim_component_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_elektro_sim_component_set_property;
	G_OBJECT_CLASS (klass)->finalize = elektro_sim_component_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEKTRO_SIM_COMPONENT_HEIGHT, g_param_spec_int ("height", "height", "height", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEKTRO_SIM_COMPONENT_WIDTH, g_param_spec_int ("width", "width", "width", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE, g_param_spec_enum ("componentType", "componentType", "componentType", ELEKTRO_SIM_COMPONENT_TYPE_COMPONENT_TYPE, ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_COMPONENT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEKTRO_SIM_COMPONENT_ORIENTATION, g_param_spec_enum ("orientation", "orientation", "orientation", ELEKTRO_SIM_COMPONENT_TYPE_ORIENTATION, ELEKTRO_SIM_COMPONENT_ORIENTATION_NONE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEKTRO_SIM_COMPONENT_GRID, g_param_spec_object ("grid", "grid", "grid", GTK_TYPE_BOX, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_signal_new ("request_simulate", ELEKTRO_SIM_TYPE_COMPONENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("request_redraw", ELEKTRO_SIM_TYPE_COMPONENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("request_graph_redraw", ELEKTRO_SIM_TYPE_COMPONENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void elektro_sim_component_instance_init (ElektroSimComponent * self) {
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	self->priv = ELEKTRO_SIM_COMPONENT_GET_PRIVATE (self);
	self->priv->_height = 0;
	self->priv->_width = 0;
	self->priv->_componentType = ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE_COMPONENT;
	self->priv->_orientation = ELEKTRO_SIM_COMPONENT_ORIENTATION_NONE;
	_tmp0_ = gee_array_list_new (ELEKTRO_SIM_TYPE_PARAMETER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	self->parameters = _tmp0_;
	_tmp1_ = gee_array_list_new (ELEKTRO_SIM_TYPE_POINT, (GBoxedCopyFunc) elektro_sim_point_ref, elektro_sim_point_unref, NULL, NULL, NULL);
	self->connections = _tmp1_;
}


static void elektro_sim_component_finalize (GObject* obj) {
	ElektroSimComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEKTRO_SIM_TYPE_COMPONENT, ElektroSimComponent);
	_g_object_unref0 (self->parameters);
	_g_object_unref0 (self->connections);
	_g_object_unref0 (self->priv->_grid);
	_g_free0 (self->priv->emoticons);
	_g_object_unref0 (self->priv->label);
	_cairo_surface_destroy0 (self->image_surface);
	_cairo_destroy0 (self->image_context);
	_cairo_surface_destroy0 (self->emoticon_surface);
	_cairo_destroy0 (self->emoticon_context);
	G_OBJECT_CLASS (elektro_sim_component_parent_class)->finalize (obj);
}


GType elektro_sim_component_get_type (void) {
	static volatile gsize elektro_sim_component_type_id__volatile = 0;
	if (g_once_init_enter (&elektro_sim_component_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ElektroSimComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) elektro_sim_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ElektroSimComponent), 0, (GInstanceInitFunc) elektro_sim_component_instance_init, NULL };
		GType elektro_sim_component_type_id;
		elektro_sim_component_type_id = g_type_register_static (GTK_TYPE_LIST_BOX_ROW, "ElektroSimComponent", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&elektro_sim_component_type_id__volatile, elektro_sim_component_type_id);
	}
	return elektro_sim_component_type_id__volatile;
}


static void _vala_elektro_sim_component_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ElektroSimComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ELEKTRO_SIM_TYPE_COMPONENT, ElektroSimComponent);
	switch (property_id) {
		case ELEKTRO_SIM_COMPONENT_HEIGHT:
		g_value_set_int (value, elektro_sim_component_get_height (self));
		break;
		case ELEKTRO_SIM_COMPONENT_WIDTH:
		g_value_set_int (value, elektro_sim_component_get_width (self));
		break;
		case ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE:
		g_value_set_enum (value, elektro_sim_component_get_componentType (self));
		break;
		case ELEKTRO_SIM_COMPONENT_ORIENTATION:
		g_value_set_enum (value, elektro_sim_component_get_orientation (self));
		break;
		case ELEKTRO_SIM_COMPONENT_GRID:
		g_value_set_object (value, elektro_sim_component_get_grid (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_elektro_sim_component_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ElektroSimComponent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ELEKTRO_SIM_TYPE_COMPONENT, ElektroSimComponent);
	switch (property_id) {
		case ELEKTRO_SIM_COMPONENT_HEIGHT:
		elektro_sim_component_set_height (self, g_value_get_int (value));
		break;
		case ELEKTRO_SIM_COMPONENT_WIDTH:
		elektro_sim_component_set_width (self, g_value_get_int (value));
		break;
		case ELEKTRO_SIM_COMPONENT_COMPONENT_TYPE:
		elektro_sim_component_set_componentType (self, g_value_get_enum (value));
		break;
		case ELEKTRO_SIM_COMPONENT_ORIENTATION:
		elektro_sim_component_set_orientation (self, g_value_get_enum (value));
		break;
		case ELEKTRO_SIM_COMPONENT_GRID:
		elektro_sim_component_set_grid (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



