/* elektronsim.c generated by valac 0.22.1, the Vala compiler
 * generated from elektronsim.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_MAIN_WINDOW (main_window_get_type ())
#define MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_WINDOW, MainWindow))
#define MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_WINDOW, MainWindowClass))
#define IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_WINDOW))
#define IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_WINDOW))
#define MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_WINDOW, MainWindowClass))

typedef struct _MainWindow MainWindow;
typedef struct _MainWindowClass MainWindowClass;
typedef struct _MainWindowPrivate MainWindowPrivate;

#define TYPE_SIMULATION_AREA (simulation_area_get_type ())
#define SIMULATION_AREA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SIMULATION_AREA, SimulationArea))
#define SIMULATION_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SIMULATION_AREA, SimulationAreaClass))
#define IS_SIMULATION_AREA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SIMULATION_AREA))
#define IS_SIMULATION_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SIMULATION_AREA))
#define SIMULATION_AREA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SIMULATION_AREA, SimulationAreaClass))

typedef struct _SimulationArea SimulationArea;
typedef struct _SimulationAreaClass SimulationAreaClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_COMPONENT (component_get_type ())
#define COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMPONENT, Component))
#define COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMPONENT, ComponentClass))
#define IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMPONENT))
#define IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMPONENT))
#define COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMPONENT, ComponentClass))

typedef struct _Component Component;
typedef struct _ComponentClass ComponentClass;

struct _MainWindow {
	GtkWindow parent_instance;
	MainWindowPrivate * priv;
};

struct _MainWindowClass {
	GtkWindowClass parent_class;
};

struct _MainWindowPrivate {
	GtkListBox* list;
	GtkGrid* grid;
	SimulationArea* simArea;
	GtkBox* box;
};


static gpointer main_window_parent_class = NULL;

GType main_window_get_type (void) G_GNUC_CONST;
GType simulation_area_get_type (void) G_GNUC_CONST;
#define MAIN_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN_WINDOW, MainWindowPrivate))
enum  {
	MAIN_WINDOW_DUMMY_PROPERTY
};
gint main_window_main (gchar** args, int args_length1);
MainWindow* main_window_new (void);
MainWindow* main_window_construct (GType object_type);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void main_window_setup_layout (MainWindow* self);
GType component_get_type (void) G_GNUC_CONST;
Component* component_new (const gchar* name, gint height, gint with);
Component* component_construct (GType object_type, const gchar* name, gint height, gint with);
SimulationArea* simulation_area_new (void);
SimulationArea* simulation_area_construct (GType object_type);
void main_window_clear_history (MainWindow* self);
void main_window_messagebox_show (MainWindow* self, const gchar* title, const gchar* message);
static void main_window_finalize (GObject* obj);


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


gint main_window_main (gchar** args, int args_length1) {
	gint result = 0;
	MainWindow* window = NULL;
	MainWindow* _tmp0_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = main_window_new ();
	g_object_ref_sink (_tmp0_);
	window = _tmp0_;
	g_signal_connect ((GtkWidget*) window, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_widget_show_all ((GtkWidget*) window);
	gtk_window_set_decorated ((GtkWindow*) window, TRUE);
	gtk_main ();
	result = 0;
	_g_object_unref0 (window);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return main_window_main (argv, argc);
}


MainWindow* main_window_construct (GType object_type) {
	MainWindow * self = NULL;
	GtkBox* _tmp0_ = NULL;
	Component* test = NULL;
	Component* _tmp1_ = NULL;
	GtkListBox* _tmp2_ = NULL;
	Component* _tmp3_ = NULL;
	Component* _tmp4_ = NULL;
	GtkListBox* _tmp5_ = NULL;
	Component* _tmp6_ = NULL;
	self = (MainWindow*) g_object_new (object_type, NULL);
	gtk_window_set_title ((GtkWindow*) self, "ElektronSim");
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 10);
	gtk_window_maximize ((GtkWindow*) self);
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	main_window_setup_layout (self);
	_tmp0_ = self->priv->box;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp0_);
	_tmp1_ = component_new ("testing this", 200, 200);
	g_object_ref_sink (_tmp1_);
	test = _tmp1_;
	_tmp2_ = self->priv->list;
	_tmp3_ = test;
	gtk_list_box_prepend (_tmp2_, (GtkWidget*) _tmp3_);
	_tmp4_ = component_new ("testing 2", 200, 200);
	g_object_ref_sink (_tmp4_);
	_g_object_unref0 (test);
	test = _tmp4_;
	_tmp5_ = self->priv->list;
	_tmp6_ = test;
	gtk_list_box_prepend (_tmp5_, (GtkWidget*) _tmp6_);
	gtk_widget_show ((GtkWidget*) self);
	_g_object_unref0 (test);
	return self;
}


MainWindow* main_window_new (void) {
	return main_window_construct (TYPE_MAIN_WINDOW);
}


static void main_window_setup_layout (MainWindow* self) {
	GtkListBox* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
	SimulationArea* _tmp3_ = NULL;
	GtkBox* _tmp4_ = NULL;
	GtkListBox* _tmp5_ = NULL;
	GtkBox* _tmp6_ = NULL;
	SimulationArea* _tmp7_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkListBox*) gtk_list_box_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->list);
	self->priv->list = _tmp0_;
	_tmp1_ = self->priv->list;
	gtk_list_box_set_selection_mode (_tmp1_, GTK_SELECTION_SINGLE);
	_tmp2_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 10);
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->box);
	self->priv->box = _tmp2_;
	_tmp3_ = simulation_area_new ();
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->simArea);
	self->priv->simArea = _tmp3_;
	_tmp4_ = self->priv->box;
	_tmp5_ = self->priv->list;
	gtk_box_pack_start (_tmp4_, (GtkWidget*) _tmp5_, FALSE, TRUE, (guint) 0);
	_tmp6_ = self->priv->box;
	_tmp7_ = self->priv->simArea;
	gtk_box_pack_start (_tmp6_, (GtkWidget*) _tmp7_, TRUE, TRUE, (guint) 0);
}


void main_window_clear_history (MainWindow* self) {
	g_return_if_fail (self != NULL);
}


void main_window_messagebox_show (MainWindow* self, const gchar* title, const gchar* message) {
	GtkMessageDialog* dialog = NULL;
	const gchar* _tmp0_ = NULL;
	GtkMessageDialog* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (title != NULL);
	g_return_if_fail (message != NULL);
	_tmp0_ = message;
	_tmp1_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_INFO, GTK_BUTTONS_OK, _tmp0_);
	g_object_ref_sink (_tmp1_);
	dialog = _tmp1_;
	_tmp2_ = title;
	gtk_window_set_title ((GtkWindow*) dialog, _tmp2_);
	gtk_dialog_run ((GtkDialog*) dialog);
	gtk_widget_destroy ((GtkWidget*) dialog);
	_g_object_unref0 (dialog);
}


static void main_window_class_init (MainWindowClass * klass) {
	main_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MainWindowPrivate));
	G_OBJECT_CLASS (klass)->finalize = main_window_finalize;
}


static void main_window_instance_init (MainWindow * self) {
	self->priv = MAIN_WINDOW_GET_PRIVATE (self);
}


static void main_window_finalize (GObject* obj) {
	MainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN_WINDOW, MainWindow);
	_g_object_unref0 (self->priv->list);
	_g_object_unref0 (self->priv->grid);
	_g_object_unref0 (self->priv->simArea);
	_g_object_unref0 (self->priv->box);
	G_OBJECT_CLASS (main_window_parent_class)->finalize (obj);
}


GType main_window_get_type (void) {
	static volatile gsize main_window_type_id__volatile = 0;
	if (g_once_init_enter (&main_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MainWindow), 0, (GInstanceInitFunc) main_window_instance_init, NULL };
		GType main_window_type_id;
		main_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "MainWindow", &g_define_type_info, 0);
		g_once_init_leave (&main_window_type_id__volatile, main_window_type_id);
	}
	return main_window_type_id__volatile;
}



