/* elektrosim.c generated by valac 0.22.1, the Vala compiler
 * generated from elektrosim.vala, do not modify */

/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * main.c
 * Copyright (C) 2014 Steven Vanden Branden <StevenVandenBrandenStift@gmail.com>
 * 
 * ElektroSim is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ElektroSim is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define TYPE_MAIN_WINDOW (main_window_get_type ())
#define MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_WINDOW, MainWindow))
#define MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_WINDOW, MainWindowClass))
#define IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_WINDOW))
#define IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_WINDOW))
#define MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_WINDOW, MainWindowClass))

typedef struct _MainWindow MainWindow;
typedef struct _MainWindowClass MainWindowClass;
typedef struct _MainWindowPrivate MainWindowPrivate;

#define TYPE_SIMULATION_AREA (simulation_area_get_type ())
#define SIMULATION_AREA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SIMULATION_AREA, SimulationArea))
#define SIMULATION_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SIMULATION_AREA, SimulationAreaClass))
#define IS_SIMULATION_AREA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SIMULATION_AREA))
#define IS_SIMULATION_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SIMULATION_AREA))
#define SIMULATION_AREA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SIMULATION_AREA, SimulationAreaClass))

typedef struct _SimulationArea SimulationArea;
typedef struct _SimulationAreaClass SimulationAreaClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_COMPONENT (component_get_type ())
#define COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMPONENT, Component))
#define COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMPONENT, ComponentClass))
#define IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMPONENT))
#define IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMPONENT))
#define COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMPONENT, ComponentClass))

typedef struct _Component Component;
typedef struct _ComponentClass ComponentClass;

#define TYPE_RESISTOR (resistor_get_type ())
#define RESISTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RESISTOR, Resistor))
#define RESISTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RESISTOR, ResistorClass))
#define IS_RESISTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RESISTOR))
#define IS_RESISTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RESISTOR))
#define RESISTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RESISTOR, ResistorClass))

typedef struct _Resistor Resistor;
typedef struct _ResistorClass ResistorClass;

#define TYPE_GROUND (ground_get_type ())
#define GROUND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GROUND, Ground))
#define GROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GROUND, GroundClass))
#define IS_GROUND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GROUND))
#define IS_GROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GROUND))
#define GROUND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GROUND, GroundClass))

typedef struct _Ground Ground;
typedef struct _GroundClass GroundClass;

#define TYPE_POWER_SOURCE (power_source_get_type ())
#define POWER_SOURCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POWER_SOURCE, PowerSource))
#define POWER_SOURCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POWER_SOURCE, PowerSourceClass))
#define IS_POWER_SOURCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POWER_SOURCE))
#define IS_POWER_SOURCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POWER_SOURCE))
#define POWER_SOURCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POWER_SOURCE, PowerSourceClass))

typedef struct _PowerSource PowerSource;
typedef struct _PowerSourceClass PowerSourceClass;

struct _MainWindow {
	GtkWindow parent_instance;
	MainWindowPrivate * priv;
};

struct _MainWindowClass {
	GtkWindowClass parent_class;
};

struct _MainWindowPrivate {
	GtkListBox* list;
	SimulationArea* simArea;
};


static gpointer main_window_parent_class = NULL;

GType main_window_get_type (void) G_GNUC_CONST;
GType simulation_area_get_type (void) G_GNUC_CONST;
#define MAIN_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN_WINDOW, MainWindowPrivate))
enum  {
	MAIN_WINDOW_DUMMY_PROPERTY
};
gint main_window_main (gchar** args, int args_length1);
MainWindow* main_window_new (void);
MainWindow* main_window_construct (GType object_type);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void main_window_setup_layout (MainWindow* self);
GType component_get_type (void) G_GNUC_CONST;
GType resistor_get_type (void) G_GNUC_CONST;
Resistor* resistor_new (gfloat restistance);
Resistor* resistor_construct (GType object_type, gfloat restistance);
GType ground_get_type (void) G_GNUC_CONST;
Ground* ground_new (void);
Ground* ground_construct (GType object_type);
GType power_source_get_type (void) G_GNUC_CONST;
PowerSource* power_source_new (gfloat voltage);
PowerSource* power_source_construct (GType object_type, gfloat voltage);
SimulationArea* simulation_area_new (GtkListBox* list);
SimulationArea* simulation_area_construct (GType object_type, GtkListBox* list);
void simulation_area_simulate (SimulationArea* self);
static void _simulation_area_simulate_gtk_button_clicked (GtkButton* _sender, gpointer self);
void main_window_messagebox_show (MainWindow* self, const gchar* title, const gchar* message);
static void main_window_finalize (GObject* obj);


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


gint main_window_main (gchar** args, int args_length1) {
	gint result = 0;
	MainWindow* window = NULL;
	MainWindow* _tmp0_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = main_window_new ();
	g_object_ref_sink (_tmp0_);
	window = _tmp0_;
	g_signal_connect ((GtkWidget*) window, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_widget_show_all ((GtkWidget*) window);
	gtk_window_set_decorated ((GtkWindow*) window, TRUE);
	gtk_main ();
	result = 0;
	_g_object_unref0 (window);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return main_window_main (argv, argc);
}


MainWindow* main_window_construct (GType object_type) {
	MainWindow * self = NULL;
	Resistor* test = NULL;
	Resistor* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	Ground* test2 = NULL;
	Ground* _tmp2_ = NULL;
	GtkListBox* _tmp3_ = NULL;
	PowerSource* powerSource = NULL;
	PowerSource* _tmp4_ = NULL;
	GtkListBox* _tmp5_ = NULL;
	self = (MainWindow*) g_object_new (object_type, NULL);
	gtk_window_set_title ((GtkWindow*) self, "ElektronSim");
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 10);
	gtk_window_maximize ((GtkWindow*) self);
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	main_window_setup_layout (self);
	_tmp0_ = resistor_new ((gfloat) 3);
	g_object_ref_sink (_tmp0_);
	test = _tmp0_;
	_tmp1_ = self->priv->list;
	gtk_list_box_prepend (_tmp1_, (GtkWidget*) test);
	_tmp2_ = ground_new ();
	g_object_ref_sink (_tmp2_);
	test2 = _tmp2_;
	_tmp3_ = self->priv->list;
	gtk_container_add ((GtkContainer*) _tmp3_, (GtkWidget*) test2);
	_tmp4_ = power_source_new ((gfloat) 5);
	g_object_ref_sink (_tmp4_);
	powerSource = _tmp4_;
	_tmp5_ = self->priv->list;
	gtk_container_add ((GtkContainer*) _tmp5_, (GtkWidget*) powerSource);
	gtk_widget_show ((GtkWidget*) self);
	_g_object_unref0 (powerSource);
	_g_object_unref0 (test2);
	_g_object_unref0 (test);
	return self;
}


MainWindow* main_window_new (void) {
	return main_window_construct (TYPE_MAIN_WINDOW);
}


static void _simulation_area_simulate_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	simulation_area_simulate (self);
}


static void main_window_setup_layout (MainWindow* self) {
	GtkHeaderBar* headerBar = NULL;
	GtkHeaderBar* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	GtkListBox* _tmp2_ = NULL;
	GtkButton* _tmp3_ = NULL;
	GtkButton* _tmp4_ = NULL;
	GtkListBox* _tmp5_ = NULL;
	SimulationArea* _tmp6_ = NULL;
	GtkButton* sim_button = NULL;
	GtkButton* _tmp7_ = NULL;
	SimulationArea* _tmp8_ = NULL;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp9_ = NULL;
	GtkListBox* _tmp10_ = NULL;
	SimulationArea* _tmp11_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkHeaderBar*) gtk_header_bar_new ();
	g_object_ref_sink (_tmp0_);
	headerBar = _tmp0_;
	_tmp1_ = (GtkListBox*) gtk_list_box_new ();
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->list);
	self->priv->list = _tmp1_;
	_tmp2_ = self->priv->list;
	gtk_list_box_set_selection_mode (_tmp2_, GTK_SELECTION_SINGLE);
	gtk_widget_set_halign ((GtkWidget*) headerBar, GTK_ALIGN_FILL);
	_tmp3_ = (GtkButton*) gtk_button_new_with_label ("Design");
	g_object_ref_sink (_tmp3_);
	_tmp4_ = _tmp3_;
	gtk_container_add ((GtkContainer*) headerBar, (GtkWidget*) _tmp4_);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = self->priv->list;
	_tmp6_ = simulation_area_new (_tmp5_);
	g_object_ref_sink (_tmp6_);
	_g_object_unref0 (self->priv->simArea);
	self->priv->simArea = _tmp6_;
	_tmp7_ = (GtkButton*) gtk_button_new_with_label ("Simulation");
	g_object_ref_sink (_tmp7_);
	sim_button = _tmp7_;
	_tmp8_ = self->priv->simArea;
	g_signal_connect_object (sim_button, "clicked", (GCallback) _simulation_area_simulate_gtk_button_clicked, _tmp8_, 0);
	gtk_container_add ((GtkContainer*) headerBar, (GtkWidget*) sim_button);
	_tmp9_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp9_);
	grid = _tmp9_;
	_tmp10_ = self->priv->list;
	gtk_container_add ((GtkContainer*) grid, (GtkWidget*) _tmp10_);
	_tmp11_ = self->priv->simArea;
	gtk_container_add ((GtkContainer*) grid, (GtkWidget*) _tmp11_);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) grid);
	gtk_window_set_titlebar ((GtkWindow*) self, (GtkWidget*) headerBar);
	_g_object_unref0 (grid);
	_g_object_unref0 (sim_button);
	_g_object_unref0 (headerBar);
}


void main_window_messagebox_show (MainWindow* self, const gchar* title, const gchar* message) {
	GtkMessageDialog* dialog = NULL;
	const gchar* _tmp0_ = NULL;
	GtkMessageDialog* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (title != NULL);
	g_return_if_fail (message != NULL);
	_tmp0_ = message;
	_tmp1_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_INFO, GTK_BUTTONS_OK, _tmp0_);
	g_object_ref_sink (_tmp1_);
	dialog = _tmp1_;
	_tmp2_ = title;
	gtk_window_set_title ((GtkWindow*) dialog, _tmp2_);
	gtk_dialog_run ((GtkDialog*) dialog);
	gtk_widget_destroy ((GtkWidget*) dialog);
	_g_object_unref0 (dialog);
}


static void main_window_class_init (MainWindowClass * klass) {
	main_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MainWindowPrivate));
	G_OBJECT_CLASS (klass)->finalize = main_window_finalize;
}


static void main_window_instance_init (MainWindow * self) {
	self->priv = MAIN_WINDOW_GET_PRIVATE (self);
}


static void main_window_finalize (GObject* obj) {
	MainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN_WINDOW, MainWindow);
	_g_object_unref0 (self->priv->list);
	_g_object_unref0 (self->priv->simArea);
	G_OBJECT_CLASS (main_window_parent_class)->finalize (obj);
}


GType main_window_get_type (void) {
	static volatile gsize main_window_type_id__volatile = 0;
	if (g_once_init_enter (&main_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MainWindow), 0, (GInstanceInitFunc) main_window_instance_init, NULL };
		GType main_window_type_id;
		main_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "MainWindow", &g_define_type_info, 0);
		g_once_init_leave (&main_window_type_id__volatile, main_window_type_id);
	}
	return main_window_type_id__volatile;
}



