/* ground.c generated by valac 0.22.1, the Vala compiler
 * generated from ground.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * ground.vala
 * Copyright (C) 2014 Steven Vanden Branden <Stevenvandenbrandenstift@gmail.com>
 *
 * ElektroSim is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ElektroSim is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <cairo.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define TYPE_COMPONENT (component_get_type ())
#define COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMPONENT, Component))
#define COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMPONENT, ComponentClass))
#define IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMPONENT))
#define IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMPONENT))
#define COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMPONENT, ComponentClass))

typedef struct _Component Component;
typedef struct _ComponentClass ComponentClass;
typedef struct _ComponentPrivate ComponentPrivate;

#define TYPE_POINT (point_get_type ())
#define POINT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POINT, Point))
#define POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POINT, PointClass))
#define IS_POINT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POINT))
#define IS_POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POINT))
#define POINT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POINT, PointClass))

typedef struct _Point Point;
typedef struct _PointClass PointClass;

#define TYPE_GROUND (ground_get_type ())
#define GROUND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GROUND, Ground))
#define GROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GROUND, GroundClass))
#define IS_GROUND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GROUND))
#define IS_GROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GROUND))
#define GROUND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GROUND, GroundClass))

typedef struct _Ground Ground;
typedef struct _GroundClass GroundClass;
typedef struct _GroundPrivate GroundPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _Component {
	GtkListBoxRow parent_instance;
	ComponentPrivate * priv;
	GList* connections;
};

struct _ComponentClass {
	GtkListBoxRowClass parent_class;
	Component* (*clone) (Component* self, Component* component, gint x, gint y);
	gint (*snap) (Component* self, GList* list, gint range, gint netAmount);
	void (*draw_symbol) (Component* self, cairo_t* context);
	gchar* (*getNetlistLine) (Component* self);
	void (*insertSimulationData) (Component* self, const gchar* data);
};

struct _Ground {
	Component parent_instance;
	GroundPrivate * priv;
};

struct _GroundClass {
	ComponentClass parent_class;
};


static gpointer ground_parent_class = NULL;

GType component_get_type (void) G_GNUC_CONST;
gpointer point_ref (gpointer instance);
void point_unref (gpointer instance);
GParamSpec* param_spec_point (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_point (GValue* value, gpointer v_object);
void value_take_point (GValue* value, gpointer v_object);
gpointer value_get_point (const GValue* value);
GType point_get_type (void) G_GNUC_CONST;
GType ground_get_type (void) G_GNUC_CONST;
enum  {
	GROUND_DUMMY_PROPERTY
};
Ground* ground_new (void);
Ground* ground_construct (GType object_type);
Component* component_construct (GType object_type, const gchar* name);
void component_set_width (Component* self, gint value);
static void ground_real_draw_symbol (Component* base, cairo_t* context);
gint point_get_x (Point* self);
gint point_get_y (Point* self);
gint component_get_width (Component* self);
static Component* ground_real_clone (Component* base, Component* component, gint x, gint y);
Point* point_new_with_net (gint x, gint y, gint net);
Point* point_construct_with_net (GType object_type, gint x, gint y, gint net);
static void ground_real_insertSimulationData (Component* base, const gchar* data);
static gint ground_real_snap (Component* base, GList* list, gint range, gint netAmount);
gboolean point_pointNearby (Point* self, gint range, GList* items);
gint point_checkNetName (Point* self, gint netCount);
static gchar* ground_real_getNetlistLine (Component* base);
const gchar* component_get_name (Component* self);
gint point_get_net (Point* self);


Ground* ground_construct (GType object_type) {
	Ground * self = NULL;
	self = (Ground*) component_construct (object_type, "ground");
	component_set_width ((Component*) self, 100);
	return self;
}


Ground* ground_new (void) {
	return ground_construct (TYPE_GROUND);
}


static void ground_real_draw_symbol (Component* base, cairo_t* context) {
	Ground * self;
	cairo_t* _tmp0_ = NULL;
	cairo_t* _tmp1_ = NULL;
	cairo_t* _tmp2_ = NULL;
	GList* _tmp3_ = NULL;
	gconstpointer _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	GList* _tmp7_ = NULL;
	gconstpointer _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	gint _tmp12_ = 0;
	cairo_t* _tmp13_ = NULL;
	cairo_t* _tmp14_ = NULL;
	cairo_t* _tmp15_ = NULL;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
	cairo_t* _tmp18_ = NULL;
	cairo_t* _tmp19_ = NULL;
	cairo_t* _tmp20_ = NULL;
	cairo_t* _tmp21_ = NULL;
	self = (Ground*) base;
	g_return_if_fail (context != NULL);
	_tmp0_ = context;
	cairo_new_path (_tmp0_);
	_tmp1_ = context;
	cairo_set_source_rgb (_tmp1_, (gdouble) 3, (gdouble) 3, (gdouble) 3);
	_tmp2_ = context;
	_tmp3_ = ((Component*) self)->connections;
	_tmp4_ = g_list_nth_data (_tmp3_, (guint) 0);
	_tmp5_ = point_get_x ((Point*) _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = ((Component*) self)->connections;
	_tmp8_ = g_list_nth_data (_tmp7_, (guint) 0);
	_tmp9_ = point_get_y ((Point*) _tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = component_get_width ((Component*) self);
	_tmp12_ = _tmp11_;
	cairo_rectangle (_tmp2_, (gdouble) _tmp6_, (gdouble) _tmp10_, (gdouble) (-_tmp12_), (gdouble) 2);
	_tmp13_ = context;
	cairo_select_font_face (_tmp13_, "Adventure", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_BOLD);
	_tmp14_ = context;
	cairo_set_font_size (_tmp14_, (gdouble) 20);
	_tmp15_ = context;
	_tmp16_ = component_get_width ((Component*) self);
	_tmp17_ = _tmp16_;
	cairo_rel_move_to (_tmp15_, (gdouble) (-_tmp17_), (gdouble) 0);
	_tmp18_ = context;
	cairo_text_path (_tmp18_, "Ground");
	_tmp19_ = context;
	cairo_fill (_tmp19_);
	_tmp20_ = context;
	cairo_stroke (_tmp20_);
	_tmp21_ = context;
	cairo_close_path (_tmp21_);
}


static Component* ground_real_clone (Component* base, Component* component, gint x, gint y) {
	Ground * self;
	Component* result = NULL;
	Ground* newc = NULL;
	Ground* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	Point* _tmp3_ = NULL;
	self = (Ground*) base;
	g_return_val_if_fail (component != NULL, NULL);
	_tmp0_ = ground_new ();
	g_object_ref_sink (_tmp0_);
	newc = _tmp0_;
	_tmp1_ = x;
	_tmp2_ = y;
	_tmp3_ = point_new_with_net (_tmp1_, _tmp2_, 0);
	((Component*) newc)->connections = g_list_append (((Component*) newc)->connections, _tmp3_);
	result = (Component*) newc;
	return result;
}


static void ground_real_insertSimulationData (Component* base, const gchar* data) {
	Ground * self;
	self = (Ground*) base;
	g_return_if_fail (data != NULL);
}


static gint ground_real_snap (Component* base, GList* list, gint range, gint netAmount) {
	Ground * self;
	gint result = 0;
	GList* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GList* _tmp3_ = NULL;
	gint newNetCount = 0;
	GList* _tmp4_ = NULL;
	gconstpointer _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	self = (Ground*) base;
	_tmp0_ = ((Component*) self)->connections;
	_tmp1_ = g_list_nth_data (_tmp0_, (guint) 0);
	_tmp2_ = range;
	_tmp3_ = list;
	point_pointNearby ((Point*) _tmp1_, _tmp2_, _tmp3_);
	_tmp4_ = ((Component*) self)->connections;
	_tmp5_ = g_list_nth_data (_tmp4_, (guint) 0);
	_tmp6_ = netAmount;
	_tmp7_ = point_checkNetName ((Point*) _tmp5_, _tmp6_);
	newNetCount = _tmp7_;
	result = newNetCount;
	return result;
}


static gchar* ground_real_getNetlistLine (Component* base) {
	Ground * self;
	gchar* result = NULL;
	gchar* line = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GList* _tmp4_ = NULL;
	gconstpointer _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	self = (Ground*) base;
	_tmp0_ = component_get_name ((Component*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strconcat (_tmp1_, " ", NULL);
	_tmp3_ = _tmp2_;
	_tmp4_ = ((Component*) self)->connections;
	_tmp5_ = g_list_nth_data (_tmp4_, (guint) 0);
	_tmp6_ = point_get_net ((Point*) _tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strdup_printf ("%i", _tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strconcat (_tmp3_, _tmp9_, NULL);
	_g_free0 (line);
	line = _tmp10_;
	_g_free0 (_tmp9_);
	_g_free0 (_tmp3_);
	_tmp11_ = g_strdup ("");
	result = _tmp11_;
	_g_free0 (line);
	return result;
}


static void ground_class_init (GroundClass * klass) {
	ground_parent_class = g_type_class_peek_parent (klass);
	COMPONENT_CLASS (klass)->draw_symbol = ground_real_draw_symbol;
	COMPONENT_CLASS (klass)->clone = ground_real_clone;
	COMPONENT_CLASS (klass)->insertSimulationData = ground_real_insertSimulationData;
	COMPONENT_CLASS (klass)->snap = ground_real_snap;
	COMPONENT_CLASS (klass)->getNetlistLine = ground_real_getNetlistLine;
}


static void ground_instance_init (Ground * self) {
}


GType ground_get_type (void) {
	static volatile gsize ground_type_id__volatile = 0;
	if (g_once_init_enter (&ground_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GroundClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ground_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Ground), 0, (GInstanceInitFunc) ground_instance_init, NULL };
		GType ground_type_id;
		ground_type_id = g_type_register_static (TYPE_COMPONENT, "Ground", &g_define_type_info, 0);
		g_once_init_leave (&ground_type_id__volatile, ground_type_id);
	}
	return ground_type_id__volatile;
}



