/* netlist-generator.c generated by valac 0.22.1, the Vala compiler
 * generated from netlist-generator.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * netlist-generator.vala
 * Copyright (C) 2014 Steven Vanden Branden <StevenVandenbrandenstift@gmail.com>
 *
 * ElektroSim is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ElektroSim is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>


#define TYPE_NG_SPICE_SIMULATOR (ng_spice_simulator_get_type ())
#define NG_SPICE_SIMULATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NG_SPICE_SIMULATOR, NGSpiceSimulator))
#define NG_SPICE_SIMULATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_NG_SPICE_SIMULATOR, NGSpiceSimulatorClass))
#define IS_NG_SPICE_SIMULATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NG_SPICE_SIMULATOR))
#define IS_NG_SPICE_SIMULATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_NG_SPICE_SIMULATOR))
#define NG_SPICE_SIMULATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_NG_SPICE_SIMULATOR, NGSpiceSimulatorClass))

typedef struct _NGSpiceSimulator NGSpiceSimulator;
typedef struct _NGSpiceSimulatorClass NGSpiceSimulatorClass;
typedef struct _NGSpiceSimulatorPrivate NGSpiceSimulatorPrivate;
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_io_channel_unref0(var) ((var == NULL) ? NULL : (var = (g_io_channel_unref (var), NULL)))

#define TYPE_COMPONENT (component_get_type ())
#define COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMPONENT, Component))
#define COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMPONENT, ComponentClass))
#define IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMPONENT))
#define IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMPONENT))
#define COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMPONENT, ComponentClass))

typedef struct _Component Component;
typedef struct _ComponentClass ComponentClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _NGSpiceSimulator {
	GObject parent_instance;
	NGSpiceSimulatorPrivate * priv;
};

struct _NGSpiceSimulatorClass {
	GObjectClass parent_class;
};

struct _NGSpiceSimulatorPrivate {
	gint standard_input;
	gint standard_output;
	gint standard_error;
	FILE* input;
	gchar* builder;
};


static gpointer ng_spice_simulator_parent_class = NULL;

GType ng_spice_simulator_get_type (void) G_GNUC_CONST;
#define NG_SPICE_SIMULATOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_NG_SPICE_SIMULATOR, NGSpiceSimulatorPrivate))
enum  {
	NG_SPICE_SIMULATOR_DUMMY_PROPERTY
};
NGSpiceSimulator* ng_spice_simulator_new (void);
NGSpiceSimulator* ng_spice_simulator_construct (GType object_type);
static gboolean ___lambda2_ (NGSpiceSimulator* self, GIOChannel* channel, GIOCondition condition);
static gboolean ng_spice_simulator_process_line (NGSpiceSimulator* self, GIOChannel* channel, GIOCondition condition, const gchar* stream_name);
static gboolean ____lambda2__gio_func (GIOChannel* source, GIOCondition condition, gpointer self);
static gboolean ___lambda3_ (NGSpiceSimulator* self, GIOChannel* channel, GIOCondition condition);
static gboolean ____lambda3__gio_func (GIOChannel* source, GIOCondition condition, gpointer self);
GType component_get_type (void) G_GNUC_CONST;
gchar* ng_spice_simulator_generate_file (NGSpiceSimulator* self, GList* components);
gchar* component_getNetlistLine (Component* self);
static gboolean ng_spice_simulator_send_to_ngspice (NGSpiceSimulator* self, const gchar* command);
void ng_spice_simulator_run_simulation (NGSpiceSimulator* self, GList* components);
const gchar* component_get_name (Component* self);
void component_insertSimulationData (Component* self, const gchar* data);
static void ng_spice_simulator_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static gboolean ___lambda2_ (NGSpiceSimulator* self, GIOChannel* channel, GIOCondition condition) {
	gboolean result = FALSE;
	GIOChannel* _tmp0_ = NULL;
	GIOCondition _tmp1_ = 0;
	gboolean _tmp2_ = FALSE;
	g_return_val_if_fail (channel != NULL, FALSE);
	_tmp0_ = channel;
	_tmp1_ = condition;
	_tmp2_ = ng_spice_simulator_process_line (self, _tmp0_, _tmp1_, "stdout");
	result = _tmp2_;
	return result;
}


static gboolean ____lambda2__gio_func (GIOChannel* source, GIOCondition condition, gpointer self) {
	gboolean result;
	result = ___lambda2_ (self, source, condition);
	return result;
}


static gboolean ___lambda3_ (NGSpiceSimulator* self, GIOChannel* channel, GIOCondition condition) {
	gboolean result = FALSE;
	GIOChannel* _tmp0_ = NULL;
	GIOCondition _tmp1_ = 0;
	gboolean _tmp2_ = FALSE;
	g_return_val_if_fail (channel != NULL, FALSE);
	_tmp0_ = channel;
	_tmp1_ = condition;
	_tmp2_ = ng_spice_simulator_process_line (self, _tmp0_, _tmp1_, "stderr");
	result = _tmp2_;
	return result;
}


static gboolean ____lambda3__gio_func (GIOChannel* source, GIOCondition condition, gpointer self) {
	gboolean result;
	result = ___lambda3_ (self, source, condition);
	return result;
}


NGSpiceSimulator* ng_spice_simulator_construct (GType object_type) {
	NGSpiceSimulator * self = NULL;
	gchar* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
	self = (NGSpiceSimulator*) g_object_new (object_type, NULL);
	_tmp0_ = g_strdup ("");
	_g_free0 (self->priv->builder);
	self->priv->builder = _tmp0_;
	{
		gchar** spawn_args = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		gchar** _tmp4_ = NULL;
		gint spawn_args_length1 = 0;
		gint _spawn_args_size_ = 0;
		gchar** spawn_env = NULL;
		gchar** _tmp5_ = NULL;
		gchar** _tmp6_ = NULL;
		gint spawn_env_length1 = 0;
		gint _spawn_env_size_ = 0;
		GPid child_pid = 0;
		gchar** _tmp7_ = NULL;
		gint _tmp7__length1 = 0;
		gchar** _tmp8_ = NULL;
		gint _tmp8__length1 = 0;
		GPid _tmp9_ = 0;
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
		gint _tmp12_ = 0;
		GIOChannel* output = NULL;
		gint _tmp13_ = 0;
		GIOChannel* _tmp14_ = NULL;
		GIOChannel* _error_ = NULL;
		gint _tmp15_ = 0;
		GIOChannel* _tmp16_ = NULL;
		_tmp1_ = g_strdup ("/usr/bin/ngspice");
		_tmp2_ = g_strdup ("-i");
		_tmp3_ = g_strdup ("-p");
		_tmp4_ = g_new0 (gchar*, 3 + 1);
		_tmp4_[0] = _tmp1_;
		_tmp4_[1] = _tmp2_;
		_tmp4_[2] = _tmp3_;
		spawn_args = _tmp4_;
		spawn_args_length1 = 3;
		_spawn_args_size_ = spawn_args_length1;
		_tmp6_ = _tmp5_ = g_get_environ ();
		spawn_env = _tmp6_;
		spawn_env_length1 = _vala_array_length (_tmp5_);
		_spawn_env_size_ = spawn_env_length1;
		_tmp7_ = spawn_args;
		_tmp7__length1 = spawn_args_length1;
		_tmp8_ = spawn_env;
		_tmp8__length1 = spawn_env_length1;
		g_spawn_async_with_pipes ("/home/steven/test/", _tmp7_, _tmp8_, G_SPAWN_SEARCH_PATH | G_SPAWN_DO_NOT_REAP_CHILD, NULL, NULL, &_tmp9_, &_tmp10_, &_tmp11_, &_tmp12_, &_inner_error_);
		child_pid = _tmp9_;
		self->priv->standard_input = _tmp10_;
		self->priv->standard_output = _tmp11_;
		self->priv->standard_error = _tmp12_;
		if (_inner_error_ != NULL) {
			spawn_env = (_vala_array_free (spawn_env, spawn_env_length1, (GDestroyNotify) g_free), NULL);
			spawn_args = (_vala_array_free (spawn_args, spawn_args_length1, (GDestroyNotify) g_free), NULL);
			goto __catch0_g_error;
		}
		_tmp13_ = self->priv->standard_output;
		_tmp14_ = g_io_channel_unix_new (_tmp13_);
		output = _tmp14_;
		g_io_add_watch (output, G_IO_IN | G_IO_HUP, ____lambda2__gio_func, self);
		_tmp15_ = self->priv->standard_error;
		_tmp16_ = g_io_channel_unix_new (_tmp15_);
		_error_ = _tmp16_;
		g_io_add_watch (_error_, G_IO_IN | G_IO_HUP, ____lambda3__gio_func, self);
		{
			gint _tmp17_ = 0;
			FILE* _tmp18_ = NULL;
			_tmp17_ = self->priv->standard_input;
			_tmp18_ = fdopen (_tmp17_, "w");
			_fclose0 (self->priv->input);
			self->priv->input = _tmp18_;
		}
		goto __finally1;
		__catch1_g_error:
		{
			GError* e = NULL;
			FILE* _tmp19_ = NULL;
			GError* _tmp20_ = NULL;
			const gchar* _tmp21_ = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp19_ = stdout;
			_tmp20_ = e;
			_tmp21_ = _tmp20_->message;
			fprintf (_tmp19_, "Error: %s\n", _tmp21_);
			_g_error_free0 (e);
		}
		__finally1:
		if (_inner_error_ != NULL) {
			_g_io_channel_unref0 (_error_);
			_g_io_channel_unref0 (output);
			spawn_env = (_vala_array_free (spawn_env, spawn_env_length1, (GDestroyNotify) g_free), NULL);
			spawn_args = (_vala_array_free (spawn_args, spawn_args_length1, (GDestroyNotify) g_free), NULL);
			goto __catch0_g_error;
		}
		_g_io_channel_unref0 (_error_);
		_g_io_channel_unref0 (output);
		spawn_env = (_vala_array_free (spawn_env, spawn_env_length1, (GDestroyNotify) g_free), NULL);
		spawn_args = (_vala_array_free (spawn_args, spawn_args_length1, (GDestroyNotify) g_free), NULL);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp22_ = NULL;
		GError* _tmp23_ = NULL;
		const gchar* _tmp24_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp22_ = stdout;
		_tmp23_ = e;
		_tmp24_ = _tmp23_->message;
		fprintf (_tmp22_, "Error: %s\n", _tmp24_);
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	return self;
}


NGSpiceSimulator* ng_spice_simulator_new (void) {
	return ng_spice_simulator_construct (TYPE_NG_SPICE_SIMULATOR);
}


static gboolean ng_spice_simulator_process_line (NGSpiceSimulator* self, GIOChannel* channel, GIOCondition condition, const gchar* stream_name) {
	gboolean result = FALSE;
	GIOCondition _tmp0_ = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (channel != NULL, FALSE);
	g_return_val_if_fail (stream_name != NULL, FALSE);
	_tmp0_ = condition;
	if (_tmp0_ == G_IO_HUP) {
		FILE* _tmp1_ = NULL;
		const gchar* _tmp2_ = NULL;
		_tmp1_ = stdout;
		_tmp2_ = stream_name;
		fprintf (_tmp1_, "%s: The fd has been closed.\n", _tmp2_);
		result = FALSE;
		return result;
	}
	{
		gchar* line = NULL;
		GIOChannel* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		FILE* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp3_ = channel;
		g_io_channel_read_line (_tmp3_, &_tmp4_, NULL, NULL, &_inner_error_);
		_g_free0 (line);
		line = _tmp4_;
		if (_inner_error_ != NULL) {
			_g_free0 (line);
			if (_inner_error_->domain == G_IO_CHANNEL_ERROR) {
				goto __catch2_g_io_channel_error;
			}
			if (_inner_error_->domain == G_CONVERT_ERROR) {
				goto __catch2_g_convert_error;
			}
			_g_free0 (line);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
		_tmp5_ = stdout;
		_tmp6_ = stream_name;
		_tmp7_ = line;
		fprintf (_tmp5_, "%s: %s", _tmp6_, _tmp7_);
		_tmp8_ = line;
		_tmp9_ = g_strdup (_tmp8_);
		_g_free0 (self->priv->builder);
		self->priv->builder = _tmp9_;
		_g_free0 (line);
	}
	goto __finally2;
	__catch2_g_io_channel_error:
	{
		GError* e = NULL;
		FILE* _tmp10_ = NULL;
		const gchar* _tmp11_ = NULL;
		GError* _tmp12_ = NULL;
		const gchar* _tmp13_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp10_ = stdout;
		_tmp11_ = stream_name;
		_tmp12_ = e;
		_tmp13_ = _tmp12_->message;
		fprintf (_tmp10_, "%s: IOChannelError: %s\n", _tmp11_, _tmp13_);
		result = FALSE;
		_g_error_free0 (e);
		return result;
	}
	goto __finally2;
	__catch2_g_convert_error:
	{
		GError* e = NULL;
		FILE* _tmp14_ = NULL;
		const gchar* _tmp15_ = NULL;
		GError* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp14_ = stdout;
		_tmp15_ = stream_name;
		_tmp16_ = e;
		_tmp17_ = _tmp16_->message;
		fprintf (_tmp14_, "%s: ConvertError: %s\n", _tmp15_, _tmp17_);
		result = FALSE;
		_g_error_free0 (e);
		return result;
	}
	__finally2:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	result = TRUE;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


gchar* ng_spice_simulator_generate_file (NGSpiceSimulator* self, GList* components) {
	gchar* result = NULL;
	GFile* file = NULL;
	GFile* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	GFileOutputStream* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	GFileOutputStream* _tmp6_ = NULL;
	GDataOutputStream* dos = NULL;
	GFileOutputStream* _tmp7_ = NULL;
	GDataOutputStream* _tmp8_ = NULL;
	GDataOutputStream* _tmp9_ = NULL;
	GDataOutputStream* _tmp10_ = NULL;
	GList* _tmp11_ = NULL;
	GDataOutputStream* _tmp20_ = NULL;
	GDataOutputStream* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_file_new_for_path ("/home/steven/test/netlist.txt");
	file = _tmp0_;
	_tmp1_ = file;
	_tmp2_ = g_file_query_exists (_tmp1_, NULL);
	if (_tmp2_) {
		GFile* _tmp3_ = NULL;
		_tmp3_ = file;
		g_file_delete (_tmp3_, NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (file);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp5_ = file;
	_tmp6_ = g_file_create (_tmp5_, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_inner_error_);
	_tmp4_ = _tmp6_;
	if (_inner_error_ != NULL) {
		_g_object_unref0 (file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp7_ = _tmp4_;
	_tmp8_ = g_data_output_stream_new ((GOutputStream*) _tmp7_);
	_tmp9_ = _tmp8_;
	_g_object_unref0 (_tmp7_);
	dos = _tmp9_;
	_tmp10_ = dos;
	g_data_output_stream_put_string (_tmp10_, " netlist by ElektroSim\n", NULL, &_inner_error_);
	if (_inner_error_ != NULL) {
		_g_object_unref0 (dos);
		_g_object_unref0 (file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp11_ = components;
	{
		GList* component_collection = NULL;
		GList* component_it = NULL;
		component_collection = _tmp11_;
		for (component_it = component_collection; component_it != NULL; component_it = component_it->next) {
			Component* _tmp12_ = NULL;
			Component* component = NULL;
			_tmp12_ = _g_object_ref0 ((Component*) component_it->data);
			component = _tmp12_;
			{
				GDataOutputStream* _tmp13_ = NULL;
				Component* _tmp14_ = NULL;
				gchar* _tmp15_ = NULL;
				gchar* _tmp16_ = NULL;
				Component* _tmp17_ = NULL;
				gchar* _tmp18_ = NULL;
				gchar* _tmp19_ = NULL;
				_tmp13_ = dos;
				_tmp14_ = component;
				_tmp15_ = component_getNetlistLine (_tmp14_);
				_tmp16_ = _tmp15_;
				g_data_output_stream_put_string (_tmp13_, _tmp16_, NULL, &_inner_error_);
				_g_free0 (_tmp16_);
				if (_inner_error_ != NULL) {
					_g_object_unref0 (component);
					_g_object_unref0 (dos);
					_g_object_unref0 (file);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return NULL;
				}
				_tmp17_ = component;
				_tmp18_ = component_getNetlistLine (_tmp17_);
				_tmp19_ = _tmp18_;
				g_print ("%s", _tmp19_);
				_g_free0 (_tmp19_);
				_g_object_unref0 (component);
			}
		}
	}
	_tmp20_ = dos;
	g_data_output_stream_put_string (_tmp20_, ".OP\n", NULL, &_inner_error_);
	if (_inner_error_ != NULL) {
		_g_object_unref0 (dos);
		_g_object_unref0 (file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp21_ = dos;
	g_data_output_stream_put_string (_tmp21_, ".END", NULL, &_inner_error_);
	if (_inner_error_ != NULL) {
		_g_object_unref0 (dos);
		_g_object_unref0 (file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp22_ = g_strdup ("ok");
	result = _tmp22_;
	_g_object_unref0 (dos);
	_g_object_unref0 (file);
	return result;
}


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res = NULL;
	gint res_length1 = 0;
	gint _res_size_ = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	guint8* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	guint8* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res_length1;
	_tmp3_ = res;
	_tmp3__length1 = res_length1;
	_tmp4_ = _tmp3_;
	_tmp4__length1 = _tmp3__length1;
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	return result;
}


static gboolean ng_spice_simulator_send_to_ngspice (NGSpiceSimulator* self, const gchar* command) {
	gboolean result = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (command != NULL, FALSE);
	{
		FILE* _tmp0_ = NULL;
		const gchar* _tmp1_ = NULL;
		guint8* _tmp2_ = NULL;
		gint _tmp2__length1 = 0;
		guint8* _tmp3_ = NULL;
		gint _tmp3__length1 = 0;
		_tmp0_ = self->priv->input;
		_tmp1_ = command;
		_tmp2_ = string_get_data (_tmp1_, &_tmp2__length1);
		_tmp3_ = _tmp2_;
		_tmp3__length1 = _tmp2__length1;
		fwrite (_tmp3_, (gsize) 1, _tmp3__length1, _tmp0_);
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError* e = NULL;
		GError* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = e;
		_tmp5_ = _tmp4_->message;
		g_print ("error: %s\n", _tmp5_);
		_g_error_free0 (e);
	}
	__finally3:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	result = TRUE;
	return result;
}


void ng_spice_simulator_run_simulation (NGSpiceSimulator* self, GList* components) {
	GList* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	ng_spice_simulator_send_to_ngspice (self, "source netlist.txt\n");
	ng_spice_simulator_send_to_ngspice (self, "run\n");
	_tmp0_ = components;
	{
		GList* component_collection = NULL;
		GList* component_it = NULL;
		component_collection = _tmp0_;
		for (component_it = component_collection; component_it != NULL; component_it = component_it->next) {
			Component* _tmp1_ = NULL;
			Component* component = NULL;
			_tmp1_ = _g_object_ref0 ((Component*) component_it->data);
			component = _tmp1_;
			{
				gchar* command = NULL;
				Component* _tmp2_ = NULL;
				const gchar* _tmp3_ = NULL;
				const gchar* _tmp4_ = NULL;
				gchar* _tmp5_ = NULL;
				gchar* _tmp6_ = NULL;
				gchar* _tmp7_ = NULL;
				gchar* _tmp8_ = NULL;
				const gchar* _tmp9_ = NULL;
				Component* _tmp10_ = NULL;
				const gchar* _tmp11_ = NULL;
				_tmp2_ = component;
				_tmp3_ = component_get_name (_tmp2_);
				_tmp4_ = _tmp3_;
				_tmp5_ = g_strconcat ("show ", _tmp4_, NULL);
				_tmp6_ = _tmp5_;
				_tmp7_ = g_strconcat (_tmp6_, "\n", NULL);
				_tmp8_ = _tmp7_;
				_g_free0 (_tmp6_);
				command = _tmp8_;
				_tmp9_ = command;
				ng_spice_simulator_send_to_ngspice (self, _tmp9_);
				_tmp10_ = component;
				_tmp11_ = self->priv->builder;
				component_insertSimulationData (_tmp10_, _tmp11_);
				_g_free0 (command);
				_g_object_unref0 (component);
			}
		}
	}
}


static void ng_spice_simulator_class_init (NGSpiceSimulatorClass * klass) {
	ng_spice_simulator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (NGSpiceSimulatorPrivate));
	G_OBJECT_CLASS (klass)->finalize = ng_spice_simulator_finalize;
}


static void ng_spice_simulator_instance_init (NGSpiceSimulator * self) {
	self->priv = NG_SPICE_SIMULATOR_GET_PRIVATE (self);
}


static void ng_spice_simulator_finalize (GObject* obj) {
	NGSpiceSimulator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_NG_SPICE_SIMULATOR, NGSpiceSimulator);
	_fclose0 (self->priv->input);
	_g_free0 (self->priv->builder);
	G_OBJECT_CLASS (ng_spice_simulator_parent_class)->finalize (obj);
}


GType ng_spice_simulator_get_type (void) {
	static volatile gsize ng_spice_simulator_type_id__volatile = 0;
	if (g_once_init_enter (&ng_spice_simulator_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (NGSpiceSimulatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ng_spice_simulator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NGSpiceSimulator), 0, (GInstanceInitFunc) ng_spice_simulator_instance_init, NULL };
		GType ng_spice_simulator_type_id;
		ng_spice_simulator_type_id = g_type_register_static (G_TYPE_OBJECT, "NGSpiceSimulator", &g_define_type_info, 0);
		g_once_init_leave (&ng_spice_simulator_type_id__volatile, ng_spice_simulator_type_id);
	}
	return ng_spice_simulator_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



