/* power-source.c generated by valac 0.22.1, the Vala compiler
 * generated from power-source.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * ground.vala
 * Copyright (C) 2014 Steven Vanden Branden <Stevenvandenbrandenstift@gmail.com>
 *
 * ElektroSim is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ElektroSim is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <cairo.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define TYPE_COMPONENT (component_get_type ())
#define COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMPONENT, Component))
#define COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMPONENT, ComponentClass))
#define IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMPONENT))
#define IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMPONENT))
#define COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMPONENT, ComponentClass))

typedef struct _Component Component;
typedef struct _ComponentClass ComponentClass;
typedef struct _ComponentPrivate ComponentPrivate;

#define TYPE_POINT (point_get_type ())
#define POINT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POINT, Point))
#define POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POINT, PointClass))
#define IS_POINT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POINT))
#define IS_POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POINT))
#define POINT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POINT, PointClass))

typedef struct _Point Point;
typedef struct _PointClass PointClass;

#define TYPE_POWER_SOURCE (power_source_get_type ())
#define POWER_SOURCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POWER_SOURCE, PowerSource))
#define POWER_SOURCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POWER_SOURCE, PowerSourceClass))
#define IS_POWER_SOURCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POWER_SOURCE))
#define IS_POWER_SOURCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POWER_SOURCE))
#define POWER_SOURCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POWER_SOURCE, PowerSourceClass))

typedef struct _PowerSource PowerSource;
typedef struct _PowerSourceClass PowerSourceClass;
typedef struct _PowerSourcePrivate PowerSourcePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Component {
	GtkListBoxRow parent_instance;
	ComponentPrivate * priv;
	GList* connections;
};

struct _ComponentClass {
	GtkListBoxRowClass parent_class;
	Component* (*clone) (Component* self, Component* component, gint x, gint y);
	gint (*snap) (Component* self, GList* list, gint range, gint netAmount);
	void (*draw_symbol) (Component* self, cairo_t* context);
	gchar* (*getNetlistLine) (Component* self);
	void (*insertSimulationData) (Component* self, const gchar* data);
};

struct _PowerSource {
	Component parent_instance;
	PowerSourcePrivate * priv;
};

struct _PowerSourceClass {
	ComponentClass parent_class;
};

struct _PowerSourcePrivate {
	gfloat _voltage;
	gchar* _voltageUnit;
};


static gpointer power_source_parent_class = NULL;
extern gint power_source_counter;
gint power_source_counter = 0;

GType component_get_type (void) G_GNUC_CONST;
gpointer point_ref (gpointer instance);
void point_unref (gpointer instance);
GParamSpec* param_spec_point (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_point (GValue* value, gpointer v_object);
void value_take_point (GValue* value, gpointer v_object);
gpointer value_get_point (const GValue* value);
GType point_get_type (void) G_GNUC_CONST;
GType power_source_get_type (void) G_GNUC_CONST;
#define POWER_SOURCE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_POWER_SOURCE, PowerSourcePrivate))
enum  {
	POWER_SOURCE_DUMMY_PROPERTY,
	POWER_SOURCE_VOLTAGE,
	POWER_SOURCE_VOLTAGE_UNIT
};
PowerSource* power_source_new (gfloat voltage);
PowerSource* power_source_construct (GType object_type, gfloat voltage);
Component* component_construct (GType object_type, const gchar* name);
void component_set_width (Component* self, gint value);
void power_source_set_voltage (PowerSource* self, gfloat value);
static void power_source_real_draw_symbol (Component* base, cairo_t* context);
gint point_get_x (Point* self);
gint point_get_y (Point* self);
gint component_get_width (Component* self);
gfloat power_source_get_voltage (PowerSource* self);
static Component* power_source_real_clone (Component* base, Component* component, gint x, gint y);
void component_set_name (Component* self, const gchar* value);
Point* point_new (gint x, gint y);
Point* point_construct (GType object_type, gint x, gint y);
static gint power_source_real_snap (Component* base, GList* list, gint range, gint netCount);
gboolean point_pointNearby (Point* self, gint range, GList* items);
gint point_checkNetName (Point* self, gint netCount);
static void power_source_real_insertSimulationData (Component* base, const gchar* data);
static gchar* power_source_real_getNetlistLine (Component* base);
const gchar* component_get_name (Component* self);
gint point_get_net (Point* self);
const gchar* power_source_get_voltageUnit (PowerSource* self);
void power_source_set_voltageUnit (PowerSource* self, const gchar* value);
static void power_source_finalize (GObject* obj);
static void _vala_power_source_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_power_source_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


PowerSource* power_source_construct (GType object_type, gfloat voltage) {
	PowerSource * self = NULL;
	gfloat _tmp0_ = 0.0F;
	self = (PowerSource*) component_construct (object_type, "PowerSource");
	component_set_width ((Component*) self, 100);
	_tmp0_ = voltage;
	power_source_set_voltage (self, _tmp0_);
	return self;
}


PowerSource* power_source_new (gfloat voltage) {
	return power_source_construct (TYPE_POWER_SOURCE, voltage);
}


static void power_source_real_draw_symbol (Component* base, cairo_t* context) {
	PowerSource * self;
	cairo_t* _tmp0_ = NULL;
	cairo_t* _tmp1_ = NULL;
	cairo_t* _tmp2_ = NULL;
	GList* _tmp3_ = NULL;
	gconstpointer _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	GList* _tmp7_ = NULL;
	gconstpointer _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	gint _tmp12_ = 0;
	cairo_t* _tmp13_ = NULL;
	cairo_t* _tmp14_ = NULL;
	cairo_t* _tmp15_ = NULL;
	gfloat _tmp16_ = 0.0F;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	cairo_t* _tmp19_ = NULL;
	cairo_t* _tmp20_ = NULL;
	cairo_t* _tmp21_ = NULL;
	self = (PowerSource*) base;
	g_return_if_fail (context != NULL);
	_tmp0_ = context;
	cairo_new_path (_tmp0_);
	_tmp1_ = context;
	cairo_set_source_rgb (_tmp1_, (gdouble) 3, (gdouble) 3, (gdouble) 3);
	_tmp2_ = context;
	_tmp3_ = ((Component*) self)->connections;
	_tmp4_ = g_list_nth_data (_tmp3_, (guint) 0);
	_tmp5_ = point_get_x ((Point*) _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = ((Component*) self)->connections;
	_tmp8_ = g_list_nth_data (_tmp7_, (guint) 0);
	_tmp9_ = point_get_y ((Point*) _tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = component_get_width ((Component*) self);
	_tmp12_ = _tmp11_;
	cairo_rectangle (_tmp2_, (gdouble) _tmp6_, (gdouble) _tmp10_, (gdouble) _tmp12_, (gdouble) 2);
	_tmp13_ = context;
	cairo_select_font_face (_tmp13_, "Adventure", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_BOLD);
	_tmp14_ = context;
	cairo_set_font_size (_tmp14_, (gdouble) 20);
	_tmp15_ = context;
	_tmp16_ = self->priv->_voltage;
	_tmp17_ = g_strdup_printf ("         %.0f V", (gdouble) _tmp16_);
	_tmp18_ = _tmp17_;
	cairo_text_path (_tmp15_, _tmp18_);
	_g_free0 (_tmp18_);
	_tmp19_ = context;
	cairo_fill (_tmp19_);
	_tmp20_ = context;
	cairo_stroke (_tmp20_);
	_tmp21_ = context;
	cairo_close_path (_tmp21_);
}


static Component* power_source_real_clone (Component* base, Component* component, gint x, gint y) {
	PowerSource * self;
	Component* result = NULL;
	PowerSource* newc = NULL;
	Component* _tmp0_ = NULL;
	gfloat _tmp1_ = 0.0F;
	PowerSource* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	Point* _tmp11_ = NULL;
	self = (PowerSource*) base;
	g_return_val_if_fail (component != NULL, NULL);
	_tmp0_ = component;
	_tmp1_ = (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, TYPE_POWER_SOURCE) ? ((PowerSource*) _tmp0_) : NULL)->priv->_voltage;
	_tmp2_ = power_source_new (_tmp1_);
	g_object_ref_sink (_tmp2_);
	newc = _tmp2_;
	_tmp3_ = power_source_counter;
	power_source_counter = _tmp3_ + 1;
	_tmp4_ = power_source_counter;
	_tmp5_ = g_strdup_printf ("%i", _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = g_strconcat ("v", _tmp6_, NULL);
	_tmp8_ = _tmp7_;
	component_set_name ((Component*) newc, _tmp8_);
	_g_free0 (_tmp8_);
	_g_free0 (_tmp6_);
	_tmp9_ = x;
	_tmp10_ = y;
	_tmp11_ = point_new (_tmp9_, _tmp10_);
	((Component*) newc)->connections = g_list_append (((Component*) newc)->connections, _tmp11_);
	result = (Component*) newc;
	return result;
}


static gint power_source_real_snap (Component* base, GList* list, gint range, gint netCount) {
	PowerSource * self;
	gint result = 0;
	GList* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GList* _tmp3_ = NULL;
	gint newNetCount = 0;
	GList* _tmp4_ = NULL;
	gconstpointer _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	self = (PowerSource*) base;
	_tmp0_ = ((Component*) self)->connections;
	_tmp1_ = g_list_nth_data (_tmp0_, (guint) 0);
	_tmp2_ = range;
	_tmp3_ = list;
	point_pointNearby ((Point*) _tmp1_, _tmp2_, _tmp3_);
	_tmp4_ = ((Component*) self)->connections;
	_tmp5_ = g_list_nth_data (_tmp4_, (guint) 0);
	_tmp6_ = netCount;
	_tmp7_ = point_checkNetName ((Point*) _tmp5_, _tmp6_);
	newNetCount = _tmp7_;
	result = newNetCount;
	return result;
}


static void power_source_real_insertSimulationData (Component* base, const gchar* data) {
	PowerSource * self;
	self = (PowerSource*) base;
	g_return_if_fail (data != NULL);
}


static gchar* power_source_real_getNetlistLine (Component* base) {
	PowerSource * self;
	gchar* result = NULL;
	gchar* line = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GList* _tmp4_ = NULL;
	gconstpointer _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gfloat _tmp14_ = 0.0F;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	self = (PowerSource*) base;
	_tmp0_ = component_get_name ((Component*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strconcat (_tmp1_, " ", NULL);
	_tmp3_ = _tmp2_;
	_tmp4_ = ((Component*) self)->connections;
	_tmp5_ = g_list_nth_data (_tmp4_, (guint) 0);
	_tmp6_ = point_get_net ((Point*) _tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strdup_printf ("%i", _tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strconcat (_tmp3_, _tmp9_, NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, " 0 ", NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = self->priv->_voltage;
	_tmp15_ = g_strdup_printf ("%g", _tmp14_);
	_tmp16_ = _tmp15_;
	_tmp17_ = g_strconcat (_tmp13_, _tmp16_, NULL);
	_tmp18_ = _tmp17_;
	_tmp19_ = self->priv->_voltageUnit;
	_tmp20_ = g_strconcat (_tmp18_, _tmp19_, NULL);
	_tmp21_ = _tmp20_;
	_tmp22_ = g_strconcat (_tmp21_, "\n", NULL);
	_g_free0 (line);
	line = _tmp22_;
	_g_free0 (_tmp21_);
	_g_free0 (_tmp18_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp13_);
	_g_free0 (_tmp11_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp3_);
	result = line;
	return result;
}


gfloat power_source_get_voltage (PowerSource* self) {
	gfloat result;
	gfloat _tmp0_ = 0.0F;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->priv->_voltage;
	result = _tmp0_;
	return result;
}


void power_source_set_voltage (PowerSource* self, gfloat value) {
	gfloat _tmp0_ = 0.0F;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_voltage = _tmp0_;
	g_object_notify ((GObject *) self, "voltage");
}


const gchar* power_source_get_voltageUnit (PowerSource* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_voltageUnit;
	result = _tmp0_;
	return result;
}


void power_source_set_voltageUnit (PowerSource* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_voltageUnit);
	self->priv->_voltageUnit = _tmp1_;
	g_object_notify ((GObject *) self, "voltageUnit");
}


static void power_source_class_init (PowerSourceClass * klass) {
	power_source_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PowerSourcePrivate));
	COMPONENT_CLASS (klass)->draw_symbol = power_source_real_draw_symbol;
	COMPONENT_CLASS (klass)->clone = power_source_real_clone;
	COMPONENT_CLASS (klass)->snap = power_source_real_snap;
	COMPONENT_CLASS (klass)->insertSimulationData = power_source_real_insertSimulationData;
	COMPONENT_CLASS (klass)->getNetlistLine = power_source_real_getNetlistLine;
	G_OBJECT_CLASS (klass)->get_property = _vala_power_source_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_power_source_set_property;
	G_OBJECT_CLASS (klass)->finalize = power_source_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), POWER_SOURCE_VOLTAGE, g_param_spec_float ("voltage", "voltage", "voltage", -G_MAXFLOAT, G_MAXFLOAT, (gfloat) 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), POWER_SOURCE_VOLTAGE_UNIT, g_param_spec_string ("voltageUnit", "voltageUnit", "voltageUnit", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void power_source_instance_init (PowerSource * self) {
	gchar* _tmp0_ = NULL;
	self->priv = POWER_SOURCE_GET_PRIVATE (self);
	self->priv->_voltage = (gfloat) 0;
	_tmp0_ = g_strdup ("V");
	self->priv->_voltageUnit = _tmp0_;
}


static void power_source_finalize (GObject* obj) {
	PowerSource * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_POWER_SOURCE, PowerSource);
	_g_free0 (self->priv->_voltageUnit);
	G_OBJECT_CLASS (power_source_parent_class)->finalize (obj);
}


GType power_source_get_type (void) {
	static volatile gsize power_source_type_id__volatile = 0;
	if (g_once_init_enter (&power_source_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PowerSourceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) power_source_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PowerSource), 0, (GInstanceInitFunc) power_source_instance_init, NULL };
		GType power_source_type_id;
		power_source_type_id = g_type_register_static (TYPE_COMPONENT, "PowerSource", &g_define_type_info, 0);
		g_once_init_leave (&power_source_type_id__volatile, power_source_type_id);
	}
	return power_source_type_id__volatile;
}


static void _vala_power_source_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	PowerSource * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_POWER_SOURCE, PowerSource);
	switch (property_id) {
		case POWER_SOURCE_VOLTAGE:
		g_value_set_float (value, power_source_get_voltage (self));
		break;
		case POWER_SOURCE_VOLTAGE_UNIT:
		g_value_set_string (value, power_source_get_voltageUnit (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_power_source_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	PowerSource * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_POWER_SOURCE, PowerSource);
	switch (property_id) {
		case POWER_SOURCE_VOLTAGE:
		power_source_set_voltage (self, g_value_get_float (value));
		break;
		case POWER_SOURCE_VOLTAGE_UNIT:
		power_source_set_voltageUnit (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



