/* resistor.c generated by valac 0.22.1, the Vala compiler
 * generated from resistor.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * resistor.vala
 * Copyright (C) 2014 Steven Vanden Branden <StevenVandenBrandenstift@gmail.com>
 *
 * ElektroSim is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ElektroSim is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <cairo.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define TYPE_COMPONENT (component_get_type ())
#define COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMPONENT, Component))
#define COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMPONENT, ComponentClass))
#define IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMPONENT))
#define IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMPONENT))
#define COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMPONENT, ComponentClass))

typedef struct _Component Component;
typedef struct _ComponentClass ComponentClass;
typedef struct _ComponentPrivate ComponentPrivate;

#define TYPE_POINT (point_get_type ())
#define POINT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POINT, Point))
#define POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POINT, PointClass))
#define IS_POINT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POINT))
#define IS_POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POINT))
#define POINT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POINT, PointClass))

typedef struct _Point Point;
typedef struct _PointClass PointClass;

#define TYPE_RESISTOR (resistor_get_type ())
#define RESISTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RESISTOR, Resistor))
#define RESISTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RESISTOR, ResistorClass))
#define IS_RESISTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RESISTOR))
#define IS_RESISTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RESISTOR))
#define RESISTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RESISTOR, ResistorClass))

typedef struct _Resistor Resistor;
typedef struct _ResistorClass ResistorClass;
typedef struct _ResistorPrivate ResistorPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Component {
	GtkListBoxRow parent_instance;
	ComponentPrivate * priv;
	GList* connections;
};

struct _ComponentClass {
	GtkListBoxRowClass parent_class;
	Component* (*clone) (Component* self, Component* component, gint x, gint y);
	gint (*snap) (Component* self, GList* list, gint range, gint netAmount);
	void (*draw_symbol) (Component* self, cairo_t* context);
	gchar* (*getNetlistLine) (Component* self);
	void (*insertSimulationData) (Component* self, const gchar* data);
};

struct _Resistor {
	Component parent_instance;
	ResistorPrivate * priv;
};

struct _ResistorClass {
	ComponentClass parent_class;
};

struct _ResistorPrivate {
	gfloat _resistance;
	gchar* _resistanceUnit;
	gfloat _ac;
	gfloat _dtemp;
	gfloat _bv_max;
	gfloat _noisy;
	gfloat _i;
	gfloat _p;
};


static gpointer resistor_parent_class = NULL;
extern gint resistor_counter;
gint resistor_counter = 0;

GType component_get_type (void) G_GNUC_CONST;
gpointer point_ref (gpointer instance);
void point_unref (gpointer instance);
GParamSpec* param_spec_point (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_point (GValue* value, gpointer v_object);
void value_take_point (GValue* value, gpointer v_object);
gpointer value_get_point (const GValue* value);
GType point_get_type (void) G_GNUC_CONST;
GType resistor_get_type (void) G_GNUC_CONST;
#define RESISTOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_RESISTOR, ResistorPrivate))
enum  {
	RESISTOR_DUMMY_PROPERTY,
	RESISTOR_RESISTANCE,
	RESISTOR_RESISTANCE_UNIT,
	RESISTOR_AC,
	RESISTOR_DTEMP,
	RESISTOR_BV_MAX,
	RESISTOR_NOISY,
	RESISTOR_I,
	RESISTOR_P
};
Resistor* resistor_new (gfloat restistance);
Resistor* resistor_construct (GType object_type, gfloat restistance);
Component* component_construct (GType object_type, const gchar* name);
void component_set_width (Component* self, gint value);
void resistor_set_resistance (Resistor* self, gfloat value);
static void resistor_real_draw_symbol (Component* base, cairo_t* context);
gint point_get_x (Point* self);
gint point_get_y (Point* self);
gint component_get_width (Component* self);
static Component* resistor_real_clone (Component* base, Component* component, gint x, gint y);
gfloat resistor_get_resistance (Resistor* self);
void component_set_name (Component* self, const gchar* value);
Point* point_new (gint x, gint y);
Point* point_construct (GType object_type, gint x, gint y);
static gint resistor_real_snap (Component* base, GList* list, gint range, gint netCount);
gboolean point_pointNearby (Point* self, gint range, GList* items);
void point_set_x (Point* self, gint value);
void point_set_y (Point* self, gint value);
gint point_checkNetName (Point* self, gint netCount);
static void resistor_real_insertSimulationData (Component* base, const gchar* data);
static gchar* resistor_real_getNetlistLine (Component* base);
const gchar* component_get_name (Component* self);
gint point_get_net (Point* self);
const gchar* resistor_get_resistanceUnit (Resistor* self);
void resistor_set_resistanceUnit (Resistor* self, const gchar* value);
gfloat resistor_get_ac (Resistor* self);
void resistor_set_ac (Resistor* self, gfloat value);
gfloat resistor_get_dtemp (Resistor* self);
void resistor_set_dtemp (Resistor* self, gfloat value);
gfloat resistor_get_bv_max (Resistor* self);
void resistor_set_bv_max (Resistor* self, gfloat value);
gfloat resistor_get_noisy (Resistor* self);
void resistor_set_noisy (Resistor* self, gfloat value);
gfloat resistor_get_i (Resistor* self);
void resistor_set_i (Resistor* self, gfloat value);
gfloat resistor_get_p (Resistor* self);
void resistor_set_p (Resistor* self, gfloat value);
static void resistor_finalize (GObject* obj);
static void _vala_resistor_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_resistor_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


Resistor* resistor_construct (GType object_type, gfloat restistance) {
	Resistor * self = NULL;
	gfloat _tmp0_ = 0.0F;
	self = (Resistor*) component_construct (object_type, "resistor");
	component_set_width ((Component*) self, 250);
	_tmp0_ = restistance;
	resistor_set_resistance (self, _tmp0_);
	return self;
}


Resistor* resistor_new (gfloat restistance) {
	return resistor_construct (TYPE_RESISTOR, restistance);
}


static void resistor_real_draw_symbol (Component* base, cairo_t* context) {
	Resistor * self;
	cairo_t* _tmp0_ = NULL;
	cairo_t* _tmp1_ = NULL;
	cairo_t* _tmp2_ = NULL;
	GList* _tmp3_ = NULL;
	gconstpointer _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	GList* _tmp7_ = NULL;
	gconstpointer _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	gint _tmp12_ = 0;
	cairo_t* _tmp13_ = NULL;
	GList* _tmp14_ = NULL;
	gconstpointer _tmp15_ = NULL;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
	gint _tmp18_ = 0;
	gint _tmp19_ = 0;
	GList* _tmp20_ = NULL;
	gconstpointer _tmp21_ = NULL;
	gint _tmp22_ = 0;
	gint _tmp23_ = 0;
	gint _tmp24_ = 0;
	gint _tmp25_ = 0;
	gint _tmp26_ = 0;
	gint _tmp27_ = 0;
	gint _tmp28_ = 0;
	gint _tmp29_ = 0;
	cairo_t* _tmp30_ = NULL;
	GList* _tmp31_ = NULL;
	gconstpointer _tmp32_ = NULL;
	gint _tmp33_ = 0;
	gint _tmp34_ = 0;
	gint _tmp35_ = 0;
	gint _tmp36_ = 0;
	GList* _tmp37_ = NULL;
	gconstpointer _tmp38_ = NULL;
	gint _tmp39_ = 0;
	gint _tmp40_ = 0;
	gint _tmp41_ = 0;
	gint _tmp42_ = 0;
	cairo_t* _tmp43_ = NULL;
	cairo_t* _tmp44_ = NULL;
	self = (Resistor*) base;
	g_return_if_fail (context != NULL);
	_tmp0_ = context;
	cairo_new_path (_tmp0_);
	_tmp1_ = context;
	cairo_set_source_rgb (_tmp1_, (gdouble) 3, (gdouble) 3, (gdouble) 3);
	_tmp2_ = context;
	_tmp3_ = ((Component*) self)->connections;
	_tmp4_ = g_list_nth_data (_tmp3_, (guint) 0);
	_tmp5_ = point_get_x ((Point*) _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = ((Component*) self)->connections;
	_tmp8_ = g_list_nth_data (_tmp7_, (guint) 0);
	_tmp9_ = point_get_y ((Point*) _tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = component_get_width ((Component*) self);
	_tmp12_ = _tmp11_;
	cairo_rectangle (_tmp2_, (gdouble) _tmp6_, (gdouble) _tmp10_, (gdouble) (_tmp12_ / 5), (gdouble) 2);
	_tmp13_ = context;
	_tmp14_ = ((Component*) self)->connections;
	_tmp15_ = g_list_nth_data (_tmp14_, (guint) 0);
	_tmp16_ = point_get_x ((Point*) _tmp15_);
	_tmp17_ = _tmp16_;
	_tmp18_ = component_get_width ((Component*) self);
	_tmp19_ = _tmp18_;
	_tmp20_ = ((Component*) self)->connections;
	_tmp21_ = g_list_nth_data (_tmp20_, (guint) 0);
	_tmp22_ = point_get_y ((Point*) _tmp21_);
	_tmp23_ = _tmp22_;
	_tmp24_ = component_get_width ((Component*) self);
	_tmp25_ = _tmp24_;
	_tmp26_ = component_get_width ((Component*) self);
	_tmp27_ = _tmp26_;
	_tmp28_ = component_get_width ((Component*) self);
	_tmp29_ = _tmp28_;
	cairo_rectangle (_tmp13_, (gdouble) (_tmp17_ + (_tmp19_ / 5)), (gdouble) (_tmp23_ - (_tmp25_ / 10)), (gdouble) ((_tmp27_ / 5) * 3), (gdouble) (_tmp29_ / 5));
	_tmp30_ = context;
	_tmp31_ = ((Component*) self)->connections;
	_tmp32_ = g_list_nth_data (_tmp31_, (guint) 1);
	_tmp33_ = point_get_x ((Point*) _tmp32_);
	_tmp34_ = _tmp33_;
	_tmp35_ = component_get_width ((Component*) self);
	_tmp36_ = _tmp35_;
	_tmp37_ = ((Component*) self)->connections;
	_tmp38_ = g_list_nth_data (_tmp37_, (guint) 1);
	_tmp39_ = point_get_y ((Point*) _tmp38_);
	_tmp40_ = _tmp39_;
	_tmp41_ = component_get_width ((Component*) self);
	_tmp42_ = _tmp41_;
	cairo_rectangle (_tmp30_, (gdouble) (_tmp34_ - (_tmp36_ / 5)), (gdouble) _tmp40_, (gdouble) (_tmp42_ / 5), (gdouble) 2);
	_tmp43_ = context;
	cairo_stroke (_tmp43_);
	_tmp44_ = context;
	cairo_close_path (_tmp44_);
}


static Component* resistor_real_clone (Component* base, Component* component, gint x, gint y) {
	Resistor * self;
	Component* result = NULL;
	Resistor* newc = NULL;
	Component* _tmp0_ = NULL;
	gfloat _tmp1_ = 0.0F;
	Resistor* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	Point* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	gint _tmp15_ = 0;
	Point* _tmp16_ = NULL;
	self = (Resistor*) base;
	g_return_val_if_fail (component != NULL, NULL);
	_tmp0_ = component;
	_tmp1_ = (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, TYPE_RESISTOR) ? ((Resistor*) _tmp0_) : NULL)->priv->_resistance;
	_tmp2_ = resistor_new (_tmp1_);
	g_object_ref_sink (_tmp2_);
	newc = _tmp2_;
	_tmp3_ = resistor_counter;
	resistor_counter = _tmp3_ + 1;
	_tmp4_ = resistor_counter;
	_tmp5_ = g_strdup_printf ("%i", _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = g_strconcat ("r", _tmp6_, NULL);
	_tmp8_ = _tmp7_;
	component_set_name ((Component*) newc, _tmp8_);
	_g_free0 (_tmp8_);
	_g_free0 (_tmp6_);
	_tmp9_ = x;
	_tmp10_ = y;
	_tmp11_ = point_new (_tmp9_, _tmp10_);
	((Component*) newc)->connections = g_list_append (((Component*) newc)->connections, _tmp11_);
	_tmp12_ = x;
	_tmp13_ = component_get_width ((Component*) self);
	_tmp14_ = _tmp13_;
	_tmp15_ = y;
	_tmp16_ = point_new (_tmp12_ + _tmp14_, _tmp15_);
	((Component*) newc)->connections = g_list_append (((Component*) newc)->connections, _tmp16_);
	result = (Component*) newc;
	return result;
}


static gint resistor_real_snap (Component* base, GList* list, gint range, gint netCount) {
	Resistor * self;
	gint result = 0;
	GList* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GList* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	self = (Resistor*) base;
	_tmp0_ = ((Component*) self)->connections;
	_tmp1_ = g_list_nth_data (_tmp0_, (guint) 0);
	_tmp2_ = range;
	_tmp3_ = list;
	_tmp4_ = point_pointNearby ((Point*) _tmp1_, _tmp2_, _tmp3_);
	if (_tmp4_) {
		GList* _tmp5_ = NULL;
		gconstpointer _tmp6_ = NULL;
		GList* _tmp7_ = NULL;
		gconstpointer _tmp8_ = NULL;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
		gint _tmp12_ = 0;
		GList* _tmp13_ = NULL;
		gconstpointer _tmp14_ = NULL;
		GList* _tmp15_ = NULL;
		gconstpointer _tmp16_ = NULL;
		gint _tmp17_ = 0;
		gint _tmp18_ = 0;
		GList* _tmp19_ = NULL;
		gconstpointer _tmp20_ = NULL;
		gint _tmp21_ = 0;
		gint _tmp22_ = 0;
		gint _tmp23_ = 0;
		_tmp5_ = ((Component*) self)->connections;
		_tmp6_ = g_list_nth_data (_tmp5_, (guint) 1);
		_tmp7_ = ((Component*) self)->connections;
		_tmp8_ = g_list_nth_data (_tmp7_, (guint) 0);
		_tmp9_ = point_get_x ((Point*) _tmp8_);
		_tmp10_ = _tmp9_;
		_tmp11_ = component_get_width ((Component*) self);
		_tmp12_ = _tmp11_;
		point_set_x ((Point*) _tmp6_, _tmp10_ + _tmp12_);
		_tmp13_ = ((Component*) self)->connections;
		_tmp14_ = g_list_nth_data (_tmp13_, (guint) 1);
		_tmp15_ = ((Component*) self)->connections;
		_tmp16_ = g_list_nth_data (_tmp15_, (guint) 0);
		_tmp17_ = point_get_y ((Point*) _tmp16_);
		_tmp18_ = _tmp17_;
		point_set_y ((Point*) _tmp14_, _tmp18_);
		_tmp19_ = ((Component*) self)->connections;
		_tmp20_ = g_list_nth_data (_tmp19_, (guint) 1);
		_tmp21_ = netCount;
		_tmp22_ = point_checkNetName ((Point*) _tmp20_, _tmp21_);
		netCount = _tmp22_;
		_tmp23_ = netCount;
		result = _tmp23_;
		return result;
	} else {
		GList* _tmp24_ = NULL;
		gconstpointer _tmp25_ = NULL;
		gint _tmp26_ = 0;
		gint _tmp27_ = 0;
		GList* _tmp28_ = NULL;
		gconstpointer _tmp29_ = NULL;
		gint _tmp30_ = 0;
		gint _tmp31_ = 0;
		gint _tmp32_ = 0;
		_tmp24_ = ((Component*) self)->connections;
		_tmp25_ = g_list_nth_data (_tmp24_, (guint) 0);
		_tmp26_ = netCount;
		_tmp27_ = point_checkNetName ((Point*) _tmp25_, _tmp26_);
		netCount = _tmp27_;
		_tmp28_ = ((Component*) self)->connections;
		_tmp29_ = g_list_nth_data (_tmp28_, (guint) 1);
		_tmp30_ = netCount;
		_tmp31_ = point_checkNetName ((Point*) _tmp29_, _tmp30_);
		netCount = _tmp31_;
		_tmp32_ = netCount;
		result = _tmp32_;
		return result;
	}
}


static void resistor_real_insertSimulationData (Component* base, const gchar* data) {
	Resistor * self;
	const gchar* _tmp0_ = NULL;
	gchar** splitData = NULL;
	const gchar* _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	gint splitData_length1 = 0;
	gint _splitData_size_ = 0;
	gchar** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	self = (Resistor*) base;
	g_return_if_fail (data != NULL);
	_tmp0_ = data;
	g_print ("%s\n", _tmp0_);
	_tmp1_ = data;
	_tmp3_ = _tmp2_ = g_strsplit_set (_tmp1_, "\t ", 0);
	splitData = _tmp3_;
	splitData_length1 = _vala_array_length (_tmp2_);
	_splitData_size_ = splitData_length1;
	_tmp4_ = splitData;
	_tmp4__length1 = splitData_length1;
	{
		gchar** line_collection = NULL;
		gint line_collection_length1 = 0;
		gint _line_collection_size_ = 0;
		gint line_it = 0;
		line_collection = _tmp4_;
		line_collection_length1 = _tmp4__length1;
		for (line_it = 0; line_it < _tmp4__length1; line_it = line_it + 1) {
			gchar* _tmp5_ = NULL;
			gchar* line = NULL;
			_tmp5_ = g_strdup (line_collection[line_it]);
			line = _tmp5_;
			{
				const gchar* _tmp6_ = NULL;
				_tmp6_ = line;
				g_print ("%s\n", _tmp6_);
				_g_free0 (line);
			}
		}
	}
	splitData = (_vala_array_free (splitData, splitData_length1, (GDestroyNotify) g_free), NULL);
}


static gchar* resistor_real_getNetlistLine (Component* base) {
	Resistor * self;
	gchar* result = NULL;
	gchar* line = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GList* _tmp4_ = NULL;
	gconstpointer _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	GList* _tmp14_ = NULL;
	gconstpointer _tmp15_ = NULL;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	gfloat _tmp24_ = 0.0F;
	gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	const gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	self = (Resistor*) base;
	_tmp0_ = component_get_name ((Component*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strconcat (_tmp1_, " ", NULL);
	_tmp3_ = _tmp2_;
	_tmp4_ = ((Component*) self)->connections;
	_tmp5_ = g_list_nth_data (_tmp4_, (guint) 0);
	_tmp6_ = point_get_net ((Point*) _tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strdup_printf ("%i", _tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strconcat (_tmp3_, _tmp9_, NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, " ", NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = ((Component*) self)->connections;
	_tmp15_ = g_list_nth_data (_tmp14_, (guint) 1);
	_tmp16_ = point_get_net ((Point*) _tmp15_);
	_tmp17_ = _tmp16_;
	_tmp18_ = g_strdup_printf ("%i", _tmp17_);
	_tmp19_ = _tmp18_;
	_tmp20_ = g_strconcat (_tmp13_, _tmp19_, NULL);
	_tmp21_ = _tmp20_;
	_tmp22_ = g_strconcat (_tmp21_, " ", NULL);
	_tmp23_ = _tmp22_;
	_tmp24_ = self->priv->_resistance;
	_tmp25_ = g_strdup_printf ("%g", _tmp24_);
	_tmp26_ = _tmp25_;
	_tmp27_ = g_strconcat (_tmp23_, _tmp26_, NULL);
	_tmp28_ = _tmp27_;
	_tmp29_ = self->priv->_resistanceUnit;
	_tmp30_ = g_strconcat (_tmp28_, _tmp29_, NULL);
	_tmp31_ = _tmp30_;
	_tmp32_ = g_strconcat (_tmp31_, "\n", NULL);
	_g_free0 (line);
	line = _tmp32_;
	_g_free0 (_tmp31_);
	_g_free0 (_tmp28_);
	_g_free0 (_tmp26_);
	_g_free0 (_tmp23_);
	_g_free0 (_tmp21_);
	_g_free0 (_tmp19_);
	_g_free0 (_tmp13_);
	_g_free0 (_tmp11_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp3_);
	result = line;
	return result;
}


gfloat resistor_get_resistance (Resistor* self) {
	gfloat result;
	gfloat _tmp0_ = 0.0F;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->priv->_resistance;
	result = _tmp0_;
	return result;
}


void resistor_set_resistance (Resistor* self, gfloat value) {
	gfloat _tmp0_ = 0.0F;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_resistance = _tmp0_;
	g_object_notify ((GObject *) self, "resistance");
}


const gchar* resistor_get_resistanceUnit (Resistor* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_resistanceUnit;
	result = _tmp0_;
	return result;
}


void resistor_set_resistanceUnit (Resistor* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_resistanceUnit);
	self->priv->_resistanceUnit = _tmp1_;
	g_object_notify ((GObject *) self, "resistanceUnit");
}


gfloat resistor_get_ac (Resistor* self) {
	gfloat result;
	gfloat _tmp0_ = 0.0F;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->priv->_ac;
	result = _tmp0_;
	return result;
}


void resistor_set_ac (Resistor* self, gfloat value) {
	gfloat _tmp0_ = 0.0F;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_ac = _tmp0_;
	g_object_notify ((GObject *) self, "ac");
}


gfloat resistor_get_dtemp (Resistor* self) {
	gfloat result;
	gfloat _tmp0_ = 0.0F;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->priv->_dtemp;
	result = _tmp0_;
	return result;
}


void resistor_set_dtemp (Resistor* self, gfloat value) {
	gfloat _tmp0_ = 0.0F;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_dtemp = _tmp0_;
	g_object_notify ((GObject *) self, "dtemp");
}


gfloat resistor_get_bv_max (Resistor* self) {
	gfloat result;
	gfloat _tmp0_ = 0.0F;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->priv->_bv_max;
	result = _tmp0_;
	return result;
}


void resistor_set_bv_max (Resistor* self, gfloat value) {
	gfloat _tmp0_ = 0.0F;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_bv_max = _tmp0_;
	g_object_notify ((GObject *) self, "bv-max");
}


gfloat resistor_get_noisy (Resistor* self) {
	gfloat result;
	gfloat _tmp0_ = 0.0F;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->priv->_noisy;
	result = _tmp0_;
	return result;
}


void resistor_set_noisy (Resistor* self, gfloat value) {
	gfloat _tmp0_ = 0.0F;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_noisy = _tmp0_;
	g_object_notify ((GObject *) self, "noisy");
}


gfloat resistor_get_i (Resistor* self) {
	gfloat result;
	gfloat _tmp0_ = 0.0F;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->priv->_i;
	result = _tmp0_;
	return result;
}


void resistor_set_i (Resistor* self, gfloat value) {
	gfloat _tmp0_ = 0.0F;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_i = _tmp0_;
	g_object_notify ((GObject *) self, "i");
}


gfloat resistor_get_p (Resistor* self) {
	gfloat result;
	gfloat _tmp0_ = 0.0F;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->priv->_p;
	result = _tmp0_;
	return result;
}


void resistor_set_p (Resistor* self, gfloat value) {
	gfloat _tmp0_ = 0.0F;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_p = _tmp0_;
	g_object_notify ((GObject *) self, "p");
}


static void resistor_class_init (ResistorClass * klass) {
	resistor_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ResistorPrivate));
	COMPONENT_CLASS (klass)->draw_symbol = resistor_real_draw_symbol;
	COMPONENT_CLASS (klass)->clone = resistor_real_clone;
	COMPONENT_CLASS (klass)->snap = resistor_real_snap;
	COMPONENT_CLASS (klass)->insertSimulationData = resistor_real_insertSimulationData;
	COMPONENT_CLASS (klass)->getNetlistLine = resistor_real_getNetlistLine;
	G_OBJECT_CLASS (klass)->get_property = _vala_resistor_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_resistor_set_property;
	G_OBJECT_CLASS (klass)->finalize = resistor_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), RESISTOR_RESISTANCE, g_param_spec_float ("resistance", "resistance", "resistance", -G_MAXFLOAT, G_MAXFLOAT, (gfloat) 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), RESISTOR_RESISTANCE_UNIT, g_param_spec_string ("resistanceUnit", "resistanceUnit", "resistanceUnit", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), RESISTOR_AC, g_param_spec_float ("ac", "ac", "ac", -G_MAXFLOAT, G_MAXFLOAT, (gfloat) 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), RESISTOR_DTEMP, g_param_spec_float ("dtemp", "dtemp", "dtemp", -G_MAXFLOAT, G_MAXFLOAT, (gfloat) 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), RESISTOR_BV_MAX, g_param_spec_float ("bv-max", "bv-max", "bv-max", -G_MAXFLOAT, G_MAXFLOAT, (gfloat) 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), RESISTOR_NOISY, g_param_spec_float ("noisy", "noisy", "noisy", -G_MAXFLOAT, G_MAXFLOAT, (gfloat) 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), RESISTOR_I, g_param_spec_float ("i", "i", "i", -G_MAXFLOAT, G_MAXFLOAT, (gfloat) 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), RESISTOR_P, g_param_spec_float ("p", "p", "p", -G_MAXFLOAT, G_MAXFLOAT, (gfloat) 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void resistor_instance_init (Resistor * self) {
	gchar* _tmp0_ = NULL;
	self->priv = RESISTOR_GET_PRIVATE (self);
	self->priv->_resistance = (gfloat) 0;
	_tmp0_ = g_strdup ("");
	self->priv->_resistanceUnit = _tmp0_;
	self->priv->_ac = (gfloat) 0;
	self->priv->_dtemp = (gfloat) 0;
	self->priv->_bv_max = (gfloat) 0;
	self->priv->_noisy = (gfloat) 0;
	self->priv->_i = (gfloat) 0;
	self->priv->_p = (gfloat) 0;
}


static void resistor_finalize (GObject* obj) {
	Resistor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_RESISTOR, Resistor);
	_g_free0 (self->priv->_resistanceUnit);
	G_OBJECT_CLASS (resistor_parent_class)->finalize (obj);
}


GType resistor_get_type (void) {
	static volatile gsize resistor_type_id__volatile = 0;
	if (g_once_init_enter (&resistor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ResistorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) resistor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Resistor), 0, (GInstanceInitFunc) resistor_instance_init, NULL };
		GType resistor_type_id;
		resistor_type_id = g_type_register_static (TYPE_COMPONENT, "Resistor", &g_define_type_info, 0);
		g_once_init_leave (&resistor_type_id__volatile, resistor_type_id);
	}
	return resistor_type_id__volatile;
}


static void _vala_resistor_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	Resistor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_RESISTOR, Resistor);
	switch (property_id) {
		case RESISTOR_RESISTANCE:
		g_value_set_float (value, resistor_get_resistance (self));
		break;
		case RESISTOR_RESISTANCE_UNIT:
		g_value_set_string (value, resistor_get_resistanceUnit (self));
		break;
		case RESISTOR_AC:
		g_value_set_float (value, resistor_get_ac (self));
		break;
		case RESISTOR_DTEMP:
		g_value_set_float (value, resistor_get_dtemp (self));
		break;
		case RESISTOR_BV_MAX:
		g_value_set_float (value, resistor_get_bv_max (self));
		break;
		case RESISTOR_NOISY:
		g_value_set_float (value, resistor_get_noisy (self));
		break;
		case RESISTOR_I:
		g_value_set_float (value, resistor_get_i (self));
		break;
		case RESISTOR_P:
		g_value_set_float (value, resistor_get_p (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_resistor_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	Resistor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_RESISTOR, Resistor);
	switch (property_id) {
		case RESISTOR_RESISTANCE:
		resistor_set_resistance (self, g_value_get_float (value));
		break;
		case RESISTOR_RESISTANCE_UNIT:
		resistor_set_resistanceUnit (self, g_value_get_string (value));
		break;
		case RESISTOR_AC:
		resistor_set_ac (self, g_value_get_float (value));
		break;
		case RESISTOR_DTEMP:
		resistor_set_dtemp (self, g_value_get_float (value));
		break;
		case RESISTOR_BV_MAX:
		resistor_set_bv_max (self, g_value_get_float (value));
		break;
		case RESISTOR_NOISY:
		resistor_set_noisy (self, g_value_get_float (value));
		break;
		case RESISTOR_I:
		resistor_set_i (self, g_value_get_float (value));
		break;
		case RESISTOR_P:
		resistor_set_p (self, g_value_get_float (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



