# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "elektrosim")
set(elektrosim_VERSION "0.0.0")
set(required_pkgs
  "atk {nolink}"
  "cairo {nolink}"
  "gdk-3.0"
  "gdk-pixbuf-2.0 {nolink}"
  "gee-0.8"
  "gio-2.0"
  "glib-2.0"
  "gobject-2.0"
  "gtk+-3.0"
  "librsvg-2.0"
  "ngspice"
  "pango {nolink}"
  "pangocairo {nolink}"
  "x11 {nolink}"
)
set(srcfiles
  "src/Line.vala"
  "src/NGSpiceSimulator.vala"
  "src/XYGraph.vala"
  "src/component.vala"
  "src/componentlist.vala"
  "src/elektrosim.vala"
  "src/ground.vala"
  "src/parameter.vala"
  "src/point.vala"
  "src/power-source.vala"
  "src/resistor.vala"
  "src/simulation.vala"
  "src/simulationArea.vala"
)
set(vapifiles
  "vapi/config.vapi"
)
set(uifiles
)
